package sun.text.resources.cldr.ca;

import java.util.ListResourceBundle;

public class FormatData_ca extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "de gener", "de febrer", "de mar\u00e7", "d\u2019abril", "de maig", "de juny", "de juliol", "d\u2019agost", "de setembre", "d\u2019octubre", "de novembre", "de desembre", "" } }, { "standalone.MonthNames", { "gener", "febrer", "mar\u00e7", "abril", "maig", "juny", "juliol", "agost", "setembre", "octubre", "novembre", "desembre", "" } }, { "MonthAbbreviations", { "de gen.", "de febr.", "de mar\u00e7", "d\u2019abr.", "de maig", "de juny", "de jul.", "d\u2019ag.", "de set.", "d\u2019oct.", "de nov.", "de des.", "" } }, { "standalone.MonthAbbreviations", { "gen.", "febr.", "mar\u00e7", "abr.", "maig", "juny", "jul.", "ag.", "set.", "oct.", "nov.", "des.", "" } }, { "MonthNarrows", { "G", "F", "M", "A", "M", "J", "G", "A", "S", "O", "N", "D", "" } }, { "standalone.MonthNarrows", { "g", "f", "m", "a", "m", "j", "j", "a", "s", "o", "n", "d", "" } }, { "DayNames", { "diumenge", "dilluns", "dimarts", "dimecres", "dijous", "divendres", "dissabte" } }, { "standalone.DayNames", { "Diumenge", "Dilluns", "Dimarts", "Dimecres", "Dijous", "Divendres", "Dissabte" } }, { "DayAbbreviations", { "dg.", "dl.", "dt.", "dc.", "dj.", "dv.", "ds." } }, { "standalone.DayAbbreviations", { "dg", "dl", "dt", "dc", "dj", "dv", "ds" } }, { "DayNarrows", { "G", "l", "T", "C", "J", "V", "S" } }, { "standalone.DayNarrows", { "g", "l", "t", "c", "j", "v", "s" } }, { "QuarterNames", { "1r trimestre", "2n trimestre", "3r trimestre", "4t trimestre" } }, { "standalone.QuarterNames", { "1r trimestre", "2n trimestre", "3r trimestre", "4t trimestre" } }, { "QuarterAbbreviations", { "1T", "2T", "3T", "4T" } }, { "standalone.QuarterAbbreviations", { "1T", "2T", "3T", "4T" } }, { "QuarterNarrows", { "1", "2", "3", "4" } }, { "AmPmMarkers", { "a.m.", "p.m." } }, { "Eras", { "aC", "dC" } }, { "field.era", "era" }, { "field.year", "any" }, { "field.month", "mes" }, { "field.week", "setmana" }, { "field.weekday", "dia de la setmana" }, { "field.dayperiod", "a.m./p.m." }, { "field.hour", "hora" }, { "field.minute", "minut" }, { "field.second", "segon" }, { "field.zone", "zona" }, { "TimePatterns", { "H:mm:ss zzzz", "H:mm:ss z", "H:mm:ss", "H:mm" } }, { "DatePatterns", { "EEEE d MMMM 'de' y", "d MMMM 'de' y", "dd/MM/yyyy", "dd/MM/yy" } }, { "calendarname.gregorian", "calendari gregori\u00e0" }, { "calendarname.gregory", "calendari gregori\u00e0" }, { "calendarname.roc", "calendari de la Rep\u00fablica de Xina" }, { "calendarname.islamic-civil", "calendari civil isl\u00e0mic" }, { "calendarname.islamicc", "calendari civil isl\u00e0mic" }, { "calendarname.japanese", "calendari japon\u00e8s" }, { "calendarname.buddhist", "calendari budista" }, { "calendarname.islamic", "calendari musulm\u00e0" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ",", ".", ";", "%", "0", "#", "-", "E", "\u2030", "\u221e", "NaN" } }, { "NumberPatterns", { "#,##0.###", "#,##0.00ад", "#,##0%" } } };
    }
}
