package com.sun.org.apache.xalan.internal.xsltc.runtime;

import java.util.ListResourceBundle;

public class ErrorMessages_es extends ListResourceBundle
{
    public Object[][] getContents() {
        return new Object[][] { { "RUN_TIME_INTERNAL_ERR", "Error interno de tiempo de ejecuci\u00f3n en ''{0}''" }, { "RUN_TIME_COPY_ERR", "Error de tiempo de ejecuci\u00f3n al ejecutar <xsl:copy>." }, { "DATA_CONVERSION_ERR", "Conversi\u00f3n no v\u00e1lida de ''{0}'' a ''{1}''." }, { "EXTERNAL_FUNC_ERR", "Funci\u00f3n externa ''{0}'' no soportada por XSLTC." }, { "EQUALITY_EXPR_ERR", "Tipo de argumento desconocido en la expresi\u00f3n de igualdad." }, { "INVALID_ARGUMENT_ERR", "Tipo de argumento ''{0}'' no v\u00e1lido en la llamada a ''{1}''" }, { "FORMAT_NUMBER_ERR", "Intentando formatear n\u00famero ''{0}'' mediante el patr\u00f3n ''{1}''." }, { "ITERATOR_CLONE_ERR", "No se puede clonar el iterador ''{0}''." }, { "AXIS_SUPPORT_ERR", "El iterador para el eje ''{0}'' no est\u00e1 soportado." }, { "TYPED_AXIS_SUPPORT_ERR", "El iterador para el eje introducido ''{0}'' no est\u00e1 soportado." }, { "STRAY_ATTRIBUTE_ERR", "El atributo ''{0}'' est\u00e1 fuera del elemento." }, { "STRAY_NAMESPACE_ERR", "Declaraci\u00f3n del espacio de nombres ''{0}''=''{1}'' fuera del elemento." }, { "NAMESPACE_PREFIX_ERR", "No se ha declarado el espacio de nombres para el prefijo ''{0}''." }, { "DOM_ADAPTER_INIT_ERR", "Se ha creado DOMAdapter mediante un tipo incorrecto de DOM de origen." }, { "PARSER_DTD_SUPPORT_ERR", "El analizador SAX que est\u00e1 utilizando no maneja los eventos de declaraci\u00f3n DTD." }, { "NAMESPACES_SUPPORT_ERR", "El analizador SAX que est\u00e1 utilizando no soporta los espacios de nombres XML." }, { "CANT_RESOLVE_RELATIVE_URI_ERR", "No se ha podido resolver la referencia al URI ''{0}''." }, { "UNSUPPORTED_XSL_ERR", "Elemento ''{0}'' de XSL no soportado" }, { "UNSUPPORTED_EXT_ERR", "Extensi\u00f3n ''{0}'' de XSLTC no reconocida" }, { "UNKNOWN_TRANSLET_VERSION_ERR", "El translet especificado, ''{0}'' se ha creado con una versi\u00f3n de XSLTC m\u00e1s reciente que la versi\u00f3n del tiempo de ejecuci\u00f3n de XSLTC que se est\u00e1 utilizando. Debe volver a compilar la hoja de estilo o utilizar una versi\u00f3n m\u00e1s reciente de XSLTC para ejecutar este translet." }, { "INVALID_QNAME_ERR", "Un atributo cuyo valor debe ser un QName ten\u00eda el valor ''{0}''" }, { "INVALID_NCNAME_ERR", "Un atributo cuyo valor debe ser un NCName ten\u00eda el valor ''{0}''" }, { "UNALLOWED_EXTENSION_FUNCTION_ERR", "El uso de la funci\u00f3n de extensi\u00f3n ''{0}'' no est\u00e1 permitido cuando la funci\u00f3n de procesamiento seguro se ha definido en true." }, { "UNALLOWED_EXTENSION_ELEMENT_ERR", "El uso del elemento de extensi\u00f3n ''{0}'' no est\u00e1 permitido cuando la funci\u00f3n de procesamiento seguro se ha definido en true." } };
    }
}
