package com.sun.org.apache.xalan.internal.xsltc.runtime;

import java.util.ListResourceBundle;

public class ErrorMessages_sv extends ListResourceBundle
{
    public Object[][] getContents() {
        return new Object[][] { { "RUN_TIME_INTERNAL_ERR", "Internt exekveringsfel i ''{0}''" }, { "RUN_TIME_COPY_ERR", "Exekveringsexekveringsfel av <xsl:copy>." }, { "DATA_CONVERSION_ERR", "Ogiltig konvertering fr\u00e5n ''{0}'' till ''{1}''." }, { "EXTERNAL_FUNC_ERR", "Den externa funktionen ''{0}'' underst\u00f6ds inte i XSLTC." }, { "EQUALITY_EXPR_ERR", "Ok\u00e4nd argumenttyp i likhetsuttryck." }, { "INVALID_ARGUMENT_ERR", "Argumenttyp ''{0}'' i anrop till ''{1}'' \u00e4r inte giltig" }, { "FORMAT_NUMBER_ERR", "F\u00f6rs\u00f6ker formatera talet ''{0}'' med m\u00f6nstret ''{1}''." }, { "ITERATOR_CLONE_ERR", "Kan inte klona iteratorn ''{0}''." }, { "AXIS_SUPPORT_ERR", "Iteratorn f\u00f6r axeln ''{0}'' underst\u00f6ds inte." }, { "TYPED_AXIS_SUPPORT_ERR", "Iteratorn f\u00f6r den typade axeln ''{0}'' underst\u00f6ds inte." }, { "STRAY_ATTRIBUTE_ERR", "Attributet ''{0}'' finns utanf\u00f6r elementet." }, { "STRAY_NAMESPACE_ERR", "Namnrymdsdeklarationen ''{0}''=''{1}'' finns utanf\u00f6r element." }, { "NAMESPACE_PREFIX_ERR", "Namnrymd f\u00f6r prefix ''{0}'' har inte deklarerats." }, { "DOM_ADAPTER_INIT_ERR", "DOMAdapter har skapats med fel typ av DOM-k\u00e4lla." }, { "PARSER_DTD_SUPPORT_ERR", "Den SAX-parser som du anv\u00e4nder hanterar inga DTD-deklarationsh\u00e4ndelser." }, { "NAMESPACES_SUPPORT_ERR", "Den SAX-parser som du anv\u00e4nder saknar st\u00f6d f\u00f6r XML-namnrymder." }, { "CANT_RESOLVE_RELATIVE_URI_ERR", "Kunde inte matcha URI-referensen ''{0}''." }, { "UNSUPPORTED_XSL_ERR", "XSL-elementet ''{0}'' st\u00f6ds inte" }, { "UNSUPPORTED_EXT_ERR", "XSLTC-till\u00e4gget ''{0}'' \u00e4r ok\u00e4nt" }, { "UNKNOWN_TRANSLET_VERSION_ERR", "Angiven translet, ''{0}'', har skapats med en XSLTC-version som \u00e4r senare \u00e4n den XSLTC-k\u00f6rning i bruk. F\u00f6r att kunna k\u00f6ra denna translet m\u00e5ste du omkompilera formatmallen eller anv\u00e4nda en senare version av XSLTC." }, { "INVALID_QNAME_ERR", "Ett attribut vars v\u00e4rde m\u00e5ste vara ett QName hade v\u00e4rdet ''{0}''" }, { "INVALID_NCNAME_ERR", "Ett attribut vars v\u00e4rde m\u00e5ste vara ett NCName hade v\u00e4rdet ''{0}''" }, { "UNALLOWED_EXTENSION_FUNCTION_ERR", "Anv\u00e4ndning av till\u00e4ggsfunktionen ''{0}'' \u00e4r inte till\u00e5tet n\u00e4r s\u00e4ker bearbetning till\u00e4mpas." }, { "UNALLOWED_EXTENSION_ELEMENT_ERR", "Anv\u00e4ndning av till\u00e4ggselementet ''{0}'' \u00e4r inte till\u00e5tet n\u00e4r s\u00e4ker bearbetning till\u00e4mpas." } };
    }
}
