package com.sun.org.apache.xalan.internal.xsltc.runtime;

import java.util.ListResourceBundle;

public class ErrorMessages_de extends ListResourceBundle
{
    public Object[][] getContents() {
        return new Object[][] { { "RUN_TIME_INTERNAL_ERR", "Interner Laufzeitfehler in \"{0}\"" }, { "RUN_TIME_COPY_ERR", "Laufzeitfehler beim Ausf\u00fchren von <xsl:copy>." }, { "DATA_CONVERSION_ERR", "Ung\u00fcltige Konvertierung von \"{0}\" in \"{1}\"." }, { "EXTERNAL_FUNC_ERR", "Externe Funktion \"{0}\" nicht unterst\u00fctzt von XSLTC." }, { "EQUALITY_EXPR_ERR", "Unbekannter Argumenttyp in Gleichheitsausdruck." }, { "INVALID_ARGUMENT_ERR", "Ung\u00fcltiger Argumenttyp \"{0}\" in Aufruf von \"{1}\"" }, { "FORMAT_NUMBER_ERR", "Versuch, Zahl \"{0}\" mit Muster \"{1}\" zu formatieren." }, { "ITERATOR_CLONE_ERR", "Iterator \"{0}\" kann nicht geclont werden." }, { "AXIS_SUPPORT_ERR", "Iterator f\u00fcr Achse \"{0}\" nicht unterst\u00fctzt." }, { "TYPED_AXIS_SUPPORT_ERR", "Iterator f\u00fcr typisierte Achse \"{0}\" nicht unterst\u00fctzt." }, { "STRAY_ATTRIBUTE_ERR", "Attribut \"{0}\" au\u00dferhalb des Elements." }, { "STRAY_NAMESPACE_ERR", "Namespace-Deklaration {0}={1} au\u00dferhalb des Elements." }, { "NAMESPACE_PREFIX_ERR", "Namespace f\u00fcr Pr\u00e4fix \"{0}\" wurde nicht deklariert." }, { "DOM_ADAPTER_INIT_ERR", "DOMAdapter mit falschem Typ von Quell-DOM erstellt." }, { "PARSER_DTD_SUPPORT_ERR", "Der verwendete SAX-Parser verarbeitet keine DTD-Deklarationsereignisse." }, { "NAMESPACES_SUPPORT_ERR", "Der verwendete SAX-Parser unterst\u00fctzt keine XML-Namespaces." }, { "CANT_RESOLVE_RELATIVE_URI_ERR", "URI-Referenz \"{0}\" konnte nicht aufgel\u00f6st werden." }, { "UNSUPPORTED_XSL_ERR", "Nicht unterst\u00fctztes XSL-Element \"{0}\"" }, { "UNSUPPORTED_EXT_ERR", "Unbekannte XSLTC-Erweiterung \"{0}\"" }, { "UNKNOWN_TRANSLET_VERSION_ERR", "Das angegebene Translet \"{0}\" wurde mit einer neueren Version von XSLTC als die verwendete Version der XSLTC-Laufzeit erstellt. Sie m\u00fcssen das Stylesheet neu kompilieren oder eine aktuellere Version von XSLTC verwenden, um dieses Translet auszuf\u00fchren." }, { "INVALID_QNAME_ERR", "Ein Attribut, dessen Wert ein QName sein muss, hatte den Wert \"{0}\"" }, { "INVALID_NCNAME_ERR", "Ein Attribut, dessen Wert ein NCName sein muss, hatte den Wert \"{0}\"" }, { "UNALLOWED_EXTENSION_FUNCTION_ERR", "Verwendung der Erweiterungsfunktion \"{0}\" ist nicht zul\u00e4ssig, wenn das Feature f\u00fcr die sichere Verarbeitung auf \"true\" gesetzt ist." }, { "UNALLOWED_EXTENSION_ELEMENT_ERR", "Verwendung des Erweiterungselements \"{0}\" ist nicht zul\u00e4ssig, wenn das Feature f\u00fcr die sichere Verarbeitung auf \"true\" gesetzt ist." } };
    }
}
