package sun.text.resources.cldr.kea;

import java.util.ListResourceBundle;

public class FormatData_kea extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "Janeru", "Fevereru", "Marsu", "Abril", "Maiu", "Junhu", "Julhu", "Agostu", "Setenbru", "Otubru", "Nuvenbru", "Dizenbru", "" } }, { "standalone.MonthNames", { "Janeru", "Fevereru", "Marsu", "Abril", "Maiu", "Junhu", "Julhu", "Agostu", "Setenbru", "Otubru", "Nuvenbru", "Dizenbru", "" } }, { "MonthAbbreviations", { "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Otu", "Nuv", "Diz", "" } }, { "standalone.MonthAbbreviations", { "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Otu", "Nuv", "Diz", "" } }, { "MonthNarrows", { "J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D", "" } }, { "standalone.MonthNarrows", { "J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D", "" } }, { "DayNames", { "dumingu", "sigunda-fera", "tersa-fera", "kuarta-fera", "kinta-fera", "sesta-fera", "sabadu" } }, { "standalone.DayNames", { "dumingu", "sigunda-fera", "tersa-fera", "kuarta-fera", "kinta-fera", "sesta-fera", "sabadu" } }, { "DayAbbreviations", { "dum", "sig", "ter", "kua", "kin", "ses", "sab" } }, { "standalone.DayAbbreviations", { "dum", "sig", "ter", "kua", "kin", "ses", "sab" } }, { "DayNarrows", { "d", "s", "t", "k", "k", "s", "s" } }, { "standalone.DayNarrows", { "d", "s", "t", "k", "k", "s", "s" } }, { "QuarterNames", { "Primeru Trimestri", "Sigundu Trimestri", "Terseru Trimestri", "Kuartu Trimestri" } }, { "standalone.QuarterNames", { "Primeru Trimestri", "Sigundu Trimestri", "Terseru Trimestri", "Kuartu Trimestri" } }, { "QuarterAbbreviations", { "T1", "T2", "T3", "T4" } }, { "standalone.QuarterAbbreviations", { "T1", "T2", "T3", "T4" } }, { "QuarterNarrows", { "1", "2", "3", "4" } }, { "AmPmMarkers", { "am", "pm" } }, { "long.Eras", { "Antis di Kristu", "Dispos di Kristu" } }, { "Eras", { "AK", "DK" } }, { "field.era", "Era" }, { "field.year", "Anu" }, { "field.month", "Mes" }, { "field.week", "Simana" }, { "field.weekday", "Dia di simana" }, { "field.dayperiod", "am/pm" }, { "field.hour", "Ora" }, { "field.minute", "Minutu" }, { "field.second", "Sigundu" }, { "field.zone", "Ora lokal" }, { "TimePatterns", { "HH:mm:ss zzzz", "HH:mm:ss z", "HH:mm:ss", "HH:mm" } }, { "DatePatterns", { "EEEE, d 'di' MMMM 'di' y", "d 'di' MMMM 'di' y", "d 'di' MMM 'di' y", "d/M/yyyy" } }, { "calendarname.gregorian", "Kalendariu Gregorianu" }, { "calendarname.gregory", "Kalendariu Gregorianu" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ",", ".", ";", "%", "0", "#", "-", "E", "\u2030", "\u221e", "NaN" } }, { "NumberPatterns", { "#,##0.###", "#,##0.00¤", "#,##0%" } } };
    }
}
