package sun.util.resources.cldr.mas;

import sun.util.resources.OpenListResourceBundle;

public class CurrencyNames_mas extends OpenListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "KES", "Ksh" }, { "aed", "Iropiyian\u00ed \u0254\u0301\u0254\u0304 lmarabu" }, { "aoa", "Iropiyian\u00ed e Angola" }, { "aud", "Iropiyian\u00ed e Austria" }, { "bhd", "Iropiyian\u00ed e Bahareini" }, { "bif", "Iropiyian\u00ed e Burundi" }, { "bwp", "Iropiyian\u00ed e Botswana" }, { "cad", "Iropiyian\u00ed e Kanada" }, { "cdf", "Iropiyian\u00ed e Kongo" }, { "chf", "Iropiyian\u00ed e Uswisi" }, { "cny", "Iropiyian\u00ed e China" }, { "cve", "Iropiyian\u00ed e Kepuvede" }, { "djf", "Iropiyian\u00ed e Jibuti" }, { "dzd", "Iropiyian\u00ed e Algeria" }, { "egp", "Iropiyian\u00ed e Misri" }, { "ern", "Iropiyian\u00ed e Eritrea" }, { "etb", "Iropiyian\u00ed e Uhabeshi" }, { "eur", "Iropiyian\u00ed e yuro" }, { "gbp", "Iropiyian\u00ed e Nk\u0268\u0301resa" }, { "ghc", "Iropiyian\u00ed e Ghana" }, { "gmd", "Iropiyian\u00ed e Gambia" }, { "gns", "Iropiyian\u00ed e Gine" }, { "inr", "Iropiyian\u00ed e India" }, { "jpy", "Iropiyian\u00ed e Japani" }, { "kes", "Iropiyian\u00ed e Kenya" }, { "kmf", "Iropiyian\u00ed e Komoro" }, { "lrd", "Iropiyian\u00ed e Liberia" }, { "lsl", "Iropiyian\u00ed e Lesoto" }, { "lyd", "Iropiyian\u00ed e Libya" }, { "mad", "Iropiyian\u00ed e Moroko" }, { "mga", "Iropiyian\u00ed e Bukini" }, { "mro", "Iropiyian\u00ed e Moritania" }, { "mur", "Iropiyian\u00ed e Morisi" }, { "mwk", "Iropiyian\u00ed e Malawi" }, { "mzm", "Iropiyian\u00ed e Msumbiji" }, { "nad", "Iropiyian\u00ed e Namibia" }, { "ngn", "Iropiyian\u00ed e Nijeria" }, { "rwf", "Iropiyian\u00ed e Rwanda" }, { "sar", "Iropiyian\u00ed e Saudi" }, { "scr", "Iropiyian\u00ed e Shelisheli" }, { "sdg", "Iropiyian\u00ed e Sudani" }, { "shp", "Iropiyian\u00ed e Santahelena" }, { "sll", "Iropiyian\u00ed e leoni" }, { "sos", "Iropiyian\u00ed e Somalia" }, { "std", "Iropiyian\u00ed e Saotome" }, { "szl", "Iropiyian\u00ed e lilangeni" }, { "tnd", "Iropiyian\u00ed e Tunisia" }, { "tzs", "Iropiyian\u00ed e Tanzania" }, { "ugx", "Iropiyian\u00ed e Uganda" }, { "usd", "Iropiyian\u00ed \u0254\u0301\u0254\u0304 lamarekani" }, { "xaf", "Iropiyian\u00ed e CFA BEAC" }, { "xof", "Iropiyian\u00ed e CFA BCEAO" }, { "zar", "Iropiyian\u00ed e Afrika Kusini" }, { "zmk", "Iropiyian\u00ed e Sambia" }, { "zwd", "Iropiyian\u00ed e Simbabwe" } };
    }
}
