package com.lowagie.text.pdf;

import java.lang.reflect.Field;
import java.util.HashMap;
import com.lowagie.text.error_messages.MessageLocalization;
import java.util.Map;

public class PdfName extends PdfObject implements Comparable
{
    public static final PdfName _3D;
    public static final PdfName A;
    public static final PdfName AA;
    public static final PdfName ABSOLUTECOLORIMETRIC;
    public static final PdfName AC;
    public static final PdfName ACROFORM;
    public static final PdfName ACTION;
    public static final PdfName ACTIVATION;
    public static final PdfName ADBE;
    public static final PdfName ACTUALTEXT;
    public static final PdfName ADBE_PKCS7_DETACHED;
    public static final PdfName ADBE_PKCS7_S4;
    public static final PdfName ADBE_PKCS7_S5;
    public static final PdfName ADBE_PKCS7_SHA1;
    public static final PdfName ADBE_X509_RSA_SHA1;
    public static final PdfName ADOBE_PPKLITE;
    public static final PdfName ADOBE_PPKMS;
    public static final PdfName AESV2;
    public static final PdfName AIS;
    public static final PdfName ALLPAGES;
    public static final PdfName ALT;
    public static final PdfName ALTERNATE;
    public static final PdfName ANIMATION;
    public static final PdfName ANNOT;
    public static final PdfName ANNOTS;
    public static final PdfName ANTIALIAS;
    public static final PdfName AP;
    public static final PdfName APPDEFAULT;
    public static final PdfName ART;
    public static final PdfName ARTBOX;
    public static final PdfName ASCENT;
    public static final PdfName AS;
    public static final PdfName ASCII85DECODE;
    public static final PdfName ASCIIHEXDECODE;
    public static final PdfName ASSET;
    public static final PdfName ASSETS;
    public static final PdfName AUTHEVENT;
    public static final PdfName AUTHOR;
    public static final PdfName B;
    public static final PdfName BACKGROUND;
    public static final PdfName BASEENCODING;
    public static final PdfName BASEFONT;
    public static final PdfName BASEVERSION;
    public static final PdfName BBOX;
    public static final PdfName BC;
    public static final PdfName BG;
    public static final PdfName BIBENTRY;
    public static final PdfName BIGFIVE;
    public static final PdfName BINDING;
    public static final PdfName BINDINGMATERIALNAME;
    public static final PdfName BITSPERCOMPONENT;
    public static final PdfName BITSPERSAMPLE;
    public static final PdfName BL;
    public static final PdfName BLACKIS1;
    public static final PdfName BLACKPOINT;
    public static final PdfName BLOCKQUOTE;
    public static final PdfName BLEEDBOX;
    public static final PdfName BLINDS;
    public static final PdfName BM;
    public static final PdfName BORDER;
    public static final PdfName BOUNDS;
    public static final PdfName BOX;
    public static final PdfName BS;
    public static final PdfName BTN;
    public static final PdfName BYTERANGE;
    public static final PdfName C;
    public static final PdfName C0;
    public static final PdfName C1;
    public static final PdfName CA;
    public static final PdfName ca;
    public static final PdfName CALGRAY;
    public static final PdfName CALRGB;
    public static final PdfName CAPHEIGHT;
    public static final PdfName CAPTION;
    public static final PdfName CATALOG;
    public static final PdfName CATEGORY;
    public static final PdfName CCITTFAXDECODE;
    public static final PdfName CENTER;
    public static final PdfName CENTERWINDOW;
    public static final PdfName CERT;
    public static final PdfName CF;
    public static final PdfName CFM;
    public static final PdfName CH;
    public static final PdfName CHARPROCS;
    public static final PdfName CHECKSUM;
    public static final PdfName CI;
    public static final PdfName CIDFONTTYPE0;
    public static final PdfName CIDFONTTYPE2;
    public static final PdfName CIDSET;
    public static final PdfName CIDSYSTEMINFO;
    public static final PdfName CIDTOGIDMAP;
    public static final PdfName CIRCLE;
    public static final PdfName CMD;
    public static final PdfName CO;
    public static final PdfName CODE;
    public static final PdfName COLORS;
    public static final PdfName COLORSPACE;
    public static final PdfName COLLECTION;
    public static final PdfName COLLECTIONFIELD;
    public static final PdfName COLLECTIONITEM;
    public static final PdfName COLLECTIONSCHEMA;
    public static final PdfName COLLECTIONSORT;
    public static final PdfName COLLECTIONSUBITEM;
    public static final PdfName COLUMNS;
    public static final PdfName CONDITION;
    public static final PdfName CONFIGURATION;
    public static final PdfName CONFIGURATIONS;
    public static final PdfName CONTACTINFO;
    public static final PdfName CONTENT;
    public static final PdfName CONTENTS;
    public static final PdfName COORDS;
    public static final PdfName COUNT;
    public static final PdfName COURIER;
    public static final PdfName COURIER_BOLD;
    public static final PdfName COURIER_OBLIQUE;
    public static final PdfName COURIER_BOLDOBLIQUE;
    public static final PdfName CREATIONDATE;
    public static final PdfName CREATOR;
    public static final PdfName CREATORINFO;
    public static final PdfName CROPBOX;
    public static final PdfName CRYPT;
    public static final PdfName CS;
    public static final PdfName CUEPOINT;
    public static final PdfName CUEPOINTS;
    public static final PdfName D;
    public static final PdfName DA;
    public static final PdfName DATA;
    public static final PdfName DC;
    public static final PdfName DCTDECODE;
    public static final PdfName DEACTIVATION;
    public static final PdfName DECODE;
    public static final PdfName DECODEPARMS;
    public static final PdfName DEFAULT;
    public static final PdfName DEFAULTCRYPTFILTER;
    public static final PdfName DEFAULTCMYK;
    public static final PdfName DEFAULTGRAY;
    public static final PdfName DEFAULTRGB;
    public static final PdfName DESC;
    public static final PdfName DESCENDANTFONTS;
    public static final PdfName DESCENT;
    public static final PdfName DEST;
    public static final PdfName DESTOUTPUTPROFILE;
    public static final PdfName DESTS;
    public static final PdfName DEVICEGRAY;
    public static final PdfName DEVICERGB;
    public static final PdfName DEVICECMYK;
    public static final PdfName DI;
    public static final PdfName DIFFERENCES;
    public static final PdfName DISSOLVE;
    public static final PdfName DIRECTION;
    public static final PdfName DISPLAYDOCTITLE;
    public static final PdfName DIV;
    public static final PdfName DL;
    public static final PdfName DM;
    public static final PdfName DOCMDP;
    public static final PdfName DOCOPEN;
    public static final PdfName DOCUMENT;
    public static final PdfName DOMAIN;
    public static final PdfName DP;
    public static final PdfName DR;
    public static final PdfName DS;
    public static final PdfName DUR;
    public static final PdfName DUPLEX;
    public static final PdfName DUPLEXFLIPSHORTEDGE;
    public static final PdfName DUPLEXFLIPLONGEDGE;
    public static final PdfName DV;
    public static final PdfName DW;
    public static final PdfName E;
    public static final PdfName EARLYCHANGE;
    public static final PdfName EF;
    public static final PdfName EFF;
    public static final PdfName EFOPEN;
    public static final PdfName EMBEDDED;
    public static final PdfName EMBEDDEDFILE;
    public static final PdfName EMBEDDEDFILES;
    public static final PdfName ENCODE;
    public static final PdfName ENCODEDBYTEALIGN;
    public static final PdfName ENCODING;
    public static final PdfName ENCRYPT;
    public static final PdfName ENCRYPTMETADATA;
    public static final PdfName ENDOFBLOCK;
    public static final PdfName ENDOFLINE;
    public static final PdfName EXTEND;
    public static final PdfName EXTENSIONS;
    public static final PdfName EXTENSIONLEVEL;
    public static final PdfName EXTGSTATE;
    public static final PdfName EXPORT;
    public static final PdfName EXPORTSTATE;
    public static final PdfName EVENT;
    public static final PdfName F;
    public static final PdfName FAR;
    public static final PdfName FB;
    public static final PdfName FDECODEPARMS;
    public static final PdfName FDF;
    public static final PdfName FF;
    public static final PdfName FFILTER;
    public static final PdfName FIELDS;
    public static final PdfName FIGURE;
    public static final PdfName FILEATTACHMENT;
    public static final PdfName FILESPEC;
    public static final PdfName FILTER;
    public static final PdfName FIRST;
    public static final PdfName FIRSTCHAR;
    public static final PdfName FIRSTPAGE;
    public static final PdfName FIT;
    public static final PdfName FITH;
    public static final PdfName FITV;
    public static final PdfName FITR;
    public static final PdfName FITB;
    public static final PdfName FITBH;
    public static final PdfName FITBV;
    public static final PdfName FITWINDOW;
    public static final PdfName FLAGS;
    public static final PdfName FLASH;
    public static final PdfName FLASHVARS;
    public static final PdfName FLATEDECODE;
    public static final PdfName FO;
    public static final PdfName FONT;
    public static final PdfName FONTBBOX;
    public static final PdfName FONTDESCRIPTOR;
    public static final PdfName FONTFILE;
    public static final PdfName FONTFILE2;
    public static final PdfName FONTFILE3;
    public static final PdfName FONTMATRIX;
    public static final PdfName FONTNAME;
    public static final PdfName FOREGROUND;
    public static final PdfName FORM;
    public static final PdfName FORMTYPE;
    public static final PdfName FORMULA;
    public static final PdfName FREETEXT;
    public static final PdfName FRM;
    public static final PdfName FS;
    public static final PdfName FT;
    public static final PdfName FULLSCREEN;
    public static final PdfName FUNCTION;
    public static final PdfName FUNCTIONS;
    public static final PdfName FUNCTIONTYPE;
    public static final PdfName GAMMA;
    public static final PdfName GBK;
    public static final PdfName GLITTER;
    public static final PdfName GOTO;
    public static final PdfName GOTOE;
    public static final PdfName GOTOR;
    public static final PdfName GROUP;
    public static final PdfName GTS_PDFA1;
    public static final PdfName GTS_PDFX;
    public static final PdfName GTS_PDFXVERSION;
    public static final PdfName H;
    public static final PdfName H1;
    public static final PdfName H2;
    public static final PdfName H3;
    public static final PdfName H4;
    public static final PdfName H5;
    public static final PdfName H6;
    public static final PdfName HALIGN;
    public static final PdfName HEIGHT;
    public static final PdfName HELV;
    public static final PdfName HELVETICA;
    public static final PdfName HELVETICA_BOLD;
    public static final PdfName HELVETICA_OBLIQUE;
    public static final PdfName HELVETICA_BOLDOBLIQUE;
    public static final PdfName HID;
    public static final PdfName HIDE;
    public static final PdfName HIDEMENUBAR;
    public static final PdfName HIDETOOLBAR;
    public static final PdfName HIDEWINDOWUI;
    public static final PdfName HIGHLIGHT;
    public static final PdfName HOFFSET;
    public static final PdfName I;
    public static final PdfName ICCBASED;
    public static final PdfName ID;
    public static final PdfName IDENTITY;
    public static final PdfName IF;
    public static final PdfName IMAGE;
    public static final PdfName IMAGEB;
    public static final PdfName IMAGEC;
    public static final PdfName IMAGEI;
    public static final PdfName IMAGEMASK;
    public static final PdfName INDEX;
    public static final PdfName INDEXED;
    public static final PdfName INFO;
    public static final PdfName INK;
    public static final PdfName INKLIST;
    public static final PdfName INSTANCES;
    public static final PdfName IMPORTDATA;
    public static final PdfName INTENT;
    public static final PdfName INTERPOLATE;
    public static final PdfName ISMAP;
    public static final PdfName IRT;
    public static final PdfName ITALICANGLE;
    public static final PdfName ITXT;
    public static final PdfName IX;
    public static final PdfName JAVASCRIPT;
    public static final PdfName JBIG2DECODE;
    public static final PdfName JBIG2GLOBALS;
    public static final PdfName JPXDECODE;
    public static final PdfName JS;
    public static final PdfName K;
    public static final PdfName KEYWORDS;
    public static final PdfName KIDS;
    public static final PdfName L;
    public static final PdfName L2R;
    public static final PdfName LANG;
    public static final PdfName LANGUAGE;
    public static final PdfName LAST;
    public static final PdfName LASTCHAR;
    public static final PdfName LASTPAGE;
    public static final PdfName LAUNCH;
    public static final PdfName LBL;
    public static final PdfName LBODY;
    public static final PdfName LENGTH;
    public static final PdfName LENGTH1;
    public static final PdfName LI;
    public static final PdfName LIMITS;
    public static final PdfName LINE;
    public static final PdfName LINEAR;
    public static final PdfName LINK;
    public static final PdfName LISTMODE;
    public static final PdfName LOCATION;
    public static final PdfName LOCK;
    public static final PdfName LOCKED;
    public static final PdfName LZWDECODE;
    public static final PdfName M;
    public static final PdfName MATERIAL;
    public static final PdfName MATRIX;
    public static final PdfName MAC_EXPERT_ENCODING;
    public static final PdfName MAC_ROMAN_ENCODING;
    public static final PdfName MARKED;
    public static final PdfName MARKINFO;
    public static final PdfName MASK;
    public static final PdfName MAX_LOWER_CASE;
    public static final PdfName MAX_CAMEL_CASE;
    public static final PdfName MAXLEN;
    public static final PdfName MEDIABOX;
    public static final PdfName MCID;
    public static final PdfName MCR;
    public static final PdfName METADATA;
    public static final PdfName MIN_LOWER_CASE;
    public static final PdfName MIN_CAMEL_CASE;
    public static final PdfName MK;
    public static final PdfName MMTYPE1;
    public static final PdfName MODDATE;
    public static final PdfName N;
    public static final PdfName N0;
    public static final PdfName N1;
    public static final PdfName N2;
    public static final PdfName N3;
    public static final PdfName N4;
    public static final PdfName NAME;
    public static final PdfName NAMED;
    public static final PdfName NAMES;
    public static final PdfName NAVIGATION;
    public static final PdfName NAVIGATIONPANE;
    public static final PdfName NEAR;
    public static final PdfName NEEDAPPEARANCES;
    public static final PdfName NEWWINDOW;
    public static final PdfName NEXT;
    public static final PdfName NEXTPAGE;
    public static final PdfName NM;
    public static final PdfName NONE;
    public static final PdfName NONFULLSCREENPAGEMODE;
    public static final PdfName NONSTRUCT;
    public static final PdfName NOTE;
    public static final PdfName NUMCOPIES;
    public static final PdfName NUMS;
    public static final PdfName O;
    public static final PdfName OBJ;
    public static final PdfName OBJR;
    public static final PdfName OBJSTM;
    public static final PdfName OC;
    public static final PdfName OCG;
    public static final PdfName OCGS;
    public static final PdfName OCMD;
    public static final PdfName OCPROPERTIES;
    public static final PdfName Off;
    public static final PdfName OFF;
    public static final PdfName ON;
    public static final PdfName ONECOLUMN;
    public static final PdfName OPEN;
    public static final PdfName OPENACTION;
    public static final PdfName OP;
    public static final PdfName op;
    public static final PdfName OPM;
    public static final PdfName OPT;
    public static final PdfName ORDER;
    public static final PdfName ORDERING;
    public static final PdfName OSCILLATING;
    public static final PdfName OUTLINES;
    public static final PdfName OUTPUTCONDITION;
    public static final PdfName OUTPUTCONDITIONIDENTIFIER;
    public static final PdfName OUTPUTINTENT;
    public static final PdfName OUTPUTINTENTS;
    public static final PdfName P;
    public static final PdfName PAGE;
    public static final PdfName PAGELABELS;
    public static final PdfName PAGELAYOUT;
    public static final PdfName PAGEMODE;
    public static final PdfName PAGES;
    public static final PdfName PAINTTYPE;
    public static final PdfName PANOSE;
    public static final PdfName PARAMS;
    public static final PdfName PARENT;
    public static final PdfName PARENTTREE;
    public static final PdfName PARENTTREENEXTKEY;
    public static final PdfName PART;
    public static final PdfName PASSCONTEXTCLICK;
    public static final PdfName PATTERN;
    public static final PdfName PATTERNTYPE;
    public static final PdfName PC;
    public static final PdfName PDF;
    public static final PdfName PDFDOCENCODING;
    public static final PdfName PERCEPTUAL;
    public static final PdfName PERMS;
    public static final PdfName PG;
    public static final PdfName PI;
    public static final PdfName PICKTRAYBYPDFSIZE;
    public static final PdfName PLAYCOUNT;
    public static final PdfName PO;
    public static final PdfName POPUP;
    public static final PdfName POSITION;
    public static final PdfName PREDICTOR;
    public static final PdfName PREFERRED;
    public static final PdfName PRESENTATION;
    public static final PdfName PRESERVERB;
    public static final PdfName PREV;
    public static final PdfName PREVPAGE;
    public static final PdfName PRINT;
    public static final PdfName PRINTAREA;
    public static final PdfName PRINTCLIP;
    public static final PdfName PRINTPAGERANGE;
    public static final PdfName PRINTSCALING;
    public static final PdfName PRINTSTATE;
    public static final PdfName PRIVATE;
    public static final PdfName PROCSET;
    public static final PdfName PRODUCER;
    public static final PdfName PROPERTIES;
    public static final PdfName PS;
    public static final PdfName PUBSEC;
    public static final PdfName PV;
    public static final PdfName Q;
    public static final PdfName QUADPOINTS;
    public static final PdfName QUOTE;
    public static final PdfName R;
    public static final PdfName R2L;
    public static final PdfName RANGE;
    public static final PdfName RC;
    public static final PdfName RBGROUPS;
    public static final PdfName REASON;
    public static final PdfName RECIPIENTS;
    public static final PdfName RECT;
    public static final PdfName REFERENCE;
    public static final PdfName REGISTRY;
    public static final PdfName REGISTRYNAME;
    public static final PdfName RELATIVECOLORIMETRIC;
    public static final PdfName RENDITION;
    public static final PdfName RESETFORM;
    public static final PdfName RESOURCES;
    public static final PdfName RI;
    public static final PdfName RICHMEDIA;
    public static final PdfName RICHMEDIAACTIVATION;
    public static final PdfName RICHMEDIAANIMATION;
    public static final PdfName RICHMEDIACOMMAND;
    public static final PdfName RICHMEDIACONFIGURATION;
    public static final PdfName RICHMEDIACONTENT;
    public static final PdfName RICHMEDIADEACTIVATION;
    public static final PdfName RICHMEDIAEXECUTE;
    public static final PdfName RICHMEDIAINSTANCE;
    public static final PdfName RICHMEDIAPARAMS;
    public static final PdfName RICHMEDIAPOSITION;
    public static final PdfName RICHMEDIAPRESENTATION;
    public static final PdfName RICHMEDIASETTINGS;
    public static final PdfName RICHMEDIAWINDOW;
    public static final PdfName ROLEMAP;
    public static final PdfName ROOT;
    public static final PdfName ROTATE;
    public static final PdfName ROWS;
    public static final PdfName RUBY;
    public static final PdfName RUNLENGTHDECODE;
    public static final PdfName RV;
    public static final PdfName S;
    public static final PdfName SATURATION;
    public static final PdfName SCHEMA;
    public static final PdfName SCREEN;
    public static final PdfName SCRIPTS;
    public static final PdfName SECT;
    public static final PdfName SEPARATION;
    public static final PdfName SETOCGSTATE;
    public static final PdfName SETTINGS;
    public static final PdfName SHADING;
    public static final PdfName SHADINGTYPE;
    public static final PdfName SHIFT_JIS;
    public static final PdfName SIG;
    public static final PdfName SIGFLAGS;
    public static final PdfName SIGREF;
    public static final PdfName SIMPLEX;
    public static final PdfName SINGLEPAGE;
    public static final PdfName SIZE;
    public static final PdfName SMASK;
    public static final PdfName SORT;
    public static final PdfName SOUND;
    public static final PdfName SPAN;
    public static final PdfName SPEED;
    public static final PdfName SPLIT;
    public static final PdfName SQUARE;
    public static final PdfName SQUIGGLY;
    public static final PdfName ST;
    public static final PdfName STAMP;
    public static final PdfName STANDARD;
    public static final PdfName STATE;
    public static final PdfName STDCF;
    public static final PdfName STEMV;
    public static final PdfName STMF;
    public static final PdfName STRF;
    public static final PdfName STRIKEOUT;
    public static final PdfName STRUCTPARENT;
    public static final PdfName STRUCTPARENTS;
    public static final PdfName STRUCTTREEROOT;
    public static final PdfName STYLE;
    public static final PdfName SUBFILTER;
    public static final PdfName SUBJECT;
    public static final PdfName SUBMITFORM;
    public static final PdfName SUBTYPE;
    public static final PdfName SUPPLEMENT;
    public static final PdfName SV;
    public static final PdfName SW;
    public static final PdfName SYMBOL;
    public static final PdfName T;
    public static final PdfName TA;
    public static final PdfName TABLE;
    public static final PdfName TABS;
    public static final PdfName TBODY;
    public static final PdfName TD;
    public static final PdfName TEXT;
    public static final PdfName TFOOT;
    public static final PdfName TH;
    public static final PdfName THEAD;
    public static final PdfName THUMB;
    public static final PdfName THREADS;
    public static final PdfName TI;
    public static final PdfName TIME;
    public static final PdfName TILINGTYPE;
    public static final PdfName TIMES_ROMAN;
    public static final PdfName TIMES_BOLD;
    public static final PdfName TIMES_ITALIC;
    public static final PdfName TIMES_BOLDITALIC;
    public static final PdfName TITLE;
    public static final PdfName TK;
    public static final PdfName TM;
    public static final PdfName TOC;
    public static final PdfName TOCI;
    public static final PdfName TOGGLE;
    public static final PdfName TOOLBAR;
    public static final PdfName TOUNICODE;
    public static final PdfName TP;
    public static final PdfName TABLEROW;
    public static final PdfName TRANS;
    public static final PdfName TRANSFORMPARAMS;
    public static final PdfName TRANSFORMMETHOD;
    public static final PdfName TRANSPARENCY;
    public static final PdfName TRANSPARENT;
    public static final PdfName TRAPPED;
    public static final PdfName TRIMBOX;
    public static final PdfName TRUETYPE;
    public static final PdfName TU;
    public static final PdfName TWOCOLUMNLEFT;
    public static final PdfName TWOCOLUMNRIGHT;
    public static final PdfName TWOPAGELEFT;
    public static final PdfName TWOPAGERIGHT;
    public static final PdfName TX;
    public static final PdfName TYPE;
    public static final PdfName TYPE0;
    public static final PdfName TYPE1;
    public static final PdfName TYPE3;
    public static final PdfName U;
    public static final PdfName UF;
    public static final PdfName UHC;
    public static final PdfName UNDERLINE;
    public static final PdfName UR;
    public static final PdfName UR3;
    public static final PdfName URI;
    public static final PdfName URL;
    public static final PdfName USAGE;
    public static final PdfName USEATTACHMENTS;
    public static final PdfName USENONE;
    public static final PdfName USEOC;
    public static final PdfName USEOUTLINES;
    public static final PdfName USER;
    public static final PdfName USERPROPERTIES;
    public static final PdfName USERUNIT;
    public static final PdfName USETHUMBS;
    public static final PdfName V;
    public static final PdfName V2;
    public static final PdfName VALIGN;
    public static final PdfName VERISIGN_PPKVS;
    public static final PdfName VERSION;
    public static final PdfName VIDEO;
    public static final PdfName VIEW;
    public static final PdfName VIEWS;
    public static final PdfName VIEWAREA;
    public static final PdfName VIEWCLIP;
    public static final PdfName VIEWERPREFERENCES;
    public static final PdfName VIEWSTATE;
    public static final PdfName VISIBLEPAGES;
    public static final PdfName VOFFSET;
    public static final PdfName W;
    public static final PdfName W2;
    public static final PdfName WARICHU;
    public static final PdfName WC;
    public static final PdfName WIDGET;
    public static final PdfName WIDTH;
    public static final PdfName WIDTHS;
    public static final PdfName WIN;
    public static final PdfName WIN_ANSI_ENCODING;
    public static final PdfName WINDOW;
    public static final PdfName WINDOWED;
    public static final PdfName WIPE;
    public static final PdfName WHITEPOINT;
    public static final PdfName WP;
    public static final PdfName WS;
    public static final PdfName X;
    public static final PdfName XA;
    public static final PdfName XD;
    public static final PdfName XFA;
    public static final PdfName XML;
    public static final PdfName XOBJECT;
    public static final PdfName XSTEP;
    public static final PdfName XREF;
    public static final PdfName XREFSTM;
    public static final PdfName XYZ;
    public static final PdfName YSTEP;
    public static final PdfName ZADB;
    public static final PdfName ZAPFDINGBATS;
    public static final PdfName ZOOM;
    public static Map<String, PdfName> staticNames;
    private int hash;
    
    public PdfName(final String name) {
        this(name, true);
    }
    
    public PdfName(final String name, final boolean lengthCheck) {
        super(4);
        this.hash = 0;
        final int length = name.length();
        if (lengthCheck && length > 127) {
            throw new IllegalArgumentException(MessageLocalization.getComposedMessage("the.name.1.is.too.long.2.characters", name, String.valueOf(length)));
        }
        this.bytes = encodeName(name);
    }
    
    public PdfName(final byte[] bytes) {
        super(4, bytes);
        this.hash = 0;
    }
    
    @Override
    public int compareTo(final Object object) {
        final PdfName name = (PdfName)object;
        final byte[] myBytes = this.bytes;
        final byte[] objBytes = name.bytes;
        for (int len = Math.min(myBytes.length, objBytes.length), i = 0; i < len; ++i) {
            if (myBytes[i] > objBytes[i]) {
                return 1;
            }
            if (myBytes[i] < objBytes[i]) {
                return -1;
            }
        }
        if (myBytes.length < objBytes.length) {
            return -1;
        }
        if (myBytes.length > objBytes.length) {
            return 1;
        }
        return 0;
    }
    
    @Override
    public boolean equals(final Object obj) {
        return this == obj || (obj instanceof PdfName && this.compareTo(obj) == 0);
    }
    
    @Override
    public int hashCode() {
        int h = this.hash;
        if (h == 0) {
            int ptr = 0;
            for (int len = this.bytes.length, i = 0; i < len; ++i) {
                h = 31 * h + (this.bytes[ptr++] & 0xFF);
            }
            this.hash = h;
        }
        return h;
    }
    
    public static byte[] encodeName(final String name) {
        final int length = name.length();
        final ByteBuffer buf = new ByteBuffer(length + 20);
        buf.append('/');
        final char[] chars = name.toCharArray();
        for (int k = 0; k < length; ++k) {
            final char c = (char)(chars[k] & '\u00ff');
            switch (c) {
                case ' ':
                case '#':
                case '%':
                case '(':
                case ')':
                case '/':
                case '<':
                case '>':
                case '[':
                case ']':
                case '{':
                case '}': {
                    buf.append('#');
                    buf.append(Integer.toString(c, 16));
                    break;
                }
                default: {
                    if (c >= ' ' && c <= '~') {
                        buf.append(c);
                        break;
                    }
                    buf.append('#');
                    if (c < '\u0010') {
                        buf.append('0');
                    }
                    buf.append(Integer.toString(c, 16));
                    break;
                }
            }
        }
        return buf.toByteArray();
    }
    
    public static String decodeName(final String name) {
        final StringBuffer buf = new StringBuffer();
        try {
            for (int len = name.length(), k = 1; k < len; ++k) {
                char c = name.charAt(k);
                if (c == '#') {
                    final char c2 = name.charAt(k + 1);
                    final char c3 = name.charAt(k + 2);
                    c = (char)((PRTokeniser.getHex(c2) << 4) + PRTokeniser.getHex(c3));
                    k += 2;
                }
                buf.append(c);
            }
        }
        catch (final IndexOutOfBoundsException ex) {}
        return buf.toString();
    }
    
    static {
        _3D = new PdfName("3D");
        A = new PdfName("A");
        AA = new PdfName("AA");
        ABSOLUTECOLORIMETRIC = new PdfName("AbsoluteColorimetric");
        AC = new PdfName("AC");
        ACROFORM = new PdfName("AcroForm");
        ACTION = new PdfName("Action");
        ACTIVATION = new PdfName("Activation");
        ADBE = new PdfName("ADBE");
        ACTUALTEXT = new PdfName("ActualText");
        ADBE_PKCS7_DETACHED = new PdfName("adbe.pkcs7.detached");
        ADBE_PKCS7_S4 = new PdfName("adbe.pkcs7.s4");
        ADBE_PKCS7_S5 = new PdfName("adbe.pkcs7.s5");
        ADBE_PKCS7_SHA1 = new PdfName("adbe.pkcs7.sha1");
        ADBE_X509_RSA_SHA1 = new PdfName("adbe.x509.rsa_sha1");
        ADOBE_PPKLITE = new PdfName("Adobe.PPKLite");
        ADOBE_PPKMS = new PdfName("Adobe.PPKMS");
        AESV2 = new PdfName("AESV2");
        AIS = new PdfName("AIS");
        ALLPAGES = new PdfName("AllPages");
        ALT = new PdfName("Alt");
        ALTERNATE = new PdfName("Alternate");
        ANIMATION = new PdfName("Animation");
        ANNOT = new PdfName("Annot");
        ANNOTS = new PdfName("Annots");
        ANTIALIAS = new PdfName("AntiAlias");
        AP = new PdfName("AP");
        APPDEFAULT = new PdfName("AppDefault");
        ART = new PdfName("Art");
        ARTBOX = new PdfName("ArtBox");
        ASCENT = new PdfName("Ascent");
        AS = new PdfName("AS");
        ASCII85DECODE = new PdfName("ASCII85Decode");
        ASCIIHEXDECODE = new PdfName("ASCIIHexDecode");
        ASSET = new PdfName("Asset");
        ASSETS = new PdfName("Assets");
        AUTHEVENT = new PdfName("AuthEvent");
        AUTHOR = new PdfName("Author");
        B = new PdfName("B");
        BACKGROUND = new PdfName("Background");
        BASEENCODING = new PdfName("BaseEncoding");
        BASEFONT = new PdfName("BaseFont");
        BASEVERSION = new PdfName("BaseVersion");
        BBOX = new PdfName("BBox");
        BC = new PdfName("BC");
        BG = new PdfName("BG");
        BIBENTRY = new PdfName("BibEntry");
        BIGFIVE = new PdfName("BigFive");
        BINDING = new PdfName("Binding");
        BINDINGMATERIALNAME = new PdfName("BindingMaterialName");
        BITSPERCOMPONENT = new PdfName("BitsPerComponent");
        BITSPERSAMPLE = new PdfName("BitsPerSample");
        BL = new PdfName("Bl");
        BLACKIS1 = new PdfName("BlackIs1");
        BLACKPOINT = new PdfName("BlackPoint");
        BLOCKQUOTE = new PdfName("BlockQuote");
        BLEEDBOX = new PdfName("BleedBox");
        BLINDS = new PdfName("Blinds");
        BM = new PdfName("BM");
        BORDER = new PdfName("Border");
        BOUNDS = new PdfName("Bounds");
        BOX = new PdfName("Box");
        BS = new PdfName("BS");
        BTN = new PdfName("Btn");
        BYTERANGE = new PdfName("ByteRange");
        C = new PdfName("C");
        C0 = new PdfName("C0");
        C1 = new PdfName("C1");
        CA = new PdfName("CA");
        ca = new PdfName("ca");
        CALGRAY = new PdfName("CalGray");
        CALRGB = new PdfName("CalRGB");
        CAPHEIGHT = new PdfName("CapHeight");
        CAPTION = new PdfName("Caption");
        CATALOG = new PdfName("Catalog");
        CATEGORY = new PdfName("Category");
        CCITTFAXDECODE = new PdfName("CCITTFaxDecode");
        CENTER = new PdfName("Center");
        CENTERWINDOW = new PdfName("CenterWindow");
        CERT = new PdfName("Cert");
        CF = new PdfName("CF");
        CFM = new PdfName("CFM");
        CH = new PdfName("Ch");
        CHARPROCS = new PdfName("CharProcs");
        CHECKSUM = new PdfName("CheckSum");
        CI = new PdfName("CI");
        CIDFONTTYPE0 = new PdfName("CIDFontType0");
        CIDFONTTYPE2 = new PdfName("CIDFontType2");
        CIDSET = new PdfName("CIDSet");
        CIDSYSTEMINFO = new PdfName("CIDSystemInfo");
        CIDTOGIDMAP = new PdfName("CIDToGIDMap");
        CIRCLE = new PdfName("Circle");
        CMD = new PdfName("CMD");
        CO = new PdfName("CO");
        CODE = new PdfName("Code");
        COLORS = new PdfName("Colors");
        COLORSPACE = new PdfName("ColorSpace");
        COLLECTION = new PdfName("Collection");
        COLLECTIONFIELD = new PdfName("CollectionField");
        COLLECTIONITEM = new PdfName("CollectionItem");
        COLLECTIONSCHEMA = new PdfName("CollectionSchema");
        COLLECTIONSORT = new PdfName("CollectionSort");
        COLLECTIONSUBITEM = new PdfName("CollectionSubitem");
        COLUMNS = new PdfName("Columns");
        CONDITION = new PdfName("Condition");
        CONFIGURATION = new PdfName("Configuration");
        CONFIGURATIONS = new PdfName("Configurations");
        CONTACTINFO = new PdfName("ContactInfo");
        CONTENT = new PdfName("Content");
        CONTENTS = new PdfName("Contents");
        COORDS = new PdfName("Coords");
        COUNT = new PdfName("Count");
        COURIER = new PdfName("Courier");
        COURIER_BOLD = new PdfName("Courier-Bold");
        COURIER_OBLIQUE = new PdfName("Courier-Oblique");
        COURIER_BOLDOBLIQUE = new PdfName("Courier-BoldOblique");
        CREATIONDATE = new PdfName("CreationDate");
        CREATOR = new PdfName("Creator");
        CREATORINFO = new PdfName("CreatorInfo");
        CROPBOX = new PdfName("CropBox");
        CRYPT = new PdfName("Crypt");
        CS = new PdfName("CS");
        CUEPOINT = new PdfName("CuePoint");
        CUEPOINTS = new PdfName("CuePoints");
        D = new PdfName("D");
        DA = new PdfName("DA");
        DATA = new PdfName("Data");
        DC = new PdfName("DC");
        DCTDECODE = new PdfName("DCTDecode");
        DEACTIVATION = new PdfName("Deactivation");
        DECODE = new PdfName("Decode");
        DECODEPARMS = new PdfName("DecodeParms");
        DEFAULT = new PdfName("Default");
        DEFAULTCRYPTFILTER = new PdfName("DefaultCryptFilter");
        DEFAULTCMYK = new PdfName("DefaultCMYK");
        DEFAULTGRAY = new PdfName("DefaultGray");
        DEFAULTRGB = new PdfName("DefaultRGB");
        DESC = new PdfName("Desc");
        DESCENDANTFONTS = new PdfName("DescendantFonts");
        DESCENT = new PdfName("Descent");
        DEST = new PdfName("Dest");
        DESTOUTPUTPROFILE = new PdfName("DestOutputProfile");
        DESTS = new PdfName("Dests");
        DEVICEGRAY = new PdfName("DeviceGray");
        DEVICERGB = new PdfName("DeviceRGB");
        DEVICECMYK = new PdfName("DeviceCMYK");
        DI = new PdfName("Di");
        DIFFERENCES = new PdfName("Differences");
        DISSOLVE = new PdfName("Dissolve");
        DIRECTION = new PdfName("Direction");
        DISPLAYDOCTITLE = new PdfName("DisplayDocTitle");
        DIV = new PdfName("Div");
        DL = new PdfName("DL");
        DM = new PdfName("Dm");
        DOCMDP = new PdfName("DocMDP");
        DOCOPEN = new PdfName("DocOpen");
        DOCUMENT = new PdfName("Document");
        DOMAIN = new PdfName("Domain");
        DP = new PdfName("DP");
        DR = new PdfName("DR");
        DS = new PdfName("DS");
        DUR = new PdfName("Dur");
        DUPLEX = new PdfName("Duplex");
        DUPLEXFLIPSHORTEDGE = new PdfName("DuplexFlipShortEdge");
        DUPLEXFLIPLONGEDGE = new PdfName("DuplexFlipLongEdge");
        DV = new PdfName("DV");
        DW = new PdfName("DW");
        E = new PdfName("E");
        EARLYCHANGE = new PdfName("EarlyChange");
        EF = new PdfName("EF");
        EFF = new PdfName("EFF");
        EFOPEN = new PdfName("EFOpen");
        EMBEDDED = new PdfName("Embedded");
        EMBEDDEDFILE = new PdfName("EmbeddedFile");
        EMBEDDEDFILES = new PdfName("EmbeddedFiles");
        ENCODE = new PdfName("Encode");
        ENCODEDBYTEALIGN = new PdfName("EncodedByteAlign");
        ENCODING = new PdfName("Encoding");
        ENCRYPT = new PdfName("Encrypt");
        ENCRYPTMETADATA = new PdfName("EncryptMetadata");
        ENDOFBLOCK = new PdfName("EndOfBlock");
        ENDOFLINE = new PdfName("EndOfLine");
        EXTEND = new PdfName("Extend");
        EXTENSIONS = new PdfName("Extensions");
        EXTENSIONLEVEL = new PdfName("ExtensionLevel");
        EXTGSTATE = new PdfName("ExtGState");
        EXPORT = new PdfName("Export");
        EXPORTSTATE = new PdfName("ExportState");
        EVENT = new PdfName("Event");
        F = new PdfName("F");
        FAR = new PdfName("Far");
        FB = new PdfName("FB");
        FDECODEPARMS = new PdfName("FDecodeParms");
        FDF = new PdfName("FDF");
        FF = new PdfName("Ff");
        FFILTER = new PdfName("FFilter");
        FIELDS = new PdfName("Fields");
        FIGURE = new PdfName("Figure");
        FILEATTACHMENT = new PdfName("FileAttachment");
        FILESPEC = new PdfName("Filespec");
        FILTER = new PdfName("Filter");
        FIRST = new PdfName("First");
        FIRSTCHAR = new PdfName("FirstChar");
        FIRSTPAGE = new PdfName("FirstPage");
        FIT = new PdfName("Fit");
        FITH = new PdfName("FitH");
        FITV = new PdfName("FitV");
        FITR = new PdfName("FitR");
        FITB = new PdfName("FitB");
        FITBH = new PdfName("FitBH");
        FITBV = new PdfName("FitBV");
        FITWINDOW = new PdfName("FitWindow");
        FLAGS = new PdfName("Flags");
        FLASH = new PdfName("Flash");
        FLASHVARS = new PdfName("FlashVars");
        FLATEDECODE = new PdfName("FlateDecode");
        FO = new PdfName("Fo");
        FONT = new PdfName("Font");
        FONTBBOX = new PdfName("FontBBox");
        FONTDESCRIPTOR = new PdfName("FontDescriptor");
        FONTFILE = new PdfName("FontFile");
        FONTFILE2 = new PdfName("FontFile2");
        FONTFILE3 = new PdfName("FontFile3");
        FONTMATRIX = new PdfName("FontMatrix");
        FONTNAME = new PdfName("FontName");
        FOREGROUND = new PdfName("Foreground");
        FORM = new PdfName("Form");
        FORMTYPE = new PdfName("FormType");
        FORMULA = new PdfName("Formula");
        FREETEXT = new PdfName("FreeText");
        FRM = new PdfName("FRM");
        FS = new PdfName("FS");
        FT = new PdfName("FT");
        FULLSCREEN = new PdfName("FullScreen");
        FUNCTION = new PdfName("Function");
        FUNCTIONS = new PdfName("Functions");
        FUNCTIONTYPE = new PdfName("FunctionType");
        GAMMA = new PdfName("Gamma");
        GBK = new PdfName("GBK");
        GLITTER = new PdfName("Glitter");
        GOTO = new PdfName("GoTo");
        GOTOE = new PdfName("GoToE");
        GOTOR = new PdfName("GoToR");
        GROUP = new PdfName("Group");
        GTS_PDFA1 = new PdfName("GTS_PDFA1");
        GTS_PDFX = new PdfName("GTS_PDFX");
        GTS_PDFXVERSION = new PdfName("GTS_PDFXVersion");
        H = new PdfName("H");
        H1 = new PdfName("H1");
        H2 = new PdfName("H2");
        H3 = new PdfName("H3");
        H4 = new PdfName("H4");
        H5 = new PdfName("H5");
        H6 = new PdfName("H6");
        HALIGN = new PdfName("HAlign");
        HEIGHT = new PdfName("Height");
        HELV = new PdfName("Helv");
        HELVETICA = new PdfName("Helvetica");
        HELVETICA_BOLD = new PdfName("Helvetica-Bold");
        HELVETICA_OBLIQUE = new PdfName("Helvetica-Oblique");
        HELVETICA_BOLDOBLIQUE = new PdfName("Helvetica-BoldOblique");
        HID = new PdfName("Hid");
        HIDE = new PdfName("Hide");
        HIDEMENUBAR = new PdfName("HideMenubar");
        HIDETOOLBAR = new PdfName("HideToolbar");
        HIDEWINDOWUI = new PdfName("HideWindowUI");
        HIGHLIGHT = new PdfName("Highlight");
        HOFFSET = new PdfName("HOffset");
        I = new PdfName("I");
        ICCBASED = new PdfName("ICCBased");
        ID = new PdfName("ID");
        IDENTITY = new PdfName("Identity");
        IF = new PdfName("IF");
        IMAGE = new PdfName("Image");
        IMAGEB = new PdfName("ImageB");
        IMAGEC = new PdfName("ImageC");
        IMAGEI = new PdfName("ImageI");
        IMAGEMASK = new PdfName("ImageMask");
        INDEX = new PdfName("Index");
        INDEXED = new PdfName("Indexed");
        INFO = new PdfName("Info");
        INK = new PdfName("Ink");
        INKLIST = new PdfName("InkList");
        INSTANCES = new PdfName("Instances");
        IMPORTDATA = new PdfName("ImportData");
        INTENT = new PdfName("Intent");
        INTERPOLATE = new PdfName("Interpolate");
        ISMAP = new PdfName("IsMap");
        IRT = new PdfName("IRT");
        ITALICANGLE = new PdfName("ItalicAngle");
        ITXT = new PdfName("ITXT");
        IX = new PdfName("IX");
        JAVASCRIPT = new PdfName("JavaScript");
        JBIG2DECODE = new PdfName("JBIG2Decode");
        JBIG2GLOBALS = new PdfName("JBIG2Globals");
        JPXDECODE = new PdfName("JPXDecode");
        JS = new PdfName("JS");
        K = new PdfName("K");
        KEYWORDS = new PdfName("Keywords");
        KIDS = new PdfName("Kids");
        L = new PdfName("L");
        L2R = new PdfName("L2R");
        LANG = new PdfName("Lang");
        LANGUAGE = new PdfName("Language");
        LAST = new PdfName("Last");
        LASTCHAR = new PdfName("LastChar");
        LASTPAGE = new PdfName("LastPage");
        LAUNCH = new PdfName("Launch");
        LBL = new PdfName("Lbl");
        LBODY = new PdfName("LBody");
        LENGTH = new PdfName("Length");
        LENGTH1 = new PdfName("Length1");
        LI = new PdfName("LI");
        LIMITS = new PdfName("Limits");
        LINE = new PdfName("Line");
        LINEAR = new PdfName("Linear");
        LINK = new PdfName("Link");
        LISTMODE = new PdfName("ListMode");
        LOCATION = new PdfName("Location");
        LOCK = new PdfName("Lock");
        LOCKED = new PdfName("Locked");
        LZWDECODE = new PdfName("LZWDecode");
        M = new PdfName("M");
        MATERIAL = new PdfName("Material");
        MATRIX = new PdfName("Matrix");
        MAC_EXPERT_ENCODING = new PdfName("MacExpertEncoding");
        MAC_ROMAN_ENCODING = new PdfName("MacRomanEncoding");
        MARKED = new PdfName("Marked");
        MARKINFO = new PdfName("MarkInfo");
        MASK = new PdfName("Mask");
        MAX_LOWER_CASE = new PdfName("max");
        MAX_CAMEL_CASE = new PdfName("Max");
        MAXLEN = new PdfName("MaxLen");
        MEDIABOX = new PdfName("MediaBox");
        MCID = new PdfName("MCID");
        MCR = new PdfName("MCR");
        METADATA = new PdfName("Metadata");
        MIN_LOWER_CASE = new PdfName("min");
        MIN_CAMEL_CASE = new PdfName("Min");
        MK = new PdfName("MK");
        MMTYPE1 = new PdfName("MMType1");
        MODDATE = new PdfName("ModDate");
        N = new PdfName("N");
        N0 = new PdfName("n0");
        N1 = new PdfName("n1");
        N2 = new PdfName("n2");
        N3 = new PdfName("n3");
        N4 = new PdfName("n4");
        NAME = new PdfName("Name");
        NAMED = new PdfName("Named");
        NAMES = new PdfName("Names");
        NAVIGATION = new PdfName("Navigation");
        NAVIGATIONPANE = new PdfName("NavigationPane");
        NEAR = new PdfName("Near");
        NEEDAPPEARANCES = new PdfName("NeedAppearances");
        NEWWINDOW = new PdfName("NewWindow");
        NEXT = new PdfName("Next");
        NEXTPAGE = new PdfName("NextPage");
        NM = new PdfName("NM");
        NONE = new PdfName("None");
        NONFULLSCREENPAGEMODE = new PdfName("NonFullScreenPageMode");
        NONSTRUCT = new PdfName("NonStruct");
        NOTE = new PdfName("Note");
        NUMCOPIES = new PdfName("NumCopies");
        NUMS = new PdfName("Nums");
        O = new PdfName("O");
        OBJ = new PdfName("Obj");
        OBJR = new PdfName("OBJR");
        OBJSTM = new PdfName("ObjStm");
        OC = new PdfName("OC");
        OCG = new PdfName("OCG");
        OCGS = new PdfName("OCGs");
        OCMD = new PdfName("OCMD");
        OCPROPERTIES = new PdfName("OCProperties");
        Off = new PdfName("Off");
        OFF = new PdfName("OFF");
        ON = new PdfName("ON");
        ONECOLUMN = new PdfName("OneColumn");
        OPEN = new PdfName("Open");
        OPENACTION = new PdfName("OpenAction");
        OP = new PdfName("OP");
        op = new PdfName("op");
        OPM = new PdfName("OPM");
        OPT = new PdfName("Opt");
        ORDER = new PdfName("Order");
        ORDERING = new PdfName("Ordering");
        OSCILLATING = new PdfName("Oscillating");
        OUTLINES = new PdfName("Outlines");
        OUTPUTCONDITION = new PdfName("OutputCondition");
        OUTPUTCONDITIONIDENTIFIER = new PdfName("OutputConditionIdentifier");
        OUTPUTINTENT = new PdfName("OutputIntent");
        OUTPUTINTENTS = new PdfName("OutputIntents");
        P = new PdfName("P");
        PAGE = new PdfName("Page");
        PAGELABELS = new PdfName("PageLabels");
        PAGELAYOUT = new PdfName("PageLayout");
        PAGEMODE = new PdfName("PageMode");
        PAGES = new PdfName("Pages");
        PAINTTYPE = new PdfName("PaintType");
        PANOSE = new PdfName("Panose");
        PARAMS = new PdfName("Params");
        PARENT = new PdfName("Parent");
        PARENTTREE = new PdfName("ParentTree");
        PARENTTREENEXTKEY = new PdfName("ParentTreeNextKey");
        PART = new PdfName("Part");
        PASSCONTEXTCLICK = new PdfName("PassContextClick");
        PATTERN = new PdfName("Pattern");
        PATTERNTYPE = new PdfName("PatternType");
        PC = new PdfName("PC");
        PDF = new PdfName("PDF");
        PDFDOCENCODING = new PdfName("PDFDocEncoding");
        PERCEPTUAL = new PdfName("Perceptual");
        PERMS = new PdfName("Perms");
        PG = new PdfName("Pg");
        PI = new PdfName("PI");
        PICKTRAYBYPDFSIZE = new PdfName("PickTrayByPDFSize");
        PLAYCOUNT = new PdfName("PlayCount");
        PO = new PdfName("PO");
        POPUP = new PdfName("Popup");
        POSITION = new PdfName("Position");
        PREDICTOR = new PdfName("Predictor");
        PREFERRED = new PdfName("Preferred");
        PRESENTATION = new PdfName("Presentation");
        PRESERVERB = new PdfName("PreserveRB");
        PREV = new PdfName("Prev");
        PREVPAGE = new PdfName("PrevPage");
        PRINT = new PdfName("Print");
        PRINTAREA = new PdfName("PrintArea");
        PRINTCLIP = new PdfName("PrintClip");
        PRINTPAGERANGE = new PdfName("PrintPageRange");
        PRINTSCALING = new PdfName("PrintScaling");
        PRINTSTATE = new PdfName("PrintState");
        PRIVATE = new PdfName("Private");
        PROCSET = new PdfName("ProcSet");
        PRODUCER = new PdfName("Producer");
        PROPERTIES = new PdfName("Properties");
        PS = new PdfName("PS");
        PUBSEC = new PdfName("Adobe.PubSec");
        PV = new PdfName("PV");
        Q = new PdfName("Q");
        QUADPOINTS = new PdfName("QuadPoints");
        QUOTE = new PdfName("Quote");
        R = new PdfName("R");
        R2L = new PdfName("R2L");
        RANGE = new PdfName("Range");
        RC = new PdfName("RC");
        RBGROUPS = new PdfName("RBGroups");
        REASON = new PdfName("Reason");
        RECIPIENTS = new PdfName("Recipients");
        RECT = new PdfName("Rect");
        REFERENCE = new PdfName("Reference");
        REGISTRY = new PdfName("Registry");
        REGISTRYNAME = new PdfName("RegistryName");
        RELATIVECOLORIMETRIC = new PdfName("RelativeColorimetric");
        RENDITION = new PdfName("Rendition");
        RESETFORM = new PdfName("ResetForm");
        RESOURCES = new PdfName("Resources");
        RI = new PdfName("RI");
        RICHMEDIA = new PdfName("RichMedia");
        RICHMEDIAACTIVATION = new PdfName("RichMediaActivation");
        RICHMEDIAANIMATION = new PdfName("RichMediaAnimation");
        RICHMEDIACOMMAND = new PdfName("RichMediaCommand");
        RICHMEDIACONFIGURATION = new PdfName("RichMediaConfiguration");
        RICHMEDIACONTENT = new PdfName("RichMediaContent");
        RICHMEDIADEACTIVATION = new PdfName("RichMediaDeactivation");
        RICHMEDIAEXECUTE = new PdfName("RichMediaExecute");
        RICHMEDIAINSTANCE = new PdfName("RichMediaInstance");
        RICHMEDIAPARAMS = new PdfName("RichMediaParams");
        RICHMEDIAPOSITION = new PdfName("RichMediaPosition");
        RICHMEDIAPRESENTATION = new PdfName("RichMediaPresentation");
        RICHMEDIASETTINGS = new PdfName("RichMediaSettings");
        RICHMEDIAWINDOW = new PdfName("RichMediaWindow");
        ROLEMAP = new PdfName("RoleMap");
        ROOT = new PdfName("Root");
        ROTATE = new PdfName("Rotate");
        ROWS = new PdfName("Rows");
        RUBY = new PdfName("Ruby");
        RUNLENGTHDECODE = new PdfName("RunLengthDecode");
        RV = new PdfName("RV");
        S = new PdfName("S");
        SATURATION = new PdfName("Saturation");
        SCHEMA = new PdfName("Schema");
        SCREEN = new PdfName("Screen");
        SCRIPTS = new PdfName("Scripts");
        SECT = new PdfName("Sect");
        SEPARATION = new PdfName("Separation");
        SETOCGSTATE = new PdfName("SetOCGState");
        SETTINGS = new PdfName("Settings");
        SHADING = new PdfName("Shading");
        SHADINGTYPE = new PdfName("ShadingType");
        SHIFT_JIS = new PdfName("Shift-JIS");
        SIG = new PdfName("Sig");
        SIGFLAGS = new PdfName("SigFlags");
        SIGREF = new PdfName("SigRef");
        SIMPLEX = new PdfName("Simplex");
        SINGLEPAGE = new PdfName("SinglePage");
        SIZE = new PdfName("Size");
        SMASK = new PdfName("SMask");
        SORT = new PdfName("Sort");
        SOUND = new PdfName("Sound");
        SPAN = new PdfName("Span");
        SPEED = new PdfName("Speed");
        SPLIT = new PdfName("Split");
        SQUARE = new PdfName("Square");
        SQUIGGLY = new PdfName("Squiggly");
        ST = new PdfName("St");
        STAMP = new PdfName("Stamp");
        STANDARD = new PdfName("Standard");
        STATE = new PdfName("State");
        STDCF = new PdfName("StdCF");
        STEMV = new PdfName("StemV");
        STMF = new PdfName("StmF");
        STRF = new PdfName("StrF");
        STRIKEOUT = new PdfName("StrikeOut");
        STRUCTPARENT = new PdfName("StructParent");
        STRUCTPARENTS = new PdfName("StructParents");
        STRUCTTREEROOT = new PdfName("StructTreeRoot");
        STYLE = new PdfName("Style");
        SUBFILTER = new PdfName("SubFilter");
        SUBJECT = new PdfName("Subject");
        SUBMITFORM = new PdfName("SubmitForm");
        SUBTYPE = new PdfName("Subtype");
        SUPPLEMENT = new PdfName("Supplement");
        SV = new PdfName("SV");
        SW = new PdfName("SW");
        SYMBOL = new PdfName("Symbol");
        T = new PdfName("T");
        TA = new PdfName("TA");
        TABLE = new PdfName("Table");
        TABS = new PdfName("Tabs");
        TBODY = new PdfName("TBody");
        TD = new PdfName("TD");
        TEXT = new PdfName("Text");
        TFOOT = new PdfName("TFoot");
        TH = new PdfName("TH");
        THEAD = new PdfName("THead");
        THUMB = new PdfName("Thumb");
        THREADS = new PdfName("Threads");
        TI = new PdfName("TI");
        TIME = new PdfName("Time");
        TILINGTYPE = new PdfName("TilingType");
        TIMES_ROMAN = new PdfName("Times-Roman");
        TIMES_BOLD = new PdfName("Times-Bold");
        TIMES_ITALIC = new PdfName("Times-Italic");
        TIMES_BOLDITALIC = new PdfName("Times-BoldItalic");
        TITLE = new PdfName("Title");
        TK = new PdfName("TK");
        TM = new PdfName("TM");
        TOC = new PdfName("TOC");
        TOCI = new PdfName("TOCI");
        TOGGLE = new PdfName("Toggle");
        TOOLBAR = new PdfName("Toolbar");
        TOUNICODE = new PdfName("ToUnicode");
        TP = new PdfName("TP");
        TABLEROW = new PdfName("TR");
        TRANS = new PdfName("Trans");
        TRANSFORMPARAMS = new PdfName("TransformParams");
        TRANSFORMMETHOD = new PdfName("TransformMethod");
        TRANSPARENCY = new PdfName("Transparency");
        TRANSPARENT = new PdfName("Transparent");
        TRAPPED = new PdfName("Trapped");
        TRIMBOX = new PdfName("TrimBox");
        TRUETYPE = new PdfName("TrueType");
        TU = new PdfName("TU");
        TWOCOLUMNLEFT = new PdfName("TwoColumnLeft");
        TWOCOLUMNRIGHT = new PdfName("TwoColumnRight");
        TWOPAGELEFT = new PdfName("TwoPageLeft");
        TWOPAGERIGHT = new PdfName("TwoPageRight");
        TX = new PdfName("Tx");
        TYPE = new PdfName("Type");
        TYPE0 = new PdfName("Type0");
        TYPE1 = new PdfName("Type1");
        TYPE3 = new PdfName("Type3");
        U = new PdfName("U");
        UF = new PdfName("UF");
        UHC = new PdfName("UHC");
        UNDERLINE = new PdfName("Underline");
        UR = new PdfName("UR");
        UR3 = new PdfName("UR3");
        URI = new PdfName("URI");
        URL = new PdfName("URL");
        USAGE = new PdfName("Usage");
        USEATTACHMENTS = new PdfName("UseAttachments");
        USENONE = new PdfName("UseNone");
        USEOC = new PdfName("UseOC");
        USEOUTLINES = new PdfName("UseOutlines");
        USER = new PdfName("User");
        USERPROPERTIES = new PdfName("UserProperties");
        USERUNIT = new PdfName("UserUnit");
        USETHUMBS = new PdfName("UseThumbs");
        V = new PdfName("V");
        V2 = new PdfName("V2");
        VALIGN = new PdfName("VAlign");
        VERISIGN_PPKVS = new PdfName("VeriSign.PPKVS");
        VERSION = new PdfName("Version");
        VIDEO = new PdfName("Video");
        VIEW = new PdfName("View");
        VIEWS = new PdfName("Views");
        VIEWAREA = new PdfName("ViewArea");
        VIEWCLIP = new PdfName("ViewClip");
        VIEWERPREFERENCES = new PdfName("ViewerPreferences");
        VIEWSTATE = new PdfName("ViewState");
        VISIBLEPAGES = new PdfName("VisiblePages");
        VOFFSET = new PdfName("VOffset");
        W = new PdfName("W");
        W2 = new PdfName("W2");
        WARICHU = new PdfName("Warichu");
        WC = new PdfName("WC");
        WIDGET = new PdfName("Widget");
        WIDTH = new PdfName("Width");
        WIDTHS = new PdfName("Widths");
        WIN = new PdfName("Win");
        WIN_ANSI_ENCODING = new PdfName("WinAnsiEncoding");
        WINDOW = new PdfName("Window");
        WINDOWED = new PdfName("Windowed");
        WIPE = new PdfName("Wipe");
        WHITEPOINT = new PdfName("WhitePoint");
        WP = new PdfName("WP");
        WS = new PdfName("WS");
        X = new PdfName("X");
        XA = new PdfName("XA");
        XD = new PdfName("XD");
        XFA = new PdfName("XFA");
        XML = new PdfName("XML");
        XOBJECT = new PdfName("XObject");
        XSTEP = new PdfName("XStep");
        XREF = new PdfName("XRef");
        XREFSTM = new PdfName("XRefStm");
        XYZ = new PdfName("XYZ");
        YSTEP = new PdfName("YStep");
        ZADB = new PdfName("ZaDb");
        ZAPFDINGBATS = new PdfName("ZapfDingbats");
        ZOOM = new PdfName("Zoom");
        final Field[] fields = PdfName.class.getDeclaredFields();
        PdfName.staticNames = new HashMap<String, PdfName>(fields.length);
        final int flags = 25;
        try {
            for (int fldIdx = 0; fldIdx < fields.length; ++fldIdx) {
                final Field curFld = fields[fldIdx];
                if ((curFld.getModifiers() & 0x19) == 0x19 && curFld.getType().equals(PdfName.class)) {
                    final PdfName name = (PdfName)curFld.get(null);
                    PdfName.staticNames.put(decodeName(name.toString()), name);
                }
            }
        }
        catch (final Exception e) {
            e.printStackTrace();
        }
    }
}
