package com.adventnet.swissqlapi.config;

public class SwisSQLOptions
{
    public static boolean PLSQL;
    public static boolean forStoredProcedureMigration;
    public static boolean UDBSQL;
    public static boolean fromSybase;
    public static boolean fromSQLServer;
    public static boolean fromAccess;
    public static boolean fromFiles;
    public static boolean addRowidColumnForAllDB2Tables;
    public static boolean intToNumberConversionForPLSQL;
    public static boolean caseWithEqualForDecode;
    public static boolean convertTruncWithVariableToFloor;
    public static String dateFormatForConvertFunction;
    public static boolean convertNextDayWithAllCase;
    public static boolean isReturningClauseConversionNeeded;
    public static boolean handleLOCK_HINTSforOracle;
    public static boolean SOURCE_DB_IS_DB2;
    public static boolean SOURCE_DB_IS_ORACLE;
    public static boolean TRUNCATE_ORACLE_SCHEMA_INFORMATION;
    public static boolean sybaseNotNullConstraint;
    public static boolean TSQLQuotedIdentifier;
    public static boolean doNotModifyVariableName;
    public static boolean generateTriggerForIdentity;
    public static boolean setPostgreSQLSelectColumnToLowerCase;
    public static boolean setObjectNamesToUpperCase;
    public static boolean setObjectNamesToLowerCase;
    public static boolean renameTableNameAsSchemName_TableName;
    public static boolean RemoveOrderByColumnWhenColumnNotInSelectList;
    public static boolean splitMulitpleColumnsOfINClause;
    public static boolean convertOracleForUpdateToSybaseLockTable;
    public static boolean EnableDeltekSpecificConversions;
    public static boolean changeDatatype_For_Deltek;
    public static boolean sqlServerTriggers;
    public static boolean SetSybaseDoubleQuotedLiteralsToSingleQuotes;
    public static boolean convertNullStringToOracleISNULL;
    public static boolean removeExtraDotForDatabaseName;
    public static boolean convertHierarchicalClausetoSQL2005;
    public static boolean removeOracleSchemaQualifier;
    public static boolean removeDBSchemaQualifier;
    public static boolean removeFormatForOracleToCharFunction;
    public static boolean isDataupia;
    public static boolean passFunctionsWithOutThrowingConvertException;
    public static boolean convert_Oracle_TO_DATE_To_Timestamp;
    public static boolean convertTemporaryTableToPermanentTable;
    public static boolean castCharDatatypeAsCaseSpecific;
    public static boolean convertOracleTruncToCastAsDate;
    public static final int TD_TEMPORARY_TABLE = 0;
    public static final int TD_VOLATILE_TABLE = 1;
    public static final int TD_PERMANENT_TABLE = 2;
    public static int oracleTempTableToTDConversionFormat;
    public static boolean setDoubleQuotesToAnsiSqlTableObjects;
    public static boolean isDualTableNameRequired;
    public static boolean fullyQualifiedWithDatabaseName;
    public static boolean retainQuotedIdentifierForOracle;
    public static boolean useANSIFormatForSubString;
    
    static {
        SwisSQLOptions.PLSQL = false;
        SwisSQLOptions.forStoredProcedureMigration = false;
        SwisSQLOptions.UDBSQL = false;
        SwisSQLOptions.fromSybase = false;
        SwisSQLOptions.fromSQLServer = false;
        SwisSQLOptions.fromAccess = false;
        SwisSQLOptions.fromFiles = false;
        SwisSQLOptions.addRowidColumnForAllDB2Tables = false;
        SwisSQLOptions.intToNumberConversionForPLSQL = false;
        SwisSQLOptions.caseWithEqualForDecode = false;
        SwisSQLOptions.convertTruncWithVariableToFloor = true;
        SwisSQLOptions.dateFormatForConvertFunction = "112";
        SwisSQLOptions.convertNextDayWithAllCase = true;
        SwisSQLOptions.isReturningClauseConversionNeeded = true;
        SwisSQLOptions.handleLOCK_HINTSforOracle = false;
        SwisSQLOptions.SOURCE_DB_IS_DB2 = false;
        SwisSQLOptions.SOURCE_DB_IS_ORACLE = false;
        SwisSQLOptions.TRUNCATE_ORACLE_SCHEMA_INFORMATION = false;
        SwisSQLOptions.sybaseNotNullConstraint = true;
        SwisSQLOptions.TSQLQuotedIdentifier = true;
        SwisSQLOptions.doNotModifyVariableName = false;
        SwisSQLOptions.generateTriggerForIdentity = false;
        SwisSQLOptions.setPostgreSQLSelectColumnToLowerCase = false;
        SwisSQLOptions.setObjectNamesToUpperCase = false;
        SwisSQLOptions.setObjectNamesToLowerCase = true;
        SwisSQLOptions.renameTableNameAsSchemName_TableName = false;
        SwisSQLOptions.RemoveOrderByColumnWhenColumnNotInSelectList = false;
        SwisSQLOptions.splitMulitpleColumnsOfINClause = true;
        SwisSQLOptions.convertOracleForUpdateToSybaseLockTable = true;
        SwisSQLOptions.EnableDeltekSpecificConversions = false;
        SwisSQLOptions.changeDatatype_For_Deltek = false;
        SwisSQLOptions.sqlServerTriggers = false;
        SwisSQLOptions.SetSybaseDoubleQuotedLiteralsToSingleQuotes = false;
        SwisSQLOptions.convertNullStringToOracleISNULL = false;
        SwisSQLOptions.removeExtraDotForDatabaseName = false;
        SwisSQLOptions.convertHierarchicalClausetoSQL2005 = false;
        SwisSQLOptions.removeOracleSchemaQualifier = false;
        SwisSQLOptions.removeDBSchemaQualifier = false;
        SwisSQLOptions.removeFormatForOracleToCharFunction = false;
        SwisSQLOptions.isDataupia = false;
        SwisSQLOptions.passFunctionsWithOutThrowingConvertException = false;
        SwisSQLOptions.convert_Oracle_TO_DATE_To_Timestamp = false;
        SwisSQLOptions.convertTemporaryTableToPermanentTable = false;
        SwisSQLOptions.castCharDatatypeAsCaseSpecific = false;
        SwisSQLOptions.convertOracleTruncToCastAsDate = false;
        SwisSQLOptions.oracleTempTableToTDConversionFormat = 1;
        SwisSQLOptions.setDoubleQuotesToAnsiSqlTableObjects = false;
        SwisSQLOptions.isDualTableNameRequired = true;
        SwisSQLOptions.fullyQualifiedWithDatabaseName = false;
        SwisSQLOptions.retainQuotedIdentifierForOracle = false;
        SwisSQLOptions.useANSIFormatForSubString = true;
    }
}
