package com.me.mdm.server.doc;

import com.me.devicemanagement.framework.server.util.UrlReplacementUtil;
import java.io.File;
import com.me.mdm.core.MDMConstants;
import com.me.mdm.server.deploy.MDMMetaDataUtil;

public class DocMgmtConstants
{
    public static final int DELETE_REPO = 0;
    public static final int SERVER_REPO = 1;
    public static final int IBOOKS_REPO = 2;
    public static final int OS_UPDATE_REPO = 3;
    public static final String TASK = "Task";
    public static final String TIME = "TIME";
    public static final String STATUS = "STATUS";
    public static final String FILE_FIELD = "file";
    public static final String ADD_DOC = "ADD_DOC";
    public static final String LEARN_MORE = "LEARN_MORE";
    public static final String STATUS_MSG = "STATUS_MSG";
    public static final String MODIFY_DOC = "MODIFY_DOC";
    public static final String PAGE_CONTENT = "PAGE_CONTENT";
    public static final String DOWNLOAD_DOC = "DOWNLOAD_DOC";
    public static final String DOC_REPO_PATH = "docrepository";
    public static final String DOC_ADDED_MSG = "DOC_ADDED_MSG";
    public static final String SYNC_DOCUMENTS = "SyncDocuments";
    public static final String COMMON_ALLOWED_EXTENTION = ".cms";
    public static final String AVAILABLE_TAGS = "AVAILABLE_TAGS";
    public static final String HARD_REMOVE_DOC = "HARD_REMOVE_DOC";
    public static final String DOC_MGMT_DETAILS = "DOC_MGMT_DETAILS";
    public static final String NO_DOCUMENTS_PAGE = "NO_DOCUMENTS_PAGE";
    public static final String VALIDATION_STATUS = "VALIDATION_STATUS";
    public static final String SHARED_USER_COUNT = "SHARED_USER_COUNT";
    public static final String SHARED_GROUP_COUNT = "SHARED_GROUP_COUNT";
    public static final String SHARED_DEVICE_COUNT = "SHARED_DEVICE_COUNT";
    public static final String DOCUMENTS_MANAGED_PAGE = "DOCUMENTS_MANAGED_PAGE";
    public static final String DOCUMENT_FILE_PATH = "DOCUMENT_FILE_PATH";
    public static final String FILE_PATH = "FILE_PATH";
    public static final String OLD_DOC_BASE_DIRECTORY;
    public static final String DOC_BASE_DIRECTORY;
    public static final String DOC_FILE_DIRECTORY;
    public static final String TERMS_DOC_FILE_DIRECTORY;
    public static final String LEARN_MORE_LINK;
    public static final int SUCCESS = 1;
    public static final int GENERIC_ERROR = 90001;
    public static final int SECURITY_ERROR = 90002;
    public static final int INVALID_FILE_ERROR = 90003;
    public static final int UNSUPPORTED_FORMAT_ERROR = 90004;
    public static final int TAG_ALREADY_EXISTS_ERROR = 90005;
    public static final int FILE_NAME_EXISTS_WARNING = 90006;
    public static final int FILES_ADDED = 90007;
    public static final int CYCLIC_GROUP_ERROR = 90008;
    public static final int UPLOAD_ERROR = 90009;
    public static final int TAG_DOESNT_EXISTS_ERROR = 90010;
    public static final int UNKNOWN_TYPE = 0;
    public static final String UNKNOWN = "NA";
    public static final int DOC_VAL = 1;
    public static final String DOC = ".doc";
    public static final int PPT_VAL = 2;
    public static final String PPT = ".ppt";
    public static final int XLS_VAL = 3;
    public static final String XLS = ".xls";
    public static final int PDF_VAL = 4;
    public static final String PDF = ".pdf";
    public static final int TXT_VAL = 5;
    public static final String TXT = ".txt";
    public static final int XPS_VAL = 6;
    public static final String XPS = ".xps";
    public static final int PPTX_VAL = 7;
    public static final String PPTX = ".pptx";
    public static final int XLSX_VAL = 8;
    public static final String XLSX = ".xlsx";
    public static final int DOCX_VAL = 9;
    public static final String DOCX = ".docx";
    public static final int EPUB_VAL = 10;
    public static final String EPUB = ".epub";
    public static final int RTF_VAL = 11;
    public static final String RTF = ".rtf";
    public static final int HTML_VAL = 12;
    public static final String HTML = ".html";
    public static final int JPEG_VAL = 13;
    public static final String JPEG = ".jpeg";
    public static final int JPG_VAL = 14;
    public static final String JPG = ".jpg";
    public static final int PNG_VAL = 15;
    public static final String PNG = ".png";
    public static final int GIF_VAL = 16;
    public static final String GIF = ".gif";
    public static final int BMP_VAL = 17;
    public static final String BMP = ".bmp";
    public static final int WAV_VAL = 18;
    public static final String WAV = ".wav";
    public static final int MP3_VAL = 19;
    public static final String MP3 = ".mp3";
    public static final int AU_VAL = 20;
    public static final String AU = ".au";
    public static final int AIFF_VAL = 21;
    public static final String AIFF = ".aiff";
    public static final int OGG_VAL = 22;
    public static final String OGG = ".ogg";
    public static final int MP4_VAL = 23;
    public static final String MP4 = ".mp4";
    public static final int MOV_VAL = 24;
    public static final String MOV = ".mov";
    public static final int FLV_VAL = 25;
    public static final String FLV = ".flv";
    public static final int TGP_VAL = 26;
    public static final String TGP = ".3gp";
    public static final int AVI_VAL = 27;
    public static final String AVI = ".avi";
    public static final int MKV_VAL = 28;
    public static final String MKV = ".mkv";
    public static final int OVPN_VAL = 29;
    public static final String OVPN = ".ovpn";
    public static final int SUPPORTED_DOC_TYPES = 28;
    public static final String TAGS_COUNT = "TAGS_COUNT";
    public static final int TAGS_TYPE = 1;
    public static final int DOC_TYPE = 2;
    public static final String DOC_PAGE_VISIT = "DOC_PAGE_VISIT";
    public static final String MAX_DOC_TAG_COUNT = "MAX_DOC_TAG_COUNT";
    public static final String MANAGED_DOCS_COUNT = "MANAGED_DOCS_COUNT";
    public static final String UNTAGGED_DOCS_COUNT = "UNTAGGED_DOCS_COUNT";
    public static final String DOC_USER_ASSOCIATION_COUNT = "DOC_USER_ASSOCIATION_COUNT";
    public static final String DOC_GROUP_ASSOCIATION_COUNT = "DOC_GROUP_ASSOCIATION_COUNT";
    public static final String DOC_DEVICE_ASSOCIATION_COUNT = "DOC_DEVICE_ASSOCIATION_COUNT";
    public static final int CONTENT_ADDED_EVENT_ID = 2101;
    public static final int CONTENT_UPDATED_EVENT_ID = 2102;
    public static final int CONTENT_DELETED_EVENT_ID = 2103;
    public static final int CONTENT_DEVICE_APPLIED_EVENT_ID = 2106;
    public static final int CONTENT_DEVICE_REMOVED_EVENT_ID = 2108;
    public static final int CONTENT_GROUP_APPLIED_EVENT_ID = 2109;
    public static final int CONTENT_GROUP_REMOVED_EVENT_ID = 2110;
    public static final int CONTENT_USER_APPLIED_EVENT_ID = 2111;
    public static final int CONTENT_USER_REMOVED_EVENT_ID = 2112;
    public static final int CONTENT_POLICY_GROUP_ADDED_EVENT_ID = 2113;
    public static final int CONTENT_POLICY_GROUP_REMOVED_EVENT_ID = 2114;
    public static final int CONTENT_POLICY_DEVICE_ADDED_EVENT_ID = 2115;
    public static final int CONTENT_POLICY_DEVICE_REMOVED_EVENT_ID = 2116;
    public static final int CONTENT_POLICY_USER_ADDED_EVENT_ID = 2117;
    public static final int CONTENT_POLICY_USER_REMOVED_EVENT_ID = 2118;
    public static final String CONTENT_ADDED_REMARK = "mdm.content.al.add";
    public static final String CONTENT_UPDATED_REMARK = "mdm.content.al.update";
    public static final String CONTENT_DELETED_REMARK = "mdm.content.al.remove";
    public static final String CONTENT_DEVICE_APPLIED_REMARK = "mdm.content.al.associate";
    public static final String CONTENT_DEVICE_REMOVED_REMARK = "mdm.content.al.disassociate";
    public static final String CONTENT_GROUP_APPLIED_REMARK = "mdm.content.group.associate";
    public static final String CONTENT_GROUP_REMOVED_REMARK = "mdm.content.group.disassociate";
    public static final String CONTENT_USER_APPLIED_REMARK = "mdm.content.user.associate";
    public static final String CONTENT_USER_REMOVED_REMARK = "mdm.content.user.disassociate";
    public static final String CONTENT_POLICY_GROUP_ADDED_REMARK = "mdm.content.user.disassociate";
    public static final String CONTENT_POLICY_GROUP_REMOVED_REMARK = "mdm.content.user.disassociate";
    public static final String CONTENT_POLICY_DEVICE_ADDED_REMARK = "mdm.content.user.disassociate";
    public static final String CONTENT_POLICY_DEVICE_REMOVED_REMARK = "mdm.content.user.disassociate";
    public static final String CONTENT_POLICY_USER_ADDED_REMARK = "mdm.content.user.disassociate";
    public static final String CONTENT_POLICY_USER_REMOVED_REMARK = "mdm.content.user.disassociate";
    public static final int CONTENT_MGMT_MDMP_PR_BUILD = 92243;
    public static final String PROCESS_TYPE = "PROCESS_TYPE";
    public static final String SYNC_REQUEST_TIME = "SYNC_REQUEST_TIME";
    public static final String UPDATE_SYNC_DOC_DIFF = "UPDATE_SYNC_DOC_DIFF";
    public static final String STATUS_UPDATE_TASK = "STATUS_UPDATE_TASK";
    public static final String DOC_MGMT_HANDLER_CLASS = "com.me.mdm.server.doc.DocMgmtDataHandler";
    public static final String DOC_MGMT_HANDLER_METHOD = "handleDocument";
    public static final String CONTENT_MGMT_POLICY = "policy";
    public static final String ACK_DOCUMENTS = "AckDocuments";
    public static final String ACK_SUPPORTED = "ACK_SUPPORTED";
    
    static {
        OLD_DOC_BASE_DIRECTORY = MDMMetaDataUtil.getInstance().getClientDataParentDir();
        DOC_BASE_DIRECTORY = MDMConstants.BASE_DIR + File.separator + "agent-files";
        DOC_FILE_DIRECTORY = File.separator + "MDM" + File.separator + "docrepository";
        TERMS_DOC_FILE_DIRECTORY = File.separator + "MDM" + File.separator + "TermsOfUseDocRepo";
        LEARN_MORE_LINK = UrlReplacementUtil.replaceUrlAndAppendTrackCode("$(mdmUrl)/help/content_management/mdm_document_distribution.html?");
    }
}
