package com.zoho.jschart;

public class JSCROOT
{
    public static final String LOADER = "loader";
    public static final String LOADER_TYPE = "org.json.JSONObject";
    public static final String LEGEND = "legend";
    public static final String LEGEND_TYPE = "org.json.JSONObject";
    public static final String NODATAHANDLER = "noDataHandler";
    public static final String NODATAHANDLER_TYPE = "org.json.JSONObject";
    public static final String CREDITS = "credits";
    public static final String CREDITS_TYPE = "org.json.JSONObject";
    public static final String CHART = "chart";
    public static final String CHART_TYPE = "org.json.JSONObject";
    public static final String CANVAS = "canvas";
    public static final String CANVAS_TYPE = "org.json.JSONObject";
    public static final String SERIESDATA = "seriesdata";
    public static final String SERIESDATA_TYPE = "org.json.JSONObject";
    public static final String NOTES = "notes";
    public static final String NOTES_TYPE = "org.json.JSONObject";
    public static final String METADATA = "metadata";
    public static final String METADATA_TYPE = "org.json.JSONObject";
    public static final String TOOLTIP = "tooltip";
    public static final String TOOLTIP_TYPE = "org.json.JSONObject";
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_MODELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_PATH;
    public static final String[] CHART_AXES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_STACKED_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_RANGE_VALUES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_DATALABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_DATALABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_DATALABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_DEPENDENCY_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_DATALABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_HOVEROPTIONS_PATH;
    public static final String[] CHART_AXES_XAXIS_TICKLABEL_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_DATALABELS_PATH;
    public static final String[] METADATA_AXES_LABEL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_INNERLABEL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_AXES_YAXIS_SUBTICKMARK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_STACKED_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_GRADIENTS_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_RANGE_LABEL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_PLOT_BACKGROUND_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_INNERLABEL_BOUNDBOX_PATH;
    public static final String[] LEGEND_SHADOW_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_LEVELMARKER_PATH;
    public static final String[] CANVAS_INTELLIGENCE_DIMENSION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_GRADIENTS_PATH;
    public static final String[] LEGEND_FILTER_SLIDER_TRIANGLEDOWN_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_LINE_MARKER_PATH;
    public static final String[] LEGEND_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_MARKER_PATH;
    public static final String[] TOOLTIP_FIXED_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_DATALABELS_PATH;
    public static final String[] NOTES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_ANIMATION_PATH;
    public static final String[] CHART_PLOT_BACKGROUND_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_GRADIENTS_OPTIONS_RADIAL_PATH;
    public static final String[] CHART_AXES_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_PATH;
    public static final String[] CHART_SCROLL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_TARGETMARKER_EVENTS_PATH;
    public static final String[] METADATA_COLUMNS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_NEEDLE_PATH;
    public static final String[] CANVAS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_ANIMATION_BLINK_PATH;
    public static final String[] NOTES_BLOCKVALUES_PATH;
    public static final String[] LEGEND_COLORAXIS_GRID_PATH;
    public static final String[] METADATA_COLUMNS_TIME_PATH;
    public static final String[] LEGEND_COLORBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_ANIMATION_BLINK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_INNERLABEL_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_STACKED_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_MARKER_PATH;
    public static final String[] CHART_AXES_YAXIS_TICKMARK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_LEVELMARKER_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_COLOROVERLAY_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_GRADIENTS_OPTIONS_PATH;
    public static final String[] METADATA_AXES_CLR_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_LINE_PATH;
    public static final String[] CHART_AXES_YAXIS_BASELINE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_LEVELMARKER_COLOR_PATH;
    public static final String[] LEGEND_BORDER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_RANGE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CANVAS_INTELLIGENCE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_MODELS_PATH;
    public static final String[] NOTES_CHARTVALUES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_DATALABELS_BOUNDBOX_PATH;
    public static final String[] SERIESDATA_CHARTDATA_YAXISCOLUMNORDER_PATH;
    public static final String[] CHART_AXES_YAXIS_LABEL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_DATALABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_INNERLABEL_PATH;
    public static final String[] CHART_AXES_YAXIS_PATH;
    public static final String[] CHART_AXES_XAXIS_LABEL_PATH;
    public static final String[] CREDITS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] METADATA_COLUMNS_NUMERIC_FORMAT_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_LINE_MARKER_HOVEROPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_LINE_PATH;
    public static final String[] NODATAHANDLER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_GRADIENTS_PATH;
    public static final String[] NOTES_OPTIONS_PATH;
    public static final String[] LEGEND_EXPANDABLE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_LEVELMARKER_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_MARKER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_HOVEROPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_ANIMATION_MARQUEE_PATH;
    public static final String[] CANVAS_BORDER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_MINMAXLABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_DATALABELS_PATH;
    public static final String[] CHART_AXES_XAXIS_GRID_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_ANIMATION_PATH;
    public static final String[] CANVAS_BACKGROUND_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_DATALABELS_STACKLABELS_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_COLOROVERLAY_VALUES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CANVAS_BACKGROUND_PATH;
    public static final String[] LEGEND_ITEMDISABLEDSTYLE_COLORBOX_PATH;
    public static final String[] CHART_ZOOM_RESETBUTTON_BORDER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_MARKER_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_LINE_EVENTS_PATH;
    public static final String[] LEGEND_COLORAXIS_MINMAXLABELS_PATH;
    public static final String[] CHART_AXES_YAXIS_TICKLABEL_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_HOVEROPTIONS_PATH;
    public static final String[] TOOLTIP_RELATIVE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_TARGETMARKER_LABEL_PATH;
    public static final String[] LEGEND_FILTER_SLIDER_LEVER_PATH;
    public static final String[] CHART_SCROLL_TRACKER_PATH;
    public static final String[] CHART_ZOOM_PATH;
    public static final String[] CHART_ZOOM_RESETBUTTON_LABEL_PATH;
    public static final String[] NOTES_OPTIONS_CUSTOMNOTE_PATH;
    public static final String[] LEGEND_FILTER_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_COLOROVERLAY_VALUES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_MARKER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_MARKER_PATH;
    public static final String[] METADATA_AXES_TOOLTIP_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_BORDER_PATH;
    public static final String[] SERIESDATA_STACKGROUP_PATH;
    public static final String[] METADATA_AXES_GROUPBY_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_BORDER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_AXES_XAXIS_TICKLABEL_MINMAXLABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_EVENTS_PATH;
    public static final String[] LEGEND_FILTER_RANGE_PATH;
    public static final String[] LEGEND_FILTER_SLIDER_TOOLTIP_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_STACKED_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_DATALABELS_BOUNDBOX_PATH;
    public static final String[] LEGEND_COLORAXIS_AXISLINE_PATH;
    public static final String[] SERIESDATA_CHARTDATA_PATH;
    public static final String[] LEGEND_FILTER_SLIDER_HOLLOWCIRCLE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_PATH;
    public static final String[] CHART_PLOT_DATALABELS_PATH;
    public static final String[] LEGEND_FILTER_SLIDER_VERNIER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_TARGETMARKER_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_INNERLABEL_PARENTLABEL_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_LINE_MARKER_HOVEROPTIONS_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_PATH;
    public static final String[] LEGEND_TITLE_PATH;
    public static final String[] CHART_AXES_XAXIS_TICKLABEL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_PATH;
    public static final String[] LEGEND_COLORAXIS_TICKMARK_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_RANGE_PATH;
    public static final String[] METADATA_COLUMNS_NUMERIC_FORMAT_ZEROPADDING_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_PATH;
    public static final String[] LEGEND_COLORAXIS_PATH;
    public static final String[] METADATA_COLUMNS_ORDINAL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_INNERLABEL_BOUNDBOX_HOOK_PATH;
    public static final String[] LEGEND_ITEMDISABLEDSTYLE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] LOADER_PATH;
    public static final String[] METADATA_AXES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_GRADIENTS_OPTIONS_RADIAL_PATH;
    public static final String[] LEGEND_FILTER_SLIDER_PENTAGON_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_INNERLABEL_BOUNDBOX_PATH;
    public static final String[] CHART_EFFECTS_OPTIONS_FREEHAND_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_COLOROVERLAY_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_MARKER_END_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_LINE_PATH;
    public static final String[] CHART_AXES_YAXIS_GRID_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_DATALABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_PATH;
    public static final String[] LEGEND_SELECTALLBOX_TOOLTIP_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] METADATA_COLUMNS_TIME_FORMAT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_INNERLABEL_PATH;
    public static final String[] LEGEND_FILTER_TRACK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_TARGETMARKER_LABEL_PATH;
    public static final String[] TOOLTIP_CROSSHAIR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_GRADIENTS_OPTIONS_RADIAL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_ANIMATION_PATH;
    public static final String[] CHART_PLOT_BORDER_PATH;
    public static final String[] CHART_EFFECTS_OPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_ANIMATION_BLINK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_GRADIENTS_PATH;
    public static final String[] CHART_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_EVENTS_PATH;
    public static final String[] LEGEND_COLORPALLETE_OPTIONS_MONOCHROME_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_LEVELMARKER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_ANIMATION_PATH;
    public static final String[] CHART_AXES_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_GRADIENTS_OPTIONS_RADIAL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_INNERLABEL_BOUNDBOX_PATH;
    public static final String[] CANVAS_SHADOW_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_GRADIENTS_OPTIONS_RADIAL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_DATALABELS_STACKLABELS_PATH;
    public static final String[] METADATA_AXES_GEOIDXPOS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_DATALABELS_PATH;
    public static final String[] CHART_AXES_XAXIS_AXISLINE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_ANIMATION_PATH;
    public static final String[] METADATA_AXES_X_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_GRADIENTS_PATH;
    public static final String[] CANVAS_EVENTS_PATH;
    public static final String[] METADATA_AXES_Y_PATH;
    public static final String[] LEGEND_COLORBAND_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] METADATA_AXES_Z_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_DATALABELS_BOUNDBOX_PATH;
    public static final String[] LEGEND_SELECTALLBOX_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_EVENTS_PATH;
    public static final String[] CHART_PLOT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_MARKER_PATH;
    public static final String[] CHART_SCROLL_RESIZER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_LEVELMARKER_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_TARGETMARKER_PATH;
    public static final String[] LEGEND_FILTER_SLIDER_CIRCLE_PATH;
    public static final String[] CHART_EFFECTS_PATH;
    public static final String[] LEGEND_FILTER_SLIDER_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_LINE_PATH;
    public static final String[] NOTES_OPTIONS_STICKYNOTE_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_LINE_LABEL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_AXES_YAXIS_TICKLABEL_MINMAXLABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_PATH;
    public static final String[] TOOLTIP_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_AXES_YAXIS_TICKLABEL_PATH;
    public static final String[] CHART_PLOT_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_DATALABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_DATALABELS_PATH;
    public static final String[] LEGEND_COLORPALLETE_PATH;
    public static final String[] LEGEND_HIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_TARGETMARKER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_LEVELMARKER_PATH;
    public static final String[] CHART_AXES_YAXIS_AXISLINE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_ANIMATION_BLINK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_LINE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_HOVEROPTIONS_PATH;
    public static final String[] CHART_PLOT_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_ZOOM_RESETBUTTON_SHADOW_PATH;
    public static final String[] CHART_ZOOM_SELECTIONAREA_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_EVENTS_PATH;
    public static final String[] LEGEND_FILTER_SLIDER_TRIANGLEUP_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_GRADIENTS_OPTIONS_PATH;
    public static final String[] TOOLTIP_BLOCK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_GRADIENTS_OPTIONS_RADIAL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_MARKER_START_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_RANGE_VALUES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_GRADIENTS_OPTIONS_RADIAL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_ANIMATION_PATH;
    public static final String[] CANVAS_SUBTITLE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_INNERLABEL_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_SCROLL_SLIDER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_HOVEROPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_DATALABELS_BOUNDBOX_PATH;
    public static final String[] SERIESDATA_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_ANIMATION_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_LINE_VALUES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_HOVEROPTIONS_PATH;
    public static final String[] METADATA_COLUMNS_NUMERIC_PATH;
    public static final String[] NOTES_PLOTVALUES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_ANIMATION_MARQUEE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_GRADIENTS_PATH;
    public static final String[] CHART_AXES_XAXIS_THRESHOLD_LINE_VALUES_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_ZOOM_RESETBUTTON_PATH;
    public static final String[] METADATA_COLUMNS_ORDINAL_FORMAT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_DEPENDENCY_LINK_PATH;
    public static final String[] CANVAS_INTELLIGENCE_DATACOUNT_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_RANGE_LABEL_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_EMPTYFUNNEL_PATH;
    public static final String[] METADATA_PATH;
    public static final String[] LEGEND_EVENTS_PATH;
    public static final String[] CHART_EFFECTS_OPTIONS_DROPSHADOW_PATH;
    public static final String[] CANVAS_TITLE_PATH;
    public static final String[] LEGEND_ITEMHOVERSTYLE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_DATALABELS_PATH;
    public static final String[] CHART_PLOT_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_LINE_LABEL_PATH;
    public static final String[] LEGEND_COLORAXIS_TICKLABEL_PATH;
    public static final String[] LEGEND_COLORPALLETE_OPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BAR_GRADIENTS_OPTIONS_PATH;
    public static final String[] LEGEND_BACKGROUND_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_AXES_XAXIS_TICKMARK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_ANIMATION_PATH;
    public static final String[] SERIESDATA_CHARTDATA_DATA_PATH;
    public static final String[] METADATA_COLUMNS_TIME_GROUPBY_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_GRADIENTS_OPTIONS_LINEAR_PATH;
    public static final String[] CHART_AXES_XAXIS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PYRAMID_DATALABELS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BULLET_DATALABELS_BOUNDBOX_HOOK_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_SCATTER_GRADIENTS_OPTIONS_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_LINE_MARKER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_LINE_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_GANTT_DEPENDENCY_MARKER_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLE_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] LEGEND_SELECTALLBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_LEGENDHIGHLIGHTEFFECT_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_PATH;
    public static final String[] CHART_AXES_YAXIS_THRESHOLD_LINE_EVENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREA_HOVEROPTIONS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_WEB_ANIMATION_MARQUEE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_DATALABELS_BOUNDBOX_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_HEATMAP_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_GRADIENTS_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_DIAL_ANIMATION_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_AREARANGE_ANIMATION_MARQUEE_PATH;
    public static final String[] CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_BOUNDBOX_PATH;
    
    static {
        CHART_PLOT_PLOTOPTIONS_BULLET_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid", "gradients", "options" };
        CHART_PLOT_PLOTOPTIONS_GANTT_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "legendHighlightEffect" };
        CHART_AXES_XAXIS_THRESHOLD_PATH = new String[] { "chart", "axes", "xaxis", "threshold" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_MODELS_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "models" };
        CHART_PLOT_PLOTOPTIONS_WEB_PATH = new String[] { "chart", "plot", "plotoptions", "web" };
        CHART_AXES_PATH = new String[] { "chart", "axes" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_PATH = new String[] { "chart", "plot", "plotoptions", "bubble" };
        CHART_PLOT_PLOTOPTIONS_BULLET_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_WEB_STACKED_PATH = new String[] { "chart", "plot", "plotoptions", "web", "stacked" };
        CHART_AXES_YAXIS_THRESHOLD_RANGE_VALUES_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "range", "values" };
        CHART_PLOT_PLOTOPTIONS_LINE_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "line", "datalabels" };
        CHART_PLOT_PLOTOPTIONS_WEB_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "web", "gradients", "options" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "datalabels" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap", "datalabels" };
        CHART_PLOT_PLOTOPTIONS_GANTT_DEPENDENCY_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "dependency" };
        CHART_PLOT_PLOTOPTIONS_DIAL_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "datalabels" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_HOVEROPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "hoveroptions" };
        CHART_AXES_XAXIS_TICKLABEL_EVENTS_PATH = new String[] { "chart", "axes", "xaxis", "ticklabel", "events" };
        CHART_PLOT_PLOTOPTIONS_WEB_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "web", "datalabels" };
        METADATA_AXES_LABEL_PATH = new String[] { "metadata", "axes", "label" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_INNERLABEL_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "datalabels", "innerLabel" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "events" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "events" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_AREA_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "area", "gradients", "options" };
        CHART_AXES_YAXIS_SUBTICKMARK_PATH = new String[] { "chart", "axes", "yaxis", "subtickmark" };
        CHART_PLOT_PLOTOPTIONS_AREA_STACKED_PATH = new String[] { "chart", "plot", "plotoptions", "area", "stacked" };
        CHART_PLOT_PLOTOPTIONS_BULLET_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "gradients", "options" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "gradients" };
        CHART_AXES_XAXIS_THRESHOLD_RANGE_LABEL_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "range", "label" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap", "gradients", "options" };
        CHART_PLOT_BACKGROUND_PATH = new String[] { "chart", "plot", "background" };
        CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_INNERLABEL_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "datalabels", "innerLabel", "boundBox" };
        LEGEND_SHADOW_PATH = new String[] { "legend", "shadow" };
        CHART_PLOT_PLOTOPTIONS_PATH = new String[] { "chart", "plot", "plotoptions" };
        CHART_PLOT_PLOTOPTIONS_GANTT_LEVELMARKER_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "levelMarker" };
        CANVAS_INTELLIGENCE_DIMENSION_PATH = new String[] { "canvas", "intelligence", "dimension" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_WEB_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "web", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_BAR_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "gradients" };
        LEGEND_FILTER_SLIDER_TRIANGLEDOWN_PATH = new String[] { "legend", "filter", "slider", "triangleDown" };
        CHART_PLOT_PLOTOPTIONS_DIAL_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "datalabels", "boundBox" };
        CHART_AXES_XAXIS_THRESHOLD_LINE_MARKER_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "line", "marker" };
        LEGEND_PATH = new String[] { "legend" };
        CHART_PLOT_PLOTOPTIONS_GANTT_MARKER_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "marker" };
        TOOLTIP_FIXED_PATH = new String[] { "tooltip", "fixed" };
        CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "packedbubble", "datalabels" };
        NOTES_PATH = new String[] { "notes" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_PIE_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "events" };
        CHART_PLOT_PLOTOPTIONS_PIE_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "gradients" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "animation" };
        CHART_PLOT_BACKGROUND_GRADIENTS_PATH = new String[] { "chart", "plot", "background", "gradients" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap", "gradients" };
        CHART_PLOT_PLOTOPTIONS_WEB_GRADIENTS_OPTIONS_RADIAL_PATH = new String[] { "chart", "plot", "plotoptions", "web", "gradients", "options", "radial" };
        CHART_AXES_ANIMATION_PATH = new String[] { "chart", "axes", "animation" };
        CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_PATH = new String[] { "chart", "plot", "plotoptions", "packedbubble" };
        CHART_SCROLL_PATH = new String[] { "chart", "scroll" };
        CHART_PLOT_PLOTOPTIONS_BULLET_TARGETMARKER_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "targetMarker", "events" };
        METADATA_COLUMNS_PATH = new String[] { "metadata", "columns" };
        CHART_PLOT_PLOTOPTIONS_GANTT_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "animation" };
        CHART_PLOT_PLOTOPTIONS_DIAL_NEEDLE_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "needle" };
        CANVAS_PATH = new String[] { "canvas" };
        CHART_PLOT_PLOTOPTIONS_BULLET_PATH = new String[] { "chart", "plot", "plotoptions", "bullet" };
        CHART_PLOT_PLOTOPTIONS_LINE_ANIMATION_BLINK_PATH = new String[] { "chart", "plot", "plotoptions", "line", "animation", "blink" };
        NOTES_BLOCKVALUES_PATH = new String[] { "notes", "blockValues" };
        LEGEND_COLORAXIS_GRID_PATH = new String[] { "legend", "colorAxis", "grid" };
        METADATA_COLUMNS_TIME_PATH = new String[] { "metadata", "columns", "time" };
        LEGEND_COLORBOX_PATH = new String[] { "legend", "colorBox" };
        CHART_PLOT_PLOTOPTIONS_AREA_PATH = new String[] { "chart", "plot", "plotoptions", "area" };
        CHART_PLOT_PLOTOPTIONS_LINE_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "line", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "datalabels" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap", "events" };
        CHART_PLOT_PLOTOPTIONS_AREA_ANIMATION_BLINK_PATH = new String[] { "chart", "plot", "plotoptions", "area", "animation", "blink" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_INNERLABEL_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "datalabels", "innerLabel", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "legendHighlightEffect" };
        CHART_PLOT_PLOTOPTIONS_LINE_STACKED_PATH = new String[] { "chart", "plot", "plotoptions", "line", "stacked" };
        CHART_PLOT_PLOTOPTIONS_LINE_MARKER_PATH = new String[] { "chart", "plot", "plotoptions", "line", "marker" };
        CHART_AXES_YAXIS_TICKMARK_PATH = new String[] { "chart", "axes", "yaxis", "tickmark" };
        CHART_PLOT_PLOTOPTIONS_LINE_PATH = new String[] { "chart", "plot", "plotoptions", "line" };
        CHART_PLOT_PLOTOPTIONS_DIAL_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "gradients" };
        CHART_PLOT_PLOTOPTIONS_BAR_LEVELMARKER_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "levelMarker" };
        CHART_AXES_XAXIS_THRESHOLD_COLOROVERLAY_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "coloroverlay" };
        CHART_PLOT_PLOTOPTIONS_GANTT_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "gradients", "options" };
        METADATA_AXES_CLR_PATH = new String[] { "metadata", "axes", "clr" };
        CHART_AXES_YAXIS_THRESHOLD_LINE_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "line" };
        CHART_AXES_YAXIS_BASELINE_PATH = new String[] { "chart", "axes", "yaxis", "baseline" };
        CHART_PLOT_PLOTOPTIONS_BULLET_LEVELMARKER_COLOR_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "levelMarker", "color" };
        LEGEND_BORDER_PATH = new String[] { "legend", "border" };
        CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "packedbubble", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_GANTT_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "gradients" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "gradients", "options" };
        CHART_AXES_XAXIS_THRESHOLD_RANGE_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "range" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid", "legendHighlightEffect" };
        CANVAS_INTELLIGENCE_PATH = new String[] { "canvas", "intelligence" };
        CHART_PLOT_PLOTOPTIONS_PIE_MODELS_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "models" };
        NOTES_CHARTVALUES_PATH = new String[] { "notes", "chartValues" };
        CHART_PLOT_PLOTOPTIONS_WEB_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "web", "events" };
        CHART_PLOT_PLOTOPTIONS_AREA_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "area", "datalabels", "boundBox" };
        SERIESDATA_CHARTDATA_YAXISCOLUMNORDER_PATH = new String[] { "seriesdata", "chartdata", "yaxiscolumnorder" };
        CHART_AXES_YAXIS_LABEL_PATH = new String[] { "chart", "axes", "yaxis", "label" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "datalabels" };
        CHART_PLOT_PLOTOPTIONS_BULLET_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "gradients" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_INNERLABEL_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "datalabels", "innerLabel" };
        CHART_AXES_YAXIS_PATH = new String[] { "chart", "axes", "yaxis" };
        CHART_AXES_XAXIS_LABEL_PATH = new String[] { "chart", "axes", "xaxis", "label" };
        CREDITS_PATH = new String[] { "credits" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "gradients", "options", "linear" };
        METADATA_COLUMNS_NUMERIC_FORMAT_PATH = new String[] { "metadata", "columns", "numeric", "format" };
        CHART_AXES_XAXIS_THRESHOLD_LINE_MARKER_HOVEROPTIONS_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "line", "marker", "hoveroptions" };
        CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "packedbubble", "legendHighlightEffect" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_LINE_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "datalabels", "line" };
        NODATAHANDLER_PATH = new String[] { "noDataHandler" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "gradients" };
        NOTES_OPTIONS_PATH = new String[] { "notes", "options" };
        LEGEND_EXPANDABLE_PATH = new String[] { "legend", "expandable" };
        CHART_PLOT_PLOTOPTIONS_DIAL_LEVELMARKER_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "levelMarker", "events" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_WEB_MARKER_PATH = new String[] { "chart", "plot", "plotoptions", "web", "marker" };
        CHART_PLOT_PLOTOPTIONS_LINE_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "line", "gradients", "options" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_HOVEROPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "hoveroptions" };
        CHART_PLOT_PLOTOPTIONS_LINE_ANIMATION_MARQUEE_PATH = new String[] { "chart", "plot", "plotoptions", "line", "animation", "marquee" };
        CANVAS_BORDER_PATH = new String[] { "canvas", "border" };
        CHART_PLOT_PLOTOPTIONS_DIAL_MINMAXLABELS_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "minmaxlabels" };
        CHART_PLOT_PLOTOPTIONS_AREA_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "area", "datalabels" };
        CHART_AXES_XAXIS_GRID_PATH = new String[] { "chart", "axes", "xaxis", "grid" };
        CHART_PLOT_PLOTOPTIONS_LINE_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "line", "legendHighlightEffect" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "animation" };
        CANVAS_BACKGROUND_GRADIENTS_PATH = new String[] { "canvas", "background", "gradients" };
        CHART_PLOT_PLOTOPTIONS_WEB_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "web", "gradients" };
        CHART_PLOT_PLOTOPTIONS_GANTT_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_LINE_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "line", "animation" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "animation" };
        CHART_PLOT_PLOTOPTIONS_BULLET_DATALABELS_STACKLABELS_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "datalabels", "stackLabels" };
        CHART_AXES_YAXIS_THRESHOLD_COLOROVERLAY_VALUES_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "coloroverlay", "values" };
        CHART_PLOT_PLOTOPTIONS_AREA_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "area", "events" };
        CHART_PLOT_PLOTOPTIONS_BAR_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "legendHighlightEffect" };
        CANVAS_BACKGROUND_PATH = new String[] { "canvas", "background" };
        LEGEND_ITEMDISABLEDSTYLE_COLORBOX_PATH = new String[] { "legend", "itemDisabledStyle", "colorBox" };
        CHART_ZOOM_RESETBUTTON_BORDER_PATH = new String[] { "chart", "zoom", "resetButton", "border" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_MARKER_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "marker" };
        CHART_AXES_XAXIS_THRESHOLD_LINE_EVENTS_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "line", "events" };
        LEGEND_COLORAXIS_MINMAXLABELS_PATH = new String[] { "legend", "colorAxis", "minmaxlabels" };
        CHART_AXES_YAXIS_TICKLABEL_EVENTS_PATH = new String[] { "chart", "axes", "yaxis", "ticklabel", "events" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "gradients", "options" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_HOVEROPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "hoveroptions" };
        TOOLTIP_RELATIVE_PATH = new String[] { "tooltip", "relative" };
        CHART_PLOT_PLOTOPTIONS_BULLET_TARGETMARKER_LABEL_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "targetMarker", "label" };
        LEGEND_FILTER_SLIDER_LEVER_PATH = new String[] { "legend", "filter", "slider", "lever" };
        CHART_SCROLL_TRACKER_PATH = new String[] { "chart", "scroll", "tracker" };
        CHART_ZOOM_PATH = new String[] { "chart", "zoom" };
        CHART_ZOOM_RESETBUTTON_LABEL_PATH = new String[] { "chart", "zoom", "resetButton", "label" };
        NOTES_OPTIONS_CUSTOMNOTE_PATH = new String[] { "notes", "options", "customNote" };
        LEGEND_FILTER_PATH = new String[] { "legend", "filter" };
        CHART_AXES_XAXIS_THRESHOLD_COLOROVERLAY_VALUES_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "coloroverlay", "values" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_MARKER_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "marker" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_MARKER_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "marker" };
        METADATA_AXES_TOOLTIP_PATH = new String[] { "metadata", "axes", "tooltip" };
        CHART_PLOT_PLOTOPTIONS_GANTT_BORDER_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "border" };
        SERIESDATA_STACKGROUP_PATH = new String[] { "seriesdata", "stackGroup" };
        METADATA_AXES_GROUPBY_PATH = new String[] { "metadata", "axes", "groupby" };
        CHART_PLOT_PLOTOPTIONS_PIE_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_BAR_BORDER_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "border" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_AREA_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "area", "animation" };
        CHART_PLOT_PLOTOPTIONS_GANTT_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "datalabels", "boundBox", "hook" };
        CHART_AXES_XAXIS_TICKLABEL_MINMAXLABELS_PATH = new String[] { "chart", "axes", "xaxis", "ticklabel", "minmaxlabels" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "events" };
        LEGEND_FILTER_RANGE_PATH = new String[] { "legend", "filter", "range" };
        LEGEND_FILTER_SLIDER_TOOLTIP_PATH = new String[] { "legend", "filter", "slider", "tooltip" };
        CHART_PLOT_PLOTOPTIONS_AREA_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "area", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_BAR_STACKED_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "stacked" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_GANTT_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "datalabels", "boundBox" };
        LEGEND_COLORAXIS_AXISLINE_PATH = new String[] { "legend", "colorAxis", "axisline" };
        SERIESDATA_CHARTDATA_PATH = new String[] { "seriesdata", "chartdata" };
        LEGEND_FILTER_SLIDER_HOLLOWCIRCLE_PATH = new String[] { "legend", "filter", "slider", "hollowCircle" };
        CHART_PLOT_PLOTOPTIONS_GANTT_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "events" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "animation" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "datalabels" };
        CHART_PLOT_DATALABELS_PATH = new String[] { "chart", "plot", "datalabels" };
        LEGEND_FILTER_SLIDER_VERNIER_PATH = new String[] { "legend", "filter", "slider", "vernier" };
        CHART_PLOT_PLOTOPTIONS_DIAL_TARGETMARKER_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "targetMarker", "events" };
        CHART_PLOT_PLOTOPTIONS_LINE_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "line", "events" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_INNERLABEL_PARENTLABEL_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "datalabels", "innerLabel", "parentLabel" };
        CHART_AXES_YAXIS_THRESHOLD_LINE_MARKER_HOVEROPTIONS_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "line", "marker", "hoveroptions" };
        CHART_AXES_YAXIS_THRESHOLD_PATH = new String[] { "chart", "axes", "yaxis", "threshold" };
        LEGEND_TITLE_PATH = new String[] { "legend", "title" };
        CHART_AXES_XAXIS_TICKLABEL_PATH = new String[] { "chart", "axes", "xaxis", "ticklabel" };
        CHART_PLOT_PLOTOPTIONS_PIE_PATH = new String[] { "chart", "plot", "plotoptions", "pie" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_BAR_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "datalabels" };
        LEGEND_COLORAXIS_TICKMARK_PATH = new String[] { "legend", "colorAxis", "tickmark" };
        CHART_AXES_YAXIS_THRESHOLD_RANGE_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "range" };
        METADATA_COLUMNS_NUMERIC_FORMAT_ZEROPADDING_PATH = new String[] { "metadata", "columns", "numeric", "format", "zeroPadding" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_PATH = new String[] { "chart", "plot", "plotoptions", "arearange" };
        LEGEND_COLORAXIS_PATH = new String[] { "legend", "colorAxis" };
        METADATA_COLUMNS_ORDINAL_PATH = new String[] { "metadata", "columns", "ordinal" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_INNERLABEL_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "datalabels", "innerLabel", "boundBox", "hook" };
        LEGEND_ITEMDISABLEDSTYLE_PATH = new String[] { "legend", "itemDisabledStyle" };
        CHART_PLOT_PLOTOPTIONS_AREA_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "area", "datalabels", "boundBox", "hook" };
        LOADER_PATH = new String[] { "loader" };
        METADATA_AXES_PATH = new String[] { "metadata", "axes" };
        CHART_PLOT_PLOTOPTIONS_DIAL_GRADIENTS_OPTIONS_RADIAL_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "gradients", "options", "radial" };
        LEGEND_FILTER_SLIDER_PENTAGON_PATH = new String[] { "legend", "filter", "slider", "pentagon" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_INNERLABEL_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "datalabels", "innerLabel", "boundBox" };
        CHART_EFFECTS_OPTIONS_FREEHAND_PATH = new String[] { "chart", "effects", "options", "freeHand" };
        CHART_AXES_YAXIS_THRESHOLD_COLOROVERLAY_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "coloroverlay" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_GANTT_MARKER_END_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "marker", "end" };
        CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_LINE_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "datalabels", "line" };
        CHART_AXES_YAXIS_GRID_PATH = new String[] { "chart", "axes", "yaxis", "grid" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "datalabels" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_PATH = new String[] { "chart", "plot", "plotoptions", "scatter" };
        LEGEND_SELECTALLBOX_TOOLTIP_PATH = new String[] { "legend", "selectAllBox", "tooltip" };
        CHART_PLOT_PLOTOPTIONS_PIE_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "legendHighlightEffect" };
        METADATA_COLUMNS_TIME_FORMAT_PATH = new String[] { "metadata", "columns", "time", "format" };
        CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_INNERLABEL_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "datalabels", "innerLabel" };
        LEGEND_FILTER_TRACK_PATH = new String[] { "legend", "filter", "track" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid", "animation" };
        CHART_PLOT_PLOTOPTIONS_DIAL_TARGETMARKER_LABEL_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "targetMarker", "label" };
        TOOLTIP_CROSSHAIR_PATH = new String[] { "tooltip", "crosshair" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_GRADIENTS_OPTIONS_RADIAL_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "gradients", "options", "radial" };
        CHART_PLOT_PLOTOPTIONS_BAR_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "animation" };
        CHART_PLOT_BORDER_PATH = new String[] { "chart", "plot", "border" };
        CHART_EFFECTS_OPTIONS_PATH = new String[] { "chart", "effects", "options" };
        CHART_PLOT_PLOTOPTIONS_WEB_ANIMATION_BLINK_PATH = new String[] { "chart", "plot", "plotoptions", "web", "animation", "blink" };
        CHART_PLOT_PLOTOPTIONS_LINE_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "line", "gradients" };
        CHART_PATH = new String[] { "chart" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid", "gradients" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid", "events" };
        LEGEND_COLORPALLETE_OPTIONS_MONOCHROME_PATH = new String[] { "legend", "colorPallete", "options", "monochrome" };
        CHART_PLOT_PLOTOPTIONS_DIAL_LEVELMARKER_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "levelMarker" };
        CHART_PLOT_PLOTOPTIONS_BULLET_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "animation" };
        CHART_AXES_EVENTS_PATH = new String[] { "chart", "axes", "events" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_GRADIENTS_OPTIONS_RADIAL_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "gradients", "options", "radial" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_INNERLABEL_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "datalabels", "innerLabel", "boundBox" };
        CANVAS_SHADOW_PATH = new String[] { "canvas", "shadow" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_GRADIENTS_OPTIONS_RADIAL_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "gradients", "options", "radial" };
        CHART_PLOT_PLOTOPTIONS_BAR_DATALABELS_STACKLABELS_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "datalabels", "stackLabels" };
        METADATA_AXES_GEOIDXPOS_PATH = new String[] { "metadata", "axes", "geoidxpos" };
        CHART_PLOT_PLOTOPTIONS_WEB_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "web", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "packedbubble", "events" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "datalabels" };
        CHART_AXES_XAXIS_AXISLINE_PATH = new String[] { "chart", "axes", "xaxis", "axisline" };
        CHART_PLOT_PLOTOPTIONS_WEB_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "web", "animation" };
        METADATA_AXES_X_PATH = new String[] { "metadata", "axes", "x" };
        CHART_PLOT_PLOTOPTIONS_AREA_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "area", "gradients" };
        CANVAS_EVENTS_PATH = new String[] { "canvas", "events" };
        METADATA_AXES_Y_PATH = new String[] { "metadata", "axes", "y" };
        LEGEND_COLORBAND_PATH = new String[] { "legend", "colorBand" };
        CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "datalabels", "boundBox", "hook" };
        METADATA_AXES_Z_PATH = new String[] { "metadata", "axes", "z" };
        CHART_PLOT_PLOTOPTIONS_BAR_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "datalabels", "boundBox" };
        LEGEND_SELECTALLBOX_EVENTS_PATH = new String[] { "legend", "selectAllBox", "events" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "events" };
        CHART_PLOT_PATH = new String[] { "chart", "plot" };
        CHART_PLOT_PLOTOPTIONS_AREA_MARKER_PATH = new String[] { "chart", "plot", "plotoptions", "area", "marker" };
        CHART_SCROLL_RESIZER_PATH = new String[] { "chart", "scroll", "resizer" };
        CHART_PLOT_PLOTOPTIONS_BULLET_LEVELMARKER_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "levelMarker", "events" };
        CHART_PLOT_PLOTOPTIONS_BULLET_TARGETMARKER_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "targetMarker" };
        LEGEND_FILTER_SLIDER_CIRCLE_PATH = new String[] { "legend", "filter", "slider", "circle" };
        CHART_EFFECTS_PATH = new String[] { "chart", "effects" };
        LEGEND_FILTER_SLIDER_PATH = new String[] { "legend", "filter", "slider" };
        CHART_AXES_XAXIS_THRESHOLD_LINE_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "line" };
        NOTES_OPTIONS_STICKYNOTE_PATH = new String[] { "notes", "options", "stickyNote" };
        CHART_AXES_XAXIS_THRESHOLD_LINE_LABEL_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "line", "label" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "legendHighlightEffect" };
        CHART_AXES_YAXIS_TICKLABEL_MINMAXLABELS_PATH = new String[] { "chart", "axes", "yaxis", "ticklabel", "minmaxlabels" };
        CHART_PLOT_PLOTOPTIONS_WEB_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "web", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_GANTT_PATH = new String[] { "chart", "plot", "plotoptions", "gantt" };
        TOOLTIP_PATH = new String[] { "tooltip" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "legendHighlightEffect" };
        CHART_AXES_YAXIS_TICKLABEL_PATH = new String[] { "chart", "axes", "yaxis", "ticklabel" };
        CHART_PLOT_EVENTS_PATH = new String[] { "chart", "plot", "events" };
        CHART_PLOT_PLOTOPTIONS_DIAL_PATH = new String[] { "chart", "plot", "plotoptions", "dial" };
        CHART_PLOT_PLOTOPTIONS_WEB_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "web", "legendHighlightEffect" };
        CHART_PLOT_PLOTOPTIONS_BAR_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "events" };
        CHART_PLOT_PLOTOPTIONS_DIAL_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_BULLET_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "datalabels" };
        CHART_PLOT_PLOTOPTIONS_PIE_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "animation" };
        CHART_PLOT_PLOTOPTIONS_BULLET_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "legendHighlightEffect" };
        CHART_PLOT_PLOTOPTIONS_BAR_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "datalabels" };
        LEGEND_COLORPALLETE_PATH = new String[] { "legend", "colorPallete" };
        LEGEND_HIGHLIGHTEFFECT_PATH = new String[] { "legend", "highlightEffect" };
        CHART_PLOT_PLOTOPTIONS_DIAL_TARGETMARKER_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "targetMarker" };
        CHART_PLOT_PLOTOPTIONS_BULLET_LEVELMARKER_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "levelMarker" };
        CHART_AXES_YAXIS_AXISLINE_PATH = new String[] { "chart", "axes", "yaxis", "axisline" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_ANIMATION_BLINK_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "animation", "blink" };
        CHART_PLOT_PLOTOPTIONS_SUNBURST_DATALABELS_LINE_PATH = new String[] { "chart", "plot", "plotoptions", "sunburst", "datalabels", "line" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_HOVEROPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "hoveroptions" };
        CHART_PLOT_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_DIAL_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "gradients", "options" };
        CHART_ZOOM_RESETBUTTON_SHADOW_PATH = new String[] { "chart", "zoom", "resetButton", "shadow" };
        CHART_ZOOM_SELECTIONAREA_PATH = new String[] { "chart", "zoom", "selectionArea" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_DIAL_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "events" };
        LEGEND_FILTER_SLIDER_TRIANGLEUP_PATH = new String[] { "legend", "filter", "slider", "triangleUp" };
        CHART_PLOT_PLOTOPTIONS_PIE_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "gradients", "options" };
        TOOLTIP_BLOCK_PATH = new String[] { "tooltip", "block" };
        CHART_PLOT_PLOTOPTIONS_BAR_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "events" };
        CHART_PLOT_PLOTOPTIONS_DIAL_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "gradients", "options", "linear" };
        CHART_PLOT_PLOTOPTIONS_PIE_GRADIENTS_OPTIONS_RADIAL_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "gradients", "options", "radial" };
        CHART_PLOT_PLOTOPTIONS_GANTT_MARKER_START_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "marker", "start" };
        CHART_AXES_XAXIS_THRESHOLD_RANGE_VALUES_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "range", "values" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_GRADIENTS_OPTIONS_RADIAL_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap", "gradients", "options", "radial" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "gradients" };
        CHART_PLOT_ANIMATION_PATH = new String[] { "chart", "plot", "animation" };
        CANVAS_SUBTITLE_PATH = new String[] { "canvas", "subtitle" };
        CHART_PLOT_PLOTOPTIONS_BULLET_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "events" };
        CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_INNERLABEL_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "datalabels", "innerLabel", "boundBox", "hook" };
        CHART_SCROLL_SLIDER_PATH = new String[] { "chart", "scroll", "slider" };
        CHART_PLOT_PLOTOPTIONS_LINE_HOVEROPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "line", "hoveroptions" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "datalabels", "boundBox" };
        SERIESDATA_PATH = new String[] { "seriesdata" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "animation" };
        CHART_AXES_YAXIS_THRESHOLD_LINE_VALUES_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "line", "values" };
        CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "packedbubble", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_WEB_HOVEROPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "web", "hoveroptions" };
        METADATA_COLUMNS_NUMERIC_PATH = new String[] { "metadata", "columns", "numeric" };
        NOTES_PLOTVALUES_PATH = new String[] { "notes", "plotValues" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_EVENTS_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "events" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "legendHighlightEffect" };
        CHART_PLOT_PLOTOPTIONS_PACKEDBUBBLE_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "packedbubble", "animation" };
        CHART_PLOT_PLOTOPTIONS_AREA_ANIMATION_MARQUEE_PATH = new String[] { "chart", "plot", "plotoptions", "area", "animation", "marquee" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "gradients" };
        CHART_AXES_XAXIS_THRESHOLD_LINE_VALUES_PATH = new String[] { "chart", "axes", "xaxis", "threshold", "line", "values" };
        CHART_PLOT_PLOTOPTIONS_AREA_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "area", "legendHighlightEffect" };
        CHART_ZOOM_RESETBUTTON_PATH = new String[] { "chart", "zoom", "resetButton" };
        METADATA_COLUMNS_ORDINAL_FORMAT_PATH = new String[] { "metadata", "columns", "ordinal", "format" };
        CHART_PLOT_PLOTOPTIONS_GANTT_DEPENDENCY_LINK_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "dependency", "link" };
        CANVAS_INTELLIGENCE_DATACOUNT_PATH = new String[] { "canvas", "intelligence", "dataCount" };
        CHART_AXES_YAXIS_THRESHOLD_RANGE_LABEL_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "range", "label" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_EMPTYFUNNEL_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "emptyFunnel" };
        METADATA_PATH = new String[] { "metadata" };
        LEGEND_EVENTS_PATH = new String[] { "legend", "events" };
        CHART_EFFECTS_OPTIONS_DROPSHADOW_PATH = new String[] { "chart", "effects", "options", "dropShadow" };
        CANVAS_TITLE_PATH = new String[] { "canvas", "title" };
        LEGEND_ITEMHOVERSTYLE_PATH = new String[] { "legend", "itemHoverStyle" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "gradients", "options" };
        CHART_PLOT_PLOTOPTIONS_BAR_PATH = new String[] { "chart", "plot", "plotoptions", "bar" };
        CHART_PLOT_PLOTOPTIONS_GANTT_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "datalabels" };
        CHART_PLOT_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "datalabels", "boundBox", "hook" };
        CHART_AXES_YAXIS_THRESHOLD_LINE_LABEL_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "line", "label" };
        LEGEND_COLORAXIS_TICKLABEL_PATH = new String[] { "legend", "colorAxis", "ticklabel" };
        LEGEND_COLORPALLETE_OPTIONS_PATH = new String[] { "legend", "colorPallete", "options" };
        CHART_PLOT_PLOTOPTIONS_BAR_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "bar", "gradients", "options" };
        LEGEND_BACKGROUND_PATH = new String[] { "legend", "background" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "gradients", "options" };
        CHART_AXES_XAXIS_TICKMARK_PATH = new String[] { "chart", "axes", "xaxis", "tickmark" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "animation" };
        SERIESDATA_CHARTDATA_DATA_PATH = new String[] { "seriesdata", "chartdata", "data" };
        METADATA_COLUMNS_TIME_GROUPBY_PATH = new String[] { "metadata", "columns", "time", "groupby" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_GRADIENTS_OPTIONS_LINEAR_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "gradients", "options", "linear" };
        CHART_AXES_XAXIS_PATH = new String[] { "chart", "axes", "xaxis" };
        CHART_PLOT_PLOTOPTIONS_PYRAMID_DATALABELS_PATH = new String[] { "chart", "plot", "plotoptions", "pyramid", "datalabels" };
        CHART_PLOT_PLOTOPTIONS_LINE_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "line", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_PIE_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "pie", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_BULLET_DATALABELS_BOUNDBOX_HOOK_PATH = new String[] { "chart", "plot", "plotoptions", "bullet", "datalabels", "boundBox", "hook" };
        CHART_PLOT_PLOTOPTIONS_SCATTER_GRADIENTS_OPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "scatter", "gradients", "options" };
        CHART_AXES_YAXIS_THRESHOLD_LINE_MARKER_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "line", "marker" };
        CHART_PLOT_PLOTOPTIONS_LINE_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "line", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_GANTT_DEPENDENCY_MARKER_PATH = new String[] { "chart", "plot", "plotoptions", "gantt", "dependency", "marker" };
        CHART_PLOT_PLOTOPTIONS_BUBBLE_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "bubble", "legendHighlightEffect" };
        LEGEND_SELECTALLBOX_PATH = new String[] { "legend", "selectAllBox" };
        CHART_PLOT_PLOTOPTIONS_BUBBLEPIE_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "bubblepie", "legendHighlightEffect" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_LEGENDHIGHLIGHTEFFECT_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap", "legendHighlightEffect" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_PATH = new String[] { "chart", "plot", "plotoptions", "funnel" };
        CHART_AXES_YAXIS_THRESHOLD_LINE_EVENTS_PATH = new String[] { "chart", "axes", "yaxis", "threshold", "line", "events" };
        CHART_PLOT_PLOTOPTIONS_AREA_HOVEROPTIONS_PATH = new String[] { "chart", "plot", "plotoptions", "area", "hoveroptions" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap", "animation" };
        CHART_PLOT_PLOTOPTIONS_WEB_ANIMATION_MARQUEE_PATH = new String[] { "chart", "plot", "plotoptions", "web", "animation", "marquee" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap", "datalabels", "boundBox" };
        CHART_PLOT_PLOTOPTIONS_HEATMAP_PATH = new String[] { "chart", "plot", "plotoptions", "heatmap" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_GRADIENTS_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "gradients" };
        CHART_PLOT_PLOTOPTIONS_DIAL_ANIMATION_PATH = new String[] { "chart", "plot", "plotoptions", "dial", "animation" };
        CHART_PLOT_PLOTOPTIONS_AREARANGE_ANIMATION_MARQUEE_PATH = new String[] { "chart", "plot", "plotoptions", "arearange", "animation", "marquee" };
        CHART_PLOT_PLOTOPTIONS_FUNNEL_DATALABELS_BOUNDBOX_PATH = new String[] { "chart", "plot", "plotoptions", "funnel", "datalabels", "boundBox" };
    }
}
