package com.me.mdm.chrome.agent.core;

public class CommandConstants
{
    public static final String STATUS = "Status";
    public static final String STATE = "State";
    public static final String COMMANDUUID = "CommandUUID";
    public static final String COMMAND = "Command";
    public static final String CMD_VERSION = "CommandVersion";
    public static final String CMD_SCOPE = "CommandScope";
    public static final String CMD_SCOPE_DEVICE = "device";
    public static final String CMD_SCOPE_CONTAINER = "container";
    public static final String IS_ADMIN_ENROLLMENT = "IsAdminEnrollment";
    public static final String REQUEST_TYPE = "RequestType";
    public static final String REQUEST_DATA = "RequestData";
    public static final String COMMAND_RESPONSE = "CommandResponse";
    public static final String RESPONSE_TYPE = "ResponseType";
    public static final String RESPONSE_DATA = "ResponseData";
    public static final String REMARKS = "Remarks";
    public static final String ERROR_MSG = "ErrorMsg";
    public static final String ERROR_CODE = "ErrorCode";
    public static final String UDID = "UDID";
    public static final String IDLE_STATUS = "Idle";
    public static final String ACK_STATUS = "Acknowledged";
    public static final String NOT_NOW_STATUS = "NotNow";
    public static final String ERR_STATUS = "Error";
    public static final String AGENT_TYPE = "AgentType";
    public static final String MSG_VERSION = "MessageVersion";
    public static final String MSG_CONTENT = "Message";
    public static final String MSG_RESPONSE = "MessageResponse";
    public static final String MSG_TYPE = "MessageType";
    public static final String MSG_ENROLLMENT = "Enrollment";
    public static final String MSG_REMOVEDEVICE = "RemoveDevice";
    public static final String AGENT_VERSION = "0.0.1 CMPA";
    public static final Integer AGENT_VERSION_CODE;
    public static final String MESSAGE_TYPE = "MessageType";
    public static final String MESSAGE_REQUEST_TYPE = "MsgRequestType";
    public static final String DEVICE_PLATFORM = "DevicePlatform";
    public static final String DEVICE_PLATFORM_CHROME_OS = "Chrome OS";
    public static final String INVENTORY_ASSET_SCAN = "AssetScan";
    public static final String INSTALL_PROFILE = "InstallProfile";
    public static final String REMOVE_PROFILE = "RemoveProfile";
    public static final String NETWORK_INFO = "NetworkInfo";
    public static final String INSTALLED_APPS_INFO = "InstalledAppsInfo";
    public static final String NETWORK_USAGE_INFO = "NetworkUsageInfo";
    public static final String SECURITY_INFO = "SecurityInfo";
    public static final String CUSTOM_FIELDS_INFO = "CustomFieldsInfo";
    public static final String SYSTEM_ACTIVITY_INFO = "SystemActivityInfo";
    public static final String DEVICE_INFO = "DeviceInfo";
    public static final String LOCATION_INFO = "LocationInfo";
    public static final String CERTIFICATE_INFO = "CertificateInfo";
    public static final String RESTRICTION_INFO = "RestrictionInfo";
    public static final String PRELOADED_APPS_INFO = "PreloadedAppsInfo";
    public static final String PERSONAL_APPS_INFO = "PersonalAppsInfo";
    public static final String RESTRICTIONS = "Restriction";
    public static final String OS_UPDATE_INFO = "OSUpdateInfo";
    public static final String ENABLE_LOST_MODE = "EnableLostMode";
    public static final String DISABLE_LOST_MODE = "DisableLostMode";
    public static final String DEPROVISION = "Deprovision";
    public static final String CORPORATE_WIPE = "CorporateWipe";
    public static final String REMOVE_DEVICE = "RemoveDevice";
    public static final String RESTART_DEVICE = "RestartDevice";
    public static final String OS_UPDATE_POLICY = "ChromeOsUpdatePolicy";
    public static final String REMOVE_OS_UPDATE_POLICY = "RemoveChromeOsUpdatePolicy";
    public static final String APPLY_POWER_IDLE_SETTINGS = "ApplyPowerIdleSettings";
    public static final String REMOVE_POWER_IDLE_SETTINGS = "RemovePowerIdleSettings";
    public static final String POWER_IDLE_SETTING_POLICY = "PowerIdleSettingPolicy";
    public static final String INSTALL_APPLICATION = "InstallApplication";
    public static final String REMOVE_APPLICATION = "RemoveApplication";
    public static final String SYNC_PRIVACY_POLICY = "SyncPrivacySettings";
    public static final String PRIVACY_SETTINGS = "PrivacySettings";
    public static final String TAKE_A_SCREENSHOT = "TakeScreenshot";
    public static final int SUCCESS_ERROR_CODE = 0;
    public static final int ERROR_INVALID_COMMAND = 12100;
    public static final int ERROR_INVALID_PAYLOAD = 12110;
    public static final int ERROR_INCOMPATIBLE_SDK_USED = 12115;
    public static final int ERROR_APP_NOT_INSTALLED = 12040;
    public static final int ERROR_APP_UNINSTALL_FAILED = 12041;
    public static final int ERROR_APP_ALREADY_INSTALLED = 12042;
    public static final int ERROR_APP_INSTALLATION_FAILED = 12043;
    public static final int ERROR_SAME_VERSION_INSTALLED = 12050;
    public static final int ERROR_AGENT_UPGRADE_FAILED = 12051;
    public static final int ERROR_INVALID_DATA_RECEIVED = 12060;
    public static final int ERROR_INVENTORY_SCAN_FAILED = 12070;
    public static final int ERROR_ON_BLACKLIST_WHITELIST_PROCESS = 12090;
    public static final int ERROR_FEW_BLACKLIST_WHITELIST_ACTION_FAILED = 12091;
    public static final int ERROR_COMMAND_NOT_SUCCESSFUL = 12132;
    public static final int ERROR_DEVICE_ROOTED = 12204;
    public static final int ERROR_DEPROVISION_FAILES = 21003;
    public static final int DEVICE_NOT_IN_KIOSK = 70000;
    public static final int UNKNOWN_ERROR = 70010;
    
    static {
        AGENT_VERSION_CODE = 1;
    }
}
