package com.adventnet.tools.update.installer;

import com.adventnet.tools.update.CommonUtil;

public enum PatchIntegrityState
{
    PASSWORD_NOT_SUPPLIED(MessageConstants.PATCH_INTEGRITY_PASSWORD_NOT_SUPPLIED), 
    NO_PATCH_FILE(MessageConstants.PATCH_INTEGRITY_STATE_NO_PATCH_FILE), 
    NO_KEYSTORE_FILE(MessageConstants.PATCH_INTEGRITY_STATE_NO_KEYSTORE_FILE), 
    PATCH_FILE_DOES_NOT_EXIST(MessageConstants.PATCH_INTEGRITY_STATE_PATCH_FILE_DOES_NOT_EXIST), 
    NO_CERTIFICATES(MessageConstants.PATCH_INTEGRITY_STATE_NO_CERTIFICATES), 
    UNABLE_TO_PARSE_SIGNATURE_FILE(MessageConstants.PATCH_INTEGRITY_STATE_UNABLE_TO_PARSE_SIGNATURE_FILE), 
    PATCH_NOT_SIGNED(MessageConstants.PATCH_INTEGRITY_STATE_PATCH_NOT_SIGNED), 
    CONTENTS_NOT_SIGNED(MessageConstants.PATCH_INTEGRITY_STATE_CONTENTS_NOT_SIGNED), 
    CONTENTS_MODIFIED(MessageConstants.PATCH_INTEGRITY_STATE_CONTENTS_MODIFIED), 
    SIGNATURE_DOES_NOT_MATCH(MessageConstants.PATCH_INTEGRITY_STATE_SIGNATURE_DOES_NOT_MATCH), 
    CONTENTS_SIGNED_WITH_DIFFERENT_CERTIFICATE(MessageConstants.PATCH_INTEGRITY_STATE_CONTENTS_SIGNED_WITH_DIFFERENT_CERTIFICATE), 
    DIGEST_NOT_FOUND(MessageConstants.PATCH_INTEGRITY_STATE_DIGEST_NOT_FOUND), 
    EMPTY_MANIFEST(MessageConstants.PATCH_INTEGRITY_STATE_EMPTY_MANIFEST), 
    SIGNED_WITH_BLACKLISTED_CERTIFICATE(MessageConstants.PATCH_INTEGRITY_SIGNED_WITH_BLACKLISTED_CERTIFICATE), 
    SUCCESS(MessageConstants.PATCH_INTEGRITY_STATE_SUCCESS), 
    FAILURE(MessageConstants.PATCH_INTEGRITY_STATE_FAILURE);
    
    MessageConstants message;
    
    private PatchIntegrityState(final MessageConstants message) {
        this.message = message;
    }
    
    public String getMessage() {
        return CommonUtil.getString(this.message);
    }
}
