package sun.util.resources.cldr.ln;

import sun.util.resources.OpenListResourceBundle;

public class CurrencyNames_ln extends OpenListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "aed", "Diriham\u025b ya L\u00e9mila alabo" }, { "aoa", "Kwanza ya Ang\u00f3la" }, { "aud", "Dolar\u025b ya Ositali" }, { "bhd", "Dinar\u025b ya Bahr\u025bn\u025b" }, { "bif", "Fal\u00e1nga ya Burundi" }, { "bwp", "Pula ya Botswana" }, { "cad", "Dolar\u025b ya Kanad\u00e1" }, { "cdf", "Fal\u00e1nga ya Kong\u00f3" }, { "chf", "Fal\u00e1nga ya Swis\u025b" }, { "cny", "Yuan\u025b Renminbi ya Sin\u025b" }, { "cve", "Esikudo ya Kapev\u025br\u025b" }, { "djf", "Fal\u00e1nga ya Dzibuti" }, { "dzd", "Dinar\u025b ya Alizeri" }, { "egp", "Paun\u025b ya Ez\u00edpit\u025b" }, { "ern", "Nakfa ya Elitl\u025b" }, { "etb", "Bir\u025b ya Etsi\u00f3pi" }, { "eur", "\u0190l\u0254\u0301" }, { "gbp", "Paun\u025b ya Ang\u025bl\u025bt\u025b\u0301l\u025b" }, { "ghc", "Sedi ya Gana" }, { "gmd", "Dalasi ya Gambi" }, { "gns", "Fal\u00e1nga ya Gin\u025b" }, { "inr", "Rupi ya \u00cdnd\u025b" }, { "jpy", "Yeni ya Zap\u0254" }, { "kes", "Shiling\u025b ya Kenya" }, { "kmf", "Fal\u00e1nga ya Komoro" }, { "lrd", "Dolar\u025b ya Liberya" }, { "lsl", "Loti ya Les\u00f3to" }, { "lyd", "Dinar\u025b ya Lib\u00ed" }, { "mad", "Dirihame ya Marok\u025b" }, { "mga", "Fal\u00e1nga ya Madagasikar\u025b" }, { "mro", "Ugwiya ya Moritani" }, { "mur", "Rupi ya Morisi" }, { "mwk", "Kwasha ya Malawi" }, { "mzm", "Metikali ya Mozambiki" }, { "nad", "Dolar\u025b ya Namibi" }, { "ngn", "Naira ya Nizerya" }, { "rwf", "Fal\u00e1nga ya Rwanda" }, { "sar", "Riyal\u025b ya Alabi Sawudit\u025b" }, { "scr", "Rupi ya S\u025bsh\u025bl\u025b" }, { "sdg", "Dinar\u025b ya Sud\u00e1" }, { "sdp", "Paun\u025b ya Sud\u00e1" }, { "shp", "Paun\u025b ya S\u00e1ntu elena" }, { "sll", "Leon\u025b" }, { "sos", "Shiling\u025b ya Somali" }, { "std", "Dobra ya Sao Tom\u00e9 mp\u00e9 Presipe" }, { "szl", "Lilangeni" }, { "tnd", "Dinar\u025b ya Tinizi" }, { "tzs", "Shiling\u025b ya Tanzani" }, { "ugx", "Shiling\u025b ya Uganda" }, { "usd", "Dolar\u025b ya Ameriki" }, { "xaf", "Fal\u00e1nga CFA BEAC" }, { "xof", "Fal\u00e1nga CFA BCEAO" }, { "zar", "Rand\u025b ya Afr\u00edka S\u00fadi" }, { "zmk", "Kwasha ya Zambi" }, { "zwd", "Dolar\u025b ya Zimbabw\u025b" } };
    }
}
