package sun.text.resources.cldr.ms;

import java.util.ListResourceBundle;

public class FormatData_ms extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "Januari", "Februari", "Mac", "April", "Mei", "Jun", "Julai", "Ogos", "September", "Oktober", "November", "Disember", "" } }, { "MonthAbbreviations", { "Jan", "Feb", "Mac", "Apr", "Mei", "Jun", "Jul", "Ogos", "Sep", "Okt", "Nov", "Dis", "" } }, { "MonthNarrows", { "J", "F", "M", "A", "M", "J", "J", "O", "S", "O", "N", "D", "" } }, { "standalone.MonthNarrows", { "J", "F", "M", "A", "M", "J", "J", "O", "S", "O", "N", "D", "" } }, { "DayNames", { "Ahad", "Isnin", "Selasa", "Rabu", "Khamis", "Jumaat", "Sabtu" } }, { "DayAbbreviations", { "Ahd", "Isn", "Sel", "Rab", "Kha", "Jum", "Sab" } }, { "DayNarrows", { "A", "I", "S", "R", "K", "J", "S" } }, { "standalone.DayNarrows", { "A", "I", "S", "R", "K", "J", "S" } }, { "QuarterNames", { "Suku pertama", "Suku Ke-2", "Suku Ke-3", "Suku Ke-4" } }, { "standalone.QuarterNames", { "Suku pertama", "Suku Ke-2", "Suku Ke-3", "Suku Ke-4" } }, { "QuarterAbbreviations", { "Suku 1", "Suku Ke-2", "Suku Ke-3", "Suku Ke-4" } }, { "standalone.QuarterAbbreviations", { "Suku 1", "Suku Ke-2", "Suku Ke-3", "Suku Ke-4" } }, { "QuarterNarrows", { "1", "2", "3", "4" } }, { "AmPmMarkers", { "PG", "PTG" } }, { "Eras", { "S.M.", "TM" } }, { "field.year", "Tahun" }, { "field.month", "Bulan" }, { "field.week", "Minggu" }, { "field.weekday", "Hari dalam Minggu" }, { "field.dayperiod", "PG/PTG" }, { "field.hour", "Jam" }, { "field.minute", "Minit" }, { "field.second", "Kedua" }, { "field.zone", "Zon Waktu" }, { "TimePatterns", { "h:mm:ss a zzzz", "h:mm:ss a z", "h:mm:ss a", "h:mm a" } }, { "DatePatterns", { "EEEE, d MMMM y", "d MMMM y", "dd/MM/yyyy", "d/MM/yy" } }, { "java.time.buddhist.DatePatterns", { "EEEE, d MMMM y G", "d MMMM y G", "dd/MM/y G", "d/MM/y G" } }, { "buddhist.DatePatterns", { "EEEE, d MMMM y GGGG", "d MMMM y GGGG", "dd/MM/y GGGG", "d/MM/y GGGG" } }, { "java.time.japanese.DatePatterns", { "EEEE, d MMMM y G", "d MMMM y G", "dd/MM/y G", "d/MM/y G" } }, { "japanese.DatePatterns", { "EEEE, d MMMM y GGGG", "d MMMM y GGGG", "dd/MM/y GGGG", "d/MM/y GGGG" } }, { "java.time.roc.DatePatterns", { "EEEE, d MMMM y G", "d MMMM y G", "dd/MM/y G", "d/MM/y G" } }, { "roc.DatePatterns", { "EEEE, d MMMM y GGGG", "d MMMM y GGGG", "dd/MM/y GGGG", "d/MM/y GGGG" } }, { "java.time.islamic.DatePatterns", { "EEEE, d MMMM y G", "d MMMM y G", "dd/MM/y G", "d/MM/y G" } }, { "islamic.DatePatterns", { "EEEE, d MMMM y GGGG", "d MMMM y GGGG", "dd/MM/y GGGG", "d/MM/y GGGG" } }, { "calendarname.islamic-civil", "Kalendar Sivil Islam" }, { "calendarname.islamicc", "Kalendar Sivil Islam" }, { "calendarname.gregorian", "Kalendar Gregory" }, { "calendarname.gregory", "Kalendar Gregory" }, { "calendarname.japanese", "Kalendar Jepun" }, { "calendarname.buddhist", "Kalendar Buddha" }, { "calendarname.islamic", "Kalendar Islam" }, { "calendarname.roc", "Kalendar Minguo" }, { "NumberPatterns", { "#,##0.###", "¤#,##0.00;(¤#,##0.00)", "#,##0%" } } };
    }
}
