package com.adventnet.db.persistence.metadata;

import org.json.JSONException;
import java.util.Iterator;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.Collections;
import java.util.Collection;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

public class UniqueKeyDefinition implements Serializable, Cloneable
{
    private static final long serialVersionUID = -3351200294407691189L;
    private Long id;
    private boolean isAutoGenerated;
    private String name;
    private List<String> columns;
    
    protected UniqueKeyDefinition(final boolean isAutoGenerated) {
        this.id = null;
        this.isAutoGenerated = false;
        this.columns = new ArrayList<String>(1);
        this.isAutoGenerated = isAutoGenerated;
    }
    
    public UniqueKeyDefinition() {
        this.id = null;
        this.isAutoGenerated = false;
        this.columns = new ArrayList<String>(1);
    }
    
    public boolean isAutoGenerated() {
        return this.isAutoGenerated;
    }
    
    @Deprecated
    public Long getID() {
        return this.id;
    }
    
    public void setID(final Long id) {
        this.id = id;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(final String name) {
        this.name = name;
    }
    
    public Object clone() throws CloneNotSupportedException {
        final UniqueKeyDefinition copy = (UniqueKeyDefinition)super.clone();
        copy.columns = new ArrayList<String>(this.columns);
        return copy;
    }
    
    public List<String> getColumns() {
        return Collections.unmodifiableList((List<? extends String>)this.columns);
    }
    
    public void addColumn(final String columnName) {
        this.columns.add(columnName);
    }
    
    @Override
    public String toString() {
        final StringBuffer buffer = new StringBuffer("\n\t\t<UniqueKeyDefinition>");
        buffer.append("\n\t\t\t<unique-key-name>" + this.name + "</unique-key-name>");
        buffer.append("\n\t\t\t<unique-key-columns>" + this.columns + "</unique-key-columns>");
        buffer.append("\n\t\t</UniqueKeyDefinition>");
        return buffer.toString();
    }
    
    protected void renameColumn(final String oldColumnName, final String newColumnName) {
        final int columnIndex = this.columns.indexOf(oldColumnName);
        if (columnIndex > -1) {
            this.columns.set(columnIndex, newColumnName);
        }
    }
    
    public JSONObject toJSON() throws JSONException {
        final JSONObject jsonObject = new JSONObject();
        jsonObject.put("uniquekeyname", (Object)this.name);
        final JSONArray jsonArray = new JSONArray();
        for (final String column : this.columns) {
            jsonArray.put((Object)column);
        }
        jsonObject.put("uniquekeycolumns", (Object)jsonArray);
        return jsonObject;
    }
}
