package org.apache.poi.sl.draw.binding;

import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "ST_PresetColorVal")
@XmlEnum
public enum STPresetColorVal
{
    @XmlEnumValue("aliceBlue")
    ALICE_BLUE("aliceBlue"), 
    @XmlEnumValue("antiqueWhite")
    ANTIQUE_WHITE("antiqueWhite"), 
    @XmlEnumValue("aqua")
    AQUA("aqua"), 
    @XmlEnumValue("aquamarine")
    AQUAMARINE("aquamarine"), 
    @XmlEnumValue("azure")
    AZURE("azure"), 
    @XmlEnumValue("beige")
    BEIGE("beige"), 
    @XmlEnumValue("bisque")
    BISQUE("bisque"), 
    @XmlEnumValue("black")
    BLACK("black"), 
    @XmlEnumValue("blanchedAlmond")
    BLANCHED_ALMOND("blanchedAlmond"), 
    @XmlEnumValue("blue")
    BLUE("blue"), 
    @XmlEnumValue("blueViolet")
    BLUE_VIOLET("blueViolet"), 
    @XmlEnumValue("brown")
    BROWN("brown"), 
    @XmlEnumValue("burlyWood")
    BURLY_WOOD("burlyWood"), 
    @XmlEnumValue("cadetBlue")
    CADET_BLUE("cadetBlue"), 
    @XmlEnumValue("chartreuse")
    CHARTREUSE("chartreuse"), 
    @XmlEnumValue("chocolate")
    CHOCOLATE("chocolate"), 
    @XmlEnumValue("coral")
    CORAL("coral"), 
    @XmlEnumValue("cornflowerBlue")
    CORNFLOWER_BLUE("cornflowerBlue"), 
    @XmlEnumValue("cornsilk")
    CORNSILK("cornsilk"), 
    @XmlEnumValue("crimson")
    CRIMSON("crimson"), 
    @XmlEnumValue("cyan")
    CYAN("cyan"), 
    @XmlEnumValue("dkBlue")
    DK_BLUE("dkBlue"), 
    @XmlEnumValue("dkCyan")
    DK_CYAN("dkCyan"), 
    @XmlEnumValue("dkGoldenrod")
    DK_GOLDENROD("dkGoldenrod"), 
    @XmlEnumValue("dkGray")
    DK_GRAY("dkGray"), 
    @XmlEnumValue("dkGreen")
    DK_GREEN("dkGreen"), 
    @XmlEnumValue("dkKhaki")
    DK_KHAKI("dkKhaki"), 
    @XmlEnumValue("dkMagenta")
    DK_MAGENTA("dkMagenta"), 
    @XmlEnumValue("dkOliveGreen")
    DK_OLIVE_GREEN("dkOliveGreen"), 
    @XmlEnumValue("dkOrange")
    DK_ORANGE("dkOrange"), 
    @XmlEnumValue("dkOrchid")
    DK_ORCHID("dkOrchid"), 
    @XmlEnumValue("dkRed")
    DK_RED("dkRed"), 
    @XmlEnumValue("dkSalmon")
    DK_SALMON("dkSalmon"), 
    @XmlEnumValue("dkSeaGreen")
    DK_SEA_GREEN("dkSeaGreen"), 
    @XmlEnumValue("dkSlateBlue")
    DK_SLATE_BLUE("dkSlateBlue"), 
    @XmlEnumValue("dkSlateGray")
    DK_SLATE_GRAY("dkSlateGray"), 
    @XmlEnumValue("dkTurquoise")
    DK_TURQUOISE("dkTurquoise"), 
    @XmlEnumValue("dkViolet")
    DK_VIOLET("dkViolet"), 
    @XmlEnumValue("deepPink")
    DEEP_PINK("deepPink"), 
    @XmlEnumValue("deepSkyBlue")
    DEEP_SKY_BLUE("deepSkyBlue"), 
    @XmlEnumValue("dimGray")
    DIM_GRAY("dimGray"), 
    @XmlEnumValue("dodgerBlue")
    DODGER_BLUE("dodgerBlue"), 
    @XmlEnumValue("firebrick")
    FIREBRICK("firebrick"), 
    @XmlEnumValue("floralWhite")
    FLORAL_WHITE("floralWhite"), 
    @XmlEnumValue("forestGreen")
    FOREST_GREEN("forestGreen"), 
    @XmlEnumValue("fuchsia")
    FUCHSIA("fuchsia"), 
    @XmlEnumValue("gainsboro")
    GAINSBORO("gainsboro"), 
    @XmlEnumValue("ghostWhite")
    GHOST_WHITE("ghostWhite"), 
    @XmlEnumValue("gold")
    GOLD("gold"), 
    @XmlEnumValue("goldenrod")
    GOLDENROD("goldenrod"), 
    @XmlEnumValue("gray")
    GRAY("gray"), 
    @XmlEnumValue("green")
    GREEN("green"), 
    @XmlEnumValue("greenYellow")
    GREEN_YELLOW("greenYellow"), 
    @XmlEnumValue("honeydew")
    HONEYDEW("honeydew"), 
    @XmlEnumValue("hotPink")
    HOT_PINK("hotPink"), 
    @XmlEnumValue("indianRed")
    INDIAN_RED("indianRed"), 
    @XmlEnumValue("indigo")
    INDIGO("indigo"), 
    @XmlEnumValue("ivory")
    IVORY("ivory"), 
    @XmlEnumValue("khaki")
    KHAKI("khaki"), 
    @XmlEnumValue("lavender")
    LAVENDER("lavender"), 
    @XmlEnumValue("lavenderBlush")
    LAVENDER_BLUSH("lavenderBlush"), 
    @XmlEnumValue("lawnGreen")
    LAWN_GREEN("lawnGreen"), 
    @XmlEnumValue("lemonChiffon")
    LEMON_CHIFFON("lemonChiffon"), 
    @XmlEnumValue("ltBlue")
    LT_BLUE("ltBlue"), 
    @XmlEnumValue("ltCoral")
    LT_CORAL("ltCoral"), 
    @XmlEnumValue("ltCyan")
    LT_CYAN("ltCyan"), 
    @XmlEnumValue("ltGoldenrodYellow")
    LT_GOLDENROD_YELLOW("ltGoldenrodYellow"), 
    @XmlEnumValue("ltGray")
    LT_GRAY("ltGray"), 
    @XmlEnumValue("ltGreen")
    LT_GREEN("ltGreen"), 
    @XmlEnumValue("ltPink")
    LT_PINK("ltPink"), 
    @XmlEnumValue("ltSalmon")
    LT_SALMON("ltSalmon"), 
    @XmlEnumValue("ltSeaGreen")
    LT_SEA_GREEN("ltSeaGreen"), 
    @XmlEnumValue("ltSkyBlue")
    LT_SKY_BLUE("ltSkyBlue"), 
    @XmlEnumValue("ltSlateGray")
    LT_SLATE_GRAY("ltSlateGray"), 
    @XmlEnumValue("ltSteelBlue")
    LT_STEEL_BLUE("ltSteelBlue"), 
    @XmlEnumValue("ltYellow")
    LT_YELLOW("ltYellow"), 
    @XmlEnumValue("lime")
    LIME("lime"), 
    @XmlEnumValue("limeGreen")
    LIME_GREEN("limeGreen"), 
    @XmlEnumValue("linen")
    LINEN("linen"), 
    @XmlEnumValue("magenta")
    MAGENTA("magenta"), 
    @XmlEnumValue("maroon")
    MAROON("maroon"), 
    @XmlEnumValue("medAquamarine")
    MED_AQUAMARINE("medAquamarine"), 
    @XmlEnumValue("medBlue")
    MED_BLUE("medBlue"), 
    @XmlEnumValue("medOrchid")
    MED_ORCHID("medOrchid"), 
    @XmlEnumValue("medPurple")
    MED_PURPLE("medPurple"), 
    @XmlEnumValue("medSeaGreen")
    MED_SEA_GREEN("medSeaGreen"), 
    @XmlEnumValue("medSlateBlue")
    MED_SLATE_BLUE("medSlateBlue"), 
    @XmlEnumValue("medSpringGreen")
    MED_SPRING_GREEN("medSpringGreen"), 
    @XmlEnumValue("medTurquoise")
    MED_TURQUOISE("medTurquoise"), 
    @XmlEnumValue("medVioletRed")
    MED_VIOLET_RED("medVioletRed"), 
    @XmlEnumValue("midnightBlue")
    MIDNIGHT_BLUE("midnightBlue"), 
    @XmlEnumValue("mintCream")
    MINT_CREAM("mintCream"), 
    @XmlEnumValue("mistyRose")
    MISTY_ROSE("mistyRose"), 
    @XmlEnumValue("moccasin")
    MOCCASIN("moccasin"), 
    @XmlEnumValue("navajoWhite")
    NAVAJO_WHITE("navajoWhite"), 
    @XmlEnumValue("navy")
    NAVY("navy"), 
    @XmlEnumValue("oldLace")
    OLD_LACE("oldLace"), 
    @XmlEnumValue("olive")
    OLIVE("olive"), 
    @XmlEnumValue("oliveDrab")
    OLIVE_DRAB("oliveDrab"), 
    @XmlEnumValue("orange")
    ORANGE("orange"), 
    @XmlEnumValue("orangeRed")
    ORANGE_RED("orangeRed"), 
    @XmlEnumValue("orchid")
    ORCHID("orchid"), 
    @XmlEnumValue("paleGoldenrod")
    PALE_GOLDENROD("paleGoldenrod"), 
    @XmlEnumValue("paleGreen")
    PALE_GREEN("paleGreen"), 
    @XmlEnumValue("paleTurquoise")
    PALE_TURQUOISE("paleTurquoise"), 
    @XmlEnumValue("paleVioletRed")
    PALE_VIOLET_RED("paleVioletRed"), 
    @XmlEnumValue("papayaWhip")
    PAPAYA_WHIP("papayaWhip"), 
    @XmlEnumValue("peachPuff")
    PEACH_PUFF("peachPuff"), 
    @XmlEnumValue("peru")
    PERU("peru"), 
    @XmlEnumValue("pink")
    PINK("pink"), 
    @XmlEnumValue("plum")
    PLUM("plum"), 
    @XmlEnumValue("powderBlue")
    POWDER_BLUE("powderBlue"), 
    @XmlEnumValue("purple")
    PURPLE("purple"), 
    @XmlEnumValue("red")
    RED("red"), 
    @XmlEnumValue("rosyBrown")
    ROSY_BROWN("rosyBrown"), 
    @XmlEnumValue("royalBlue")
    ROYAL_BLUE("royalBlue"), 
    @XmlEnumValue("saddleBrown")
    SADDLE_BROWN("saddleBrown"), 
    @XmlEnumValue("salmon")
    SALMON("salmon"), 
    @XmlEnumValue("sandyBrown")
    SANDY_BROWN("sandyBrown"), 
    @XmlEnumValue("seaGreen")
    SEA_GREEN("seaGreen"), 
    @XmlEnumValue("seaShell")
    SEA_SHELL("seaShell"), 
    @XmlEnumValue("sienna")
    SIENNA("sienna"), 
    @XmlEnumValue("silver")
    SILVER("silver"), 
    @XmlEnumValue("skyBlue")
    SKY_BLUE("skyBlue"), 
    @XmlEnumValue("slateBlue")
    SLATE_BLUE("slateBlue"), 
    @XmlEnumValue("slateGray")
    SLATE_GRAY("slateGray"), 
    @XmlEnumValue("snow")
    SNOW("snow"), 
    @XmlEnumValue("springGreen")
    SPRING_GREEN("springGreen"), 
    @XmlEnumValue("steelBlue")
    STEEL_BLUE("steelBlue"), 
    @XmlEnumValue("tan")
    TAN("tan"), 
    @XmlEnumValue("teal")
    TEAL("teal"), 
    @XmlEnumValue("thistle")
    THISTLE("thistle"), 
    @XmlEnumValue("tomato")
    TOMATO("tomato"), 
    @XmlEnumValue("turquoise")
    TURQUOISE("turquoise"), 
    @XmlEnumValue("violet")
    VIOLET("violet"), 
    @XmlEnumValue("wheat")
    WHEAT("wheat"), 
    @XmlEnumValue("white")
    WHITE("white"), 
    @XmlEnumValue("whiteSmoke")
    WHITE_SMOKE("whiteSmoke"), 
    @XmlEnumValue("yellow")
    YELLOW("yellow"), 
    @XmlEnumValue("yellowGreen")
    YELLOW_GREEN("yellowGreen");
    
    private final String value;
    
    private STPresetColorVal(final String v) {
        this.value = v;
    }
    
    public String value() {
        return this.value;
    }
    
    public static STPresetColorVal fromValue(final String v) {
        for (final STPresetColorVal c : values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
