package org.apache.poi.sl.draw.binding;

import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "ST_ShapeType")
@XmlEnum
public enum STShapeType
{
    @XmlEnumValue("line")
    LINE("line"), 
    @XmlEnumValue("lineInv")
    LINE_INV("lineInv"), 
    @XmlEnumValue("triangle")
    TRIANGLE("triangle"), 
    @XmlEnumValue("rtTriangle")
    RT_TRIANGLE("rtTriangle"), 
    @XmlEnumValue("rect")
    RECT("rect"), 
    @XmlEnumValue("diamond")
    DIAMOND("diamond"), 
    @XmlEnumValue("parallelogram")
    PARALLELOGRAM("parallelogram"), 
    @XmlEnumValue("trapezoid")
    TRAPEZOID("trapezoid"), 
    @XmlEnumValue("nonIsoscelesTrapezoid")
    NON_ISOSCELES_TRAPEZOID("nonIsoscelesTrapezoid"), 
    @XmlEnumValue("pentagon")
    PENTAGON("pentagon"), 
    @XmlEnumValue("hexagon")
    HEXAGON("hexagon"), 
    @XmlEnumValue("heptagon")
    HEPTAGON("heptagon"), 
    @XmlEnumValue("octagon")
    OCTAGON("octagon"), 
    @XmlEnumValue("decagon")
    DECAGON("decagon"), 
    @XmlEnumValue("dodecagon")
    DODECAGON("dodecagon"), 
    @XmlEnumValue("star4")
    STAR_4("star4"), 
    @XmlEnumValue("star5")
    STAR_5("star5"), 
    @XmlEnumValue("star6")
    STAR_6("star6"), 
    @XmlEnumValue("star7")
    STAR_7("star7"), 
    @XmlEnumValue("star8")
    STAR_8("star8"), 
    @XmlEnumValue("star10")
    STAR_10("star10"), 
    @XmlEnumValue("star12")
    STAR_12("star12"), 
    @XmlEnumValue("star16")
    STAR_16("star16"), 
    @XmlEnumValue("star24")
    STAR_24("star24"), 
    @XmlEnumValue("star32")
    STAR_32("star32"), 
    @XmlEnumValue("roundRect")
    ROUND_RECT("roundRect"), 
    @XmlEnumValue("round1Rect")
    ROUND_1_RECT("round1Rect"), 
    @XmlEnumValue("round2SameRect")
    ROUND_2_SAME_RECT("round2SameRect"), 
    @XmlEnumValue("round2DiagRect")
    ROUND_2_DIAG_RECT("round2DiagRect"), 
    @XmlEnumValue("snipRoundRect")
    SNIP_ROUND_RECT("snipRoundRect"), 
    @XmlEnumValue("snip1Rect")
    SNIP_1_RECT("snip1Rect"), 
    @XmlEnumValue("snip2SameRect")
    SNIP_2_SAME_RECT("snip2SameRect"), 
    @XmlEnumValue("snip2DiagRect")
    SNIP_2_DIAG_RECT("snip2DiagRect"), 
    @XmlEnumValue("plaque")
    PLAQUE("plaque"), 
    @XmlEnumValue("ellipse")
    ELLIPSE("ellipse"), 
    @XmlEnumValue("teardrop")
    TEARDROP("teardrop"), 
    @XmlEnumValue("homePlate")
    HOME_PLATE("homePlate"), 
    @XmlEnumValue("chevron")
    CHEVRON("chevron"), 
    @XmlEnumValue("pieWedge")
    PIE_WEDGE("pieWedge"), 
    @XmlEnumValue("pie")
    PIE("pie"), 
    @XmlEnumValue("blockArc")
    BLOCK_ARC("blockArc"), 
    @XmlEnumValue("donut")
    DONUT("donut"), 
    @XmlEnumValue("noSmoking")
    NO_SMOKING("noSmoking"), 
    @XmlEnumValue("rightArrow")
    RIGHT_ARROW("rightArrow"), 
    @XmlEnumValue("leftArrow")
    LEFT_ARROW("leftArrow"), 
    @XmlEnumValue("upArrow")
    UP_ARROW("upArrow"), 
    @XmlEnumValue("downArrow")
    DOWN_ARROW("downArrow"), 
    @XmlEnumValue("stripedRightArrow")
    STRIPED_RIGHT_ARROW("stripedRightArrow"), 
    @XmlEnumValue("notchedRightArrow")
    NOTCHED_RIGHT_ARROW("notchedRightArrow"), 
    @XmlEnumValue("bentUpArrow")
    BENT_UP_ARROW("bentUpArrow"), 
    @XmlEnumValue("leftRightArrow")
    LEFT_RIGHT_ARROW("leftRightArrow"), 
    @XmlEnumValue("upDownArrow")
    UP_DOWN_ARROW("upDownArrow"), 
    @XmlEnumValue("leftUpArrow")
    LEFT_UP_ARROW("leftUpArrow"), 
    @XmlEnumValue("leftRightUpArrow")
    LEFT_RIGHT_UP_ARROW("leftRightUpArrow"), 
    @XmlEnumValue("quadArrow")
    QUAD_ARROW("quadArrow"), 
    @XmlEnumValue("leftArrowCallout")
    LEFT_ARROW_CALLOUT("leftArrowCallout"), 
    @XmlEnumValue("rightArrowCallout")
    RIGHT_ARROW_CALLOUT("rightArrowCallout"), 
    @XmlEnumValue("upArrowCallout")
    UP_ARROW_CALLOUT("upArrowCallout"), 
    @XmlEnumValue("downArrowCallout")
    DOWN_ARROW_CALLOUT("downArrowCallout"), 
    @XmlEnumValue("leftRightArrowCallout")
    LEFT_RIGHT_ARROW_CALLOUT("leftRightArrowCallout"), 
    @XmlEnumValue("upDownArrowCallout")
    UP_DOWN_ARROW_CALLOUT("upDownArrowCallout"), 
    @XmlEnumValue("quadArrowCallout")
    QUAD_ARROW_CALLOUT("quadArrowCallout"), 
    @XmlEnumValue("bentArrow")
    BENT_ARROW("bentArrow"), 
    @XmlEnumValue("uturnArrow")
    UTURN_ARROW("uturnArrow"), 
    @XmlEnumValue("circularArrow")
    CIRCULAR_ARROW("circularArrow"), 
    @XmlEnumValue("leftCircularArrow")
    LEFT_CIRCULAR_ARROW("leftCircularArrow"), 
    @XmlEnumValue("leftRightCircularArrow")
    LEFT_RIGHT_CIRCULAR_ARROW("leftRightCircularArrow"), 
    @XmlEnumValue("curvedRightArrow")
    CURVED_RIGHT_ARROW("curvedRightArrow"), 
    @XmlEnumValue("curvedLeftArrow")
    CURVED_LEFT_ARROW("curvedLeftArrow"), 
    @XmlEnumValue("curvedUpArrow")
    CURVED_UP_ARROW("curvedUpArrow"), 
    @XmlEnumValue("curvedDownArrow")
    CURVED_DOWN_ARROW("curvedDownArrow"), 
    @XmlEnumValue("swooshArrow")
    SWOOSH_ARROW("swooshArrow"), 
    @XmlEnumValue("cube")
    CUBE("cube"), 
    @XmlEnumValue("can")
    CAN("can"), 
    @XmlEnumValue("lightningBolt")
    LIGHTNING_BOLT("lightningBolt"), 
    @XmlEnumValue("heart")
    HEART("heart"), 
    @XmlEnumValue("sun")
    SUN("sun"), 
    @XmlEnumValue("moon")
    MOON("moon"), 
    @XmlEnumValue("smileyFace")
    SMILEY_FACE("smileyFace"), 
    @XmlEnumValue("irregularSeal1")
    IRREGULAR_SEAL_1("irregularSeal1"), 
    @XmlEnumValue("irregularSeal2")
    IRREGULAR_SEAL_2("irregularSeal2"), 
    @XmlEnumValue("foldedCorner")
    FOLDED_CORNER("foldedCorner"), 
    @XmlEnumValue("bevel")
    BEVEL("bevel"), 
    @XmlEnumValue("frame")
    FRAME("frame"), 
    @XmlEnumValue("halfFrame")
    HALF_FRAME("halfFrame"), 
    @XmlEnumValue("corner")
    CORNER("corner"), 
    @XmlEnumValue("diagStripe")
    DIAG_STRIPE("diagStripe"), 
    @XmlEnumValue("chord")
    CHORD("chord"), 
    @XmlEnumValue("arc")
    ARC("arc"), 
    @XmlEnumValue("leftBracket")
    LEFT_BRACKET("leftBracket"), 
    @XmlEnumValue("rightBracket")
    RIGHT_BRACKET("rightBracket"), 
    @XmlEnumValue("leftBrace")
    LEFT_BRACE("leftBrace"), 
    @XmlEnumValue("rightBrace")
    RIGHT_BRACE("rightBrace"), 
    @XmlEnumValue("bracketPair")
    BRACKET_PAIR("bracketPair"), 
    @XmlEnumValue("bracePair")
    BRACE_PAIR("bracePair"), 
    @XmlEnumValue("straightConnector1")
    STRAIGHT_CONNECTOR_1("straightConnector1"), 
    @XmlEnumValue("bentConnector2")
    BENT_CONNECTOR_2("bentConnector2"), 
    @XmlEnumValue("bentConnector3")
    BENT_CONNECTOR_3("bentConnector3"), 
    @XmlEnumValue("bentConnector4")
    BENT_CONNECTOR_4("bentConnector4"), 
    @XmlEnumValue("bentConnector5")
    BENT_CONNECTOR_5("bentConnector5"), 
    @XmlEnumValue("curvedConnector2")
    CURVED_CONNECTOR_2("curvedConnector2"), 
    @XmlEnumValue("curvedConnector3")
    CURVED_CONNECTOR_3("curvedConnector3"), 
    @XmlEnumValue("curvedConnector4")
    CURVED_CONNECTOR_4("curvedConnector4"), 
    @XmlEnumValue("curvedConnector5")
    CURVED_CONNECTOR_5("curvedConnector5"), 
    @XmlEnumValue("callout1")
    CALLOUT_1("callout1"), 
    @XmlEnumValue("callout2")
    CALLOUT_2("callout2"), 
    @XmlEnumValue("callout3")
    CALLOUT_3("callout3"), 
    @XmlEnumValue("accentCallout1")
    ACCENT_CALLOUT_1("accentCallout1"), 
    @XmlEnumValue("accentCallout2")
    ACCENT_CALLOUT_2("accentCallout2"), 
    @XmlEnumValue("accentCallout3")
    ACCENT_CALLOUT_3("accentCallout3"), 
    @XmlEnumValue("borderCallout1")
    BORDER_CALLOUT_1("borderCallout1"), 
    @XmlEnumValue("borderCallout2")
    BORDER_CALLOUT_2("borderCallout2"), 
    @XmlEnumValue("borderCallout3")
    BORDER_CALLOUT_3("borderCallout3"), 
    @XmlEnumValue("accentBorderCallout1")
    ACCENT_BORDER_CALLOUT_1("accentBorderCallout1"), 
    @XmlEnumValue("accentBorderCallout2")
    ACCENT_BORDER_CALLOUT_2("accentBorderCallout2"), 
    @XmlEnumValue("accentBorderCallout3")
    ACCENT_BORDER_CALLOUT_3("accentBorderCallout3"), 
    @XmlEnumValue("wedgeRectCallout")
    WEDGE_RECT_CALLOUT("wedgeRectCallout"), 
    @XmlEnumValue("wedgeRoundRectCallout")
    WEDGE_ROUND_RECT_CALLOUT("wedgeRoundRectCallout"), 
    @XmlEnumValue("wedgeEllipseCallout")
    WEDGE_ELLIPSE_CALLOUT("wedgeEllipseCallout"), 
    @XmlEnumValue("cloudCallout")
    CLOUD_CALLOUT("cloudCallout"), 
    @XmlEnumValue("cloud")
    CLOUD("cloud"), 
    @XmlEnumValue("ribbon")
    RIBBON("ribbon"), 
    @XmlEnumValue("ribbon2")
    RIBBON_2("ribbon2"), 
    @XmlEnumValue("ellipseRibbon")
    ELLIPSE_RIBBON("ellipseRibbon"), 
    @XmlEnumValue("ellipseRibbon2")
    ELLIPSE_RIBBON_2("ellipseRibbon2"), 
    @XmlEnumValue("leftRightRibbon")
    LEFT_RIGHT_RIBBON("leftRightRibbon"), 
    @XmlEnumValue("verticalScroll")
    VERTICAL_SCROLL("verticalScroll"), 
    @XmlEnumValue("horizontalScroll")
    HORIZONTAL_SCROLL("horizontalScroll"), 
    @XmlEnumValue("wave")
    WAVE("wave"), 
    @XmlEnumValue("doubleWave")
    DOUBLE_WAVE("doubleWave"), 
    @XmlEnumValue("plus")
    PLUS("plus"), 
    @XmlEnumValue("flowChartProcess")
    FLOW_CHART_PROCESS("flowChartProcess"), 
    @XmlEnumValue("flowChartDecision")
    FLOW_CHART_DECISION("flowChartDecision"), 
    @XmlEnumValue("flowChartInputOutput")
    FLOW_CHART_INPUT_OUTPUT("flowChartInputOutput"), 
    @XmlEnumValue("flowChartPredefinedProcess")
    FLOW_CHART_PREDEFINED_PROCESS("flowChartPredefinedProcess"), 
    @XmlEnumValue("flowChartInternalStorage")
    FLOW_CHART_INTERNAL_STORAGE("flowChartInternalStorage"), 
    @XmlEnumValue("flowChartDocument")
    FLOW_CHART_DOCUMENT("flowChartDocument"), 
    @XmlEnumValue("flowChartMultidocument")
    FLOW_CHART_MULTIDOCUMENT("flowChartMultidocument"), 
    @XmlEnumValue("flowChartTerminator")
    FLOW_CHART_TERMINATOR("flowChartTerminator"), 
    @XmlEnumValue("flowChartPreparation")
    FLOW_CHART_PREPARATION("flowChartPreparation"), 
    @XmlEnumValue("flowChartManualInput")
    FLOW_CHART_MANUAL_INPUT("flowChartManualInput"), 
    @XmlEnumValue("flowChartManualOperation")
    FLOW_CHART_MANUAL_OPERATION("flowChartManualOperation"), 
    @XmlEnumValue("flowChartConnector")
    FLOW_CHART_CONNECTOR("flowChartConnector"), 
    @XmlEnumValue("flowChartPunchedCard")
    FLOW_CHART_PUNCHED_CARD("flowChartPunchedCard"), 
    @XmlEnumValue("flowChartPunchedTape")
    FLOW_CHART_PUNCHED_TAPE("flowChartPunchedTape"), 
    @XmlEnumValue("flowChartSummingJunction")
    FLOW_CHART_SUMMING_JUNCTION("flowChartSummingJunction"), 
    @XmlEnumValue("flowChartOr")
    FLOW_CHART_OR("flowChartOr"), 
    @XmlEnumValue("flowChartCollate")
    FLOW_CHART_COLLATE("flowChartCollate"), 
    @XmlEnumValue("flowChartSort")
    FLOW_CHART_SORT("flowChartSort"), 
    @XmlEnumValue("flowChartExtract")
    FLOW_CHART_EXTRACT("flowChartExtract"), 
    @XmlEnumValue("flowChartMerge")
    FLOW_CHART_MERGE("flowChartMerge"), 
    @XmlEnumValue("flowChartOfflineStorage")
    FLOW_CHART_OFFLINE_STORAGE("flowChartOfflineStorage"), 
    @XmlEnumValue("flowChartOnlineStorage")
    FLOW_CHART_ONLINE_STORAGE("flowChartOnlineStorage"), 
    @XmlEnumValue("flowChartMagneticTape")
    FLOW_CHART_MAGNETIC_TAPE("flowChartMagneticTape"), 
    @XmlEnumValue("flowChartMagneticDisk")
    FLOW_CHART_MAGNETIC_DISK("flowChartMagneticDisk"), 
    @XmlEnumValue("flowChartMagneticDrum")
    FLOW_CHART_MAGNETIC_DRUM("flowChartMagneticDrum"), 
    @XmlEnumValue("flowChartDisplay")
    FLOW_CHART_DISPLAY("flowChartDisplay"), 
    @XmlEnumValue("flowChartDelay")
    FLOW_CHART_DELAY("flowChartDelay"), 
    @XmlEnumValue("flowChartAlternateProcess")
    FLOW_CHART_ALTERNATE_PROCESS("flowChartAlternateProcess"), 
    @XmlEnumValue("flowChartOffpageConnector")
    FLOW_CHART_OFFPAGE_CONNECTOR("flowChartOffpageConnector"), 
    @XmlEnumValue("actionButtonBlank")
    ACTION_BUTTON_BLANK("actionButtonBlank"), 
    @XmlEnumValue("actionButtonHome")
    ACTION_BUTTON_HOME("actionButtonHome"), 
    @XmlEnumValue("actionButtonHelp")
    ACTION_BUTTON_HELP("actionButtonHelp"), 
    @XmlEnumValue("actionButtonInformation")
    ACTION_BUTTON_INFORMATION("actionButtonInformation"), 
    @XmlEnumValue("actionButtonForwardNext")
    ACTION_BUTTON_FORWARD_NEXT("actionButtonForwardNext"), 
    @XmlEnumValue("actionButtonBackPrevious")
    ACTION_BUTTON_BACK_PREVIOUS("actionButtonBackPrevious"), 
    @XmlEnumValue("actionButtonEnd")
    ACTION_BUTTON_END("actionButtonEnd"), 
    @XmlEnumValue("actionButtonBeginning")
    ACTION_BUTTON_BEGINNING("actionButtonBeginning"), 
    @XmlEnumValue("actionButtonReturn")
    ACTION_BUTTON_RETURN("actionButtonReturn"), 
    @XmlEnumValue("actionButtonDocument")
    ACTION_BUTTON_DOCUMENT("actionButtonDocument"), 
    @XmlEnumValue("actionButtonSound")
    ACTION_BUTTON_SOUND("actionButtonSound"), 
    @XmlEnumValue("actionButtonMovie")
    ACTION_BUTTON_MOVIE("actionButtonMovie"), 
    @XmlEnumValue("gear6")
    GEAR_6("gear6"), 
    @XmlEnumValue("gear9")
    GEAR_9("gear9"), 
    @XmlEnumValue("funnel")
    FUNNEL("funnel"), 
    @XmlEnumValue("mathPlus")
    MATH_PLUS("mathPlus"), 
    @XmlEnumValue("mathMinus")
    MATH_MINUS("mathMinus"), 
    @XmlEnumValue("mathMultiply")
    MATH_MULTIPLY("mathMultiply"), 
    @XmlEnumValue("mathDivide")
    MATH_DIVIDE("mathDivide"), 
    @XmlEnumValue("mathEqual")
    MATH_EQUAL("mathEqual"), 
    @XmlEnumValue("mathNotEqual")
    MATH_NOT_EQUAL("mathNotEqual"), 
    @XmlEnumValue("cornerTabs")
    CORNER_TABS("cornerTabs"), 
    @XmlEnumValue("squareTabs")
    SQUARE_TABS("squareTabs"), 
    @XmlEnumValue("plaqueTabs")
    PLAQUE_TABS("plaqueTabs"), 
    @XmlEnumValue("chartX")
    CHART_X("chartX"), 
    @XmlEnumValue("chartStar")
    CHART_STAR("chartStar"), 
    @XmlEnumValue("chartPlus")
    CHART_PLUS("chartPlus");
    
    private final String value;
    
    private STShapeType(final String v) {
        this.value = v;
    }
    
    public String value() {
        return this.value;
    }
    
    public static STShapeType fromValue(final String v) {
        for (final STShapeType c : values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
