package sun.text.resources.cldr.zu;

import java.util.ListResourceBundle;

public class FormatData_zu extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "Januwari", "Februwari", "Mashi", "Apreli", "Meyi", "Juni", "Julayi", "Agasti", "Septhemba", "Okthoba", "Novemba", "Disemba", "" } }, { "standalone.MonthNames", { "uJanuwari", "uFebruwari", "uMashi", "u-Apreli", "uMeyi", "uJuni", "uJulayi", "uAgasti", "uSepthemba", "u-Okthoba", "uNovemba", "uDisemba", "" } }, { "MonthAbbreviations", { "Jan", "Feb", "Mas", "Apr", "Mey", "Jun", "Jul", "Aga", "Sep", "Okt", "Nov", "Dis", "" } }, { "MonthNarrows", { "J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D", "" } }, { "DayNames", { "Sonto", "Msombuluko", "Lwesibili", "Lwesithathu", "uLwesine", "Lwesihlanu", "Mgqibelo" } }, { "DayAbbreviations", { "Son", "Mso", "Bil", "Tha", "Sin", "Hla", "Mgq" } }, { "DayNarrows", { "S", "M", "B", "T", "S", "H", "M" } }, { "QuarterNames", { "ikota yoku-1", "ikota yesi-2", "ikota yesi-3", "ikota yesi-4" } }, { "standalone.QuarterNames", { "ikota yoku-1", "ikota yesi-2", "ikota yesi-3", "ikota yesi-4" } }, { "QuarterAbbreviations", { "Q1", "Q2", "Q3", "Q4" } }, { "standalone.QuarterAbbreviations", { "Q1", "Q2", "Q3", "Q4" } }, { "QuarterNarrows", { "1", "2", "3", "4" } }, { "narrow.AmPmMarkers", { "a", "p" } }, { "Eras", { "BC", "AD" } }, { "field.era", "Isikhathi" }, { "field.year", "Unyaka" }, { "field.month", "Inyanga" }, { "field.week", "Iviki" }, { "field.weekday", "Usuku evikini" }, { "field.dayperiod", "AM/PM" }, { "field.hour", "Ihora" }, { "field.minute", "Iminithi" }, { "field.second", "Isekhondi" }, { "field.zone", "Isikhathi sendawo" }, { "TimePatterns", { "h:mm:ss a zzzz", "h:mm:ss a z", "h:mm:ss a", "h:mm a" } }, { "DatePatterns", { "EEEE dd MMMM y", "d MMMM y", "d MMM y", "yyyy-MM-dd" } }, { "calendarname.islamic-civil", "i-Islamic-Civil Calendar" }, { "calendarname.islamicc", "i-Islamic-Civil Calendar" }, { "calendarname.gregorian", "i-Gregorian Calender" }, { "calendarname.gregory", "i-Gregorian Calender" }, { "calendarname.japanese", "i-Japanese Calendar" }, { "calendarname.buddhist", "i-Buddhist Calender" }, { "calendarname.islamic", "i-Islamic Calender" }, { "calendarname.roc", "i-Minguo Calender" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ",", " ", ";", "%", "0", "#", "-", "E", "\u2030", "\u221e", "NaN" } }, { "NumberPatterns", { "#,##0.###", "¤#,##0.00", "#,##0%" } } };
    }
}
