package com.unboundid.asn1;

import com.unboundid.util.ThreadSafetyLevel;
import com.unboundid.util.ThreadSafety;
import com.unboundid.util.InternalUseOnly;

@InternalUseOnly
@ThreadSafety(level = ThreadSafetyLevel.COMPLETELY_THREADSAFE)
public final class ASN1Constants
{
    static final ASN1Element[] NO_ELEMENTS;
    static final byte[] BOOLEAN_VALUE_FALSE;
    static final byte[] BOOLEAN_VALUE_TRUE;
    static final byte[] LENGTH_0;
    static final byte[] LENGTH_1;
    static final byte[] LENGTH_2;
    static final byte[] LENGTH_3;
    static final byte[] LENGTH_4;
    static final byte[] LENGTH_5;
    static final byte[] LENGTH_6;
    static final byte[] LENGTH_7;
    static final byte[] LENGTH_8;
    static final byte[] LENGTH_9;
    static final byte[] LENGTH_10;
    static final byte[] LENGTH_11;
    static final byte[] LENGTH_12;
    static final byte[] LENGTH_13;
    static final byte[] LENGTH_14;
    static final byte[] LENGTH_15;
    static final byte[] LENGTH_16;
    static final byte[] LENGTH_17;
    static final byte[] LENGTH_18;
    static final byte[] LENGTH_19;
    static final byte[] LENGTH_20;
    static final byte[] LENGTH_21;
    static final byte[] LENGTH_22;
    static final byte[] LENGTH_23;
    static final byte[] LENGTH_24;
    static final byte[] LENGTH_25;
    static final byte[] LENGTH_26;
    static final byte[] LENGTH_27;
    static final byte[] LENGTH_28;
    static final byte[] LENGTH_29;
    static final byte[] LENGTH_30;
    static final byte[] LENGTH_31;
    static final byte[] LENGTH_32;
    static final byte[] LENGTH_33;
    static final byte[] LENGTH_34;
    static final byte[] LENGTH_35;
    static final byte[] LENGTH_36;
    static final byte[] LENGTH_37;
    static final byte[] LENGTH_38;
    static final byte[] LENGTH_39;
    static final byte[] LENGTH_40;
    static final byte[] LENGTH_41;
    static final byte[] LENGTH_42;
    static final byte[] LENGTH_43;
    static final byte[] LENGTH_44;
    static final byte[] LENGTH_45;
    static final byte[] LENGTH_46;
    static final byte[] LENGTH_47;
    static final byte[] LENGTH_48;
    static final byte[] LENGTH_49;
    static final byte[] LENGTH_50;
    static final byte[] LENGTH_51;
    static final byte[] LENGTH_52;
    static final byte[] LENGTH_53;
    static final byte[] LENGTH_54;
    static final byte[] LENGTH_55;
    static final byte[] LENGTH_56;
    static final byte[] LENGTH_57;
    static final byte[] LENGTH_58;
    static final byte[] LENGTH_59;
    static final byte[] LENGTH_60;
    static final byte[] LENGTH_61;
    static final byte[] LENGTH_62;
    static final byte[] LENGTH_63;
    static final byte[] LENGTH_64;
    static final byte[] LENGTH_65;
    static final byte[] LENGTH_66;
    static final byte[] LENGTH_67;
    static final byte[] LENGTH_68;
    static final byte[] LENGTH_69;
    static final byte[] LENGTH_70;
    static final byte[] LENGTH_71;
    static final byte[] LENGTH_72;
    static final byte[] LENGTH_73;
    static final byte[] LENGTH_74;
    static final byte[] LENGTH_75;
    static final byte[] LENGTH_76;
    static final byte[] LENGTH_77;
    static final byte[] LENGTH_78;
    static final byte[] LENGTH_79;
    static final byte[] LENGTH_80;
    static final byte[] LENGTH_81;
    static final byte[] LENGTH_82;
    static final byte[] LENGTH_83;
    static final byte[] LENGTH_84;
    static final byte[] LENGTH_85;
    static final byte[] LENGTH_86;
    static final byte[] LENGTH_87;
    static final byte[] LENGTH_88;
    static final byte[] LENGTH_89;
    static final byte[] LENGTH_90;
    static final byte[] LENGTH_91;
    static final byte[] LENGTH_92;
    static final byte[] LENGTH_93;
    static final byte[] LENGTH_94;
    static final byte[] LENGTH_95;
    static final byte[] LENGTH_96;
    static final byte[] LENGTH_97;
    static final byte[] LENGTH_98;
    static final byte[] LENGTH_99;
    static final byte[] LENGTH_100;
    static final byte[] LENGTH_101;
    static final byte[] LENGTH_102;
    static final byte[] LENGTH_103;
    static final byte[] LENGTH_104;
    static final byte[] LENGTH_105;
    static final byte[] LENGTH_106;
    static final byte[] LENGTH_107;
    static final byte[] LENGTH_108;
    static final byte[] LENGTH_109;
    static final byte[] LENGTH_110;
    static final byte[] LENGTH_111;
    static final byte[] LENGTH_112;
    static final byte[] LENGTH_113;
    static final byte[] LENGTH_114;
    static final byte[] LENGTH_115;
    static final byte[] LENGTH_116;
    static final byte[] LENGTH_117;
    static final byte[] LENGTH_118;
    static final byte[] LENGTH_119;
    static final byte[] LENGTH_120;
    static final byte[] LENGTH_121;
    static final byte[] LENGTH_122;
    static final byte[] LENGTH_123;
    static final byte[] LENGTH_124;
    static final byte[] LENGTH_125;
    static final byte[] LENGTH_126;
    static final byte[] LENGTH_127;
    public static final byte UNIVERSAL_BOOLEAN_TYPE = 1;
    public static final byte UNIVERSAL_INTEGER_TYPE = 2;
    public static final byte UNIVERSAL_BIT_STRING_TYPE = 3;
    public static final byte UNIVERSAL_OCTET_STRING_TYPE = 4;
    public static final byte UNIVERSAL_NULL_TYPE = 5;
    public static final byte UNIVERSAL_OBJECT_IDENTIFIER_TYPE = 6;
    public static final byte UNIVERSAL_ENUMERATED_TYPE = 10;
    public static final byte UNIVERSAL_UTF_8_STRING_TYPE = 12;
    public static final byte UNIVERSAL_NUMERIC_STRING_TYPE = 18;
    public static final byte UNIVERSAL_PRINTABLE_STRING_TYPE = 19;
    public static final byte UNIVERSAL_IA5_STRING_TYPE = 22;
    public static final byte UNIVERSAL_UTC_TIME_TYPE = 23;
    public static final byte UNIVERSAL_GENERALIZED_TIME_TYPE = 24;
    public static final byte UNIVERSAL_SEQUENCE_TYPE = 48;
    public static final byte UNIVERSAL_SET_TYPE = 49;
    public static final byte[] NO_VALUE;
    public static final byte TYPE_MASK_UNIVERSAL_CLASS = 0;
    @Deprecated
    public static final byte TYE_MASK_UNIVERSAL_CLASS = 0;
    public static final byte TYPE_MASK_APPLICATION_CLASS = 64;
    @Deprecated
    public static final byte TYE_MASK_APPLICATION_CLASS = 64;
    public static final byte TYPE_MASK_CONTEXT_SPECIFIC_CLASS = Byte.MIN_VALUE;
    @Deprecated
    public static final byte TYE_MASK_CONTEXT_SPECIFIC_CLASS = Byte.MIN_VALUE;
    public static final byte TYPE_MASK_PRIVATE_CLASS = -64;
    @Deprecated
    public static final byte TYE_MASK_PRIVATE_CLASS = -64;
    public static final byte TYPE_MASK_PC_PRIMITIVE = 0;
    @Deprecated
    public static final byte TYE_MASK_PC_PRIMITIVE = 0;
    public static final byte TYPE_MASK_PC_CONSTRUCTED = 32;
    @Deprecated
    public static final byte TYE_MASK_PC_CONSTRUCTED = 32;
    
    private ASN1Constants() {
    }
    
    static {
        NO_ELEMENTS = new ASN1Element[0];
        BOOLEAN_VALUE_FALSE = new byte[] { 0 };
        BOOLEAN_VALUE_TRUE = new byte[] { -1 };
        LENGTH_0 = new byte[] { 0 };
        LENGTH_1 = new byte[] { 1 };
        LENGTH_2 = new byte[] { 2 };
        LENGTH_3 = new byte[] { 3 };
        LENGTH_4 = new byte[] { 4 };
        LENGTH_5 = new byte[] { 5 };
        LENGTH_6 = new byte[] { 6 };
        LENGTH_7 = new byte[] { 7 };
        LENGTH_8 = new byte[] { 8 };
        LENGTH_9 = new byte[] { 9 };
        LENGTH_10 = new byte[] { 10 };
        LENGTH_11 = new byte[] { 11 };
        LENGTH_12 = new byte[] { 12 };
        LENGTH_13 = new byte[] { 13 };
        LENGTH_14 = new byte[] { 14 };
        LENGTH_15 = new byte[] { 15 };
        LENGTH_16 = new byte[] { 16 };
        LENGTH_17 = new byte[] { 17 };
        LENGTH_18 = new byte[] { 18 };
        LENGTH_19 = new byte[] { 19 };
        LENGTH_20 = new byte[] { 20 };
        LENGTH_21 = new byte[] { 21 };
        LENGTH_22 = new byte[] { 22 };
        LENGTH_23 = new byte[] { 23 };
        LENGTH_24 = new byte[] { 24 };
        LENGTH_25 = new byte[] { 25 };
        LENGTH_26 = new byte[] { 26 };
        LENGTH_27 = new byte[] { 27 };
        LENGTH_28 = new byte[] { 28 };
        LENGTH_29 = new byte[] { 29 };
        LENGTH_30 = new byte[] { 30 };
        LENGTH_31 = new byte[] { 31 };
        LENGTH_32 = new byte[] { 32 };
        LENGTH_33 = new byte[] { 33 };
        LENGTH_34 = new byte[] { 34 };
        LENGTH_35 = new byte[] { 35 };
        LENGTH_36 = new byte[] { 36 };
        LENGTH_37 = new byte[] { 37 };
        LENGTH_38 = new byte[] { 38 };
        LENGTH_39 = new byte[] { 39 };
        LENGTH_40 = new byte[] { 40 };
        LENGTH_41 = new byte[] { 41 };
        LENGTH_42 = new byte[] { 42 };
        LENGTH_43 = new byte[] { 43 };
        LENGTH_44 = new byte[] { 44 };
        LENGTH_45 = new byte[] { 45 };
        LENGTH_46 = new byte[] { 46 };
        LENGTH_47 = new byte[] { 47 };
        LENGTH_48 = new byte[] { 48 };
        LENGTH_49 = new byte[] { 49 };
        LENGTH_50 = new byte[] { 50 };
        LENGTH_51 = new byte[] { 51 };
        LENGTH_52 = new byte[] { 52 };
        LENGTH_53 = new byte[] { 53 };
        LENGTH_54 = new byte[] { 54 };
        LENGTH_55 = new byte[] { 55 };
        LENGTH_56 = new byte[] { 56 };
        LENGTH_57 = new byte[] { 57 };
        LENGTH_58 = new byte[] { 58 };
        LENGTH_59 = new byte[] { 59 };
        LENGTH_60 = new byte[] { 60 };
        LENGTH_61 = new byte[] { 61 };
        LENGTH_62 = new byte[] { 62 };
        LENGTH_63 = new byte[] { 63 };
        LENGTH_64 = new byte[] { 64 };
        LENGTH_65 = new byte[] { 65 };
        LENGTH_66 = new byte[] { 66 };
        LENGTH_67 = new byte[] { 67 };
        LENGTH_68 = new byte[] { 68 };
        LENGTH_69 = new byte[] { 69 };
        LENGTH_70 = new byte[] { 70 };
        LENGTH_71 = new byte[] { 71 };
        LENGTH_72 = new byte[] { 72 };
        LENGTH_73 = new byte[] { 73 };
        LENGTH_74 = new byte[] { 74 };
        LENGTH_75 = new byte[] { 75 };
        LENGTH_76 = new byte[] { 76 };
        LENGTH_77 = new byte[] { 77 };
        LENGTH_78 = new byte[] { 78 };
        LENGTH_79 = new byte[] { 79 };
        LENGTH_80 = new byte[] { 80 };
        LENGTH_81 = new byte[] { 81 };
        LENGTH_82 = new byte[] { 82 };
        LENGTH_83 = new byte[] { 83 };
        LENGTH_84 = new byte[] { 84 };
        LENGTH_85 = new byte[] { 85 };
        LENGTH_86 = new byte[] { 86 };
        LENGTH_87 = new byte[] { 87 };
        LENGTH_88 = new byte[] { 88 };
        LENGTH_89 = new byte[] { 89 };
        LENGTH_90 = new byte[] { 90 };
        LENGTH_91 = new byte[] { 91 };
        LENGTH_92 = new byte[] { 92 };
        LENGTH_93 = new byte[] { 93 };
        LENGTH_94 = new byte[] { 94 };
        LENGTH_95 = new byte[] { 95 };
        LENGTH_96 = new byte[] { 96 };
        LENGTH_97 = new byte[] { 97 };
        LENGTH_98 = new byte[] { 98 };
        LENGTH_99 = new byte[] { 99 };
        LENGTH_100 = new byte[] { 100 };
        LENGTH_101 = new byte[] { 101 };
        LENGTH_102 = new byte[] { 102 };
        LENGTH_103 = new byte[] { 103 };
        LENGTH_104 = new byte[] { 104 };
        LENGTH_105 = new byte[] { 105 };
        LENGTH_106 = new byte[] { 106 };
        LENGTH_107 = new byte[] { 107 };
        LENGTH_108 = new byte[] { 108 };
        LENGTH_109 = new byte[] { 109 };
        LENGTH_110 = new byte[] { 110 };
        LENGTH_111 = new byte[] { 111 };
        LENGTH_112 = new byte[] { 112 };
        LENGTH_113 = new byte[] { 113 };
        LENGTH_114 = new byte[] { 114 };
        LENGTH_115 = new byte[] { 115 };
        LENGTH_116 = new byte[] { 116 };
        LENGTH_117 = new byte[] { 117 };
        LENGTH_118 = new byte[] { 118 };
        LENGTH_119 = new byte[] { 119 };
        LENGTH_120 = new byte[] { 120 };
        LENGTH_121 = new byte[] { 121 };
        LENGTH_122 = new byte[] { 122 };
        LENGTH_123 = new byte[] { 123 };
        LENGTH_124 = new byte[] { 124 };
        LENGTH_125 = new byte[] { 125 };
        LENGTH_126 = new byte[] { 126 };
        LENGTH_127 = new byte[] { 127 };
        NO_VALUE = new byte[0];
    }
}
