package sun.text.resources.cldr.gsw;

import java.util.ListResourceBundle;

public class FormatData_gsw extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "Januar", "Februar", "M\u00e4rz", "April", "Mai", "Juni", "Juli", "Auguscht", "Sept\u00e4mber", "Oktoober", "Nov\u00e4mber", "Dez\u00e4mber", "" } }, { "MonthAbbreviations", { "Jan", "Feb", "M\u00e4r", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez", "" } }, { "MonthNarrows", { "J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D", "" } }, { "DayNames", { "Sunntig", "M\u00e4\u00e4ntig", "Ziischtig", "Mittwuch", "Dunschtig", "Friitig", "Samschtig" } }, { "DayAbbreviations", { "Su.", "M\u00e4.", "Zi.", "Mi.", "Du.", "Fr.", "Sa." } }, { "DayNarrows", { "S", "M", "D", "M", "D", "F", "S" } }, { "QuarterNames", { "1. Quartal", "2. Quartal", "3. Quartal", "4. Quartal" } }, { "QuarterAbbreviations", { "Q1", "Q2", "Q3", "Q4" } }, { "AmPmMarkers", { "vorm.", "nam." } }, { "long.Eras", { "v. Chr.", "n. Chr." } }, { "Eras", { "v. Chr.", "n. Chr." } }, { "field.era", "Epoche" }, { "field.year", "Jaar" }, { "field.month", "Monet" }, { "field.week", "Wuche" }, { "field.weekday", "Wuchetag" }, { "field.dayperiod", "Tagesh\u00e4lfti" }, { "field.hour", "Schtund" }, { "field.minute", "Minuute" }, { "field.second", "Sekunde" }, { "field.zone", "Zone" }, { "TimePatterns", { "HH:mm:ss zzzz", "HH:mm:ss z", "HH:mm:ss", "HH:mm" } }, { "DatePatterns", { "EEEE, d. MMMM y", "d. MMMM y", "dd.MM.yyyy", "dd.MM.yy" } }, { "java.time.buddhist.DatePatterns", { "EEEE d. MMMM y G", "d. MMMM y G", "d. MMM y G", "d.M.yyyy" } }, { "buddhist.DatePatterns", { "EEEE d. MMMM y GGGG", "d. MMMM y GGGG", "d. MMM y GGGG", "d.M.yyyy" } }, { "calendarname.gregorian", "Gregoriaanisch Kal\u00e4nder" }, { "calendarname.gregory", "Gregoriaanisch Kal\u00e4nder" }, { "calendarname.roc", "Kal\u00e4nder vor Republik Chiina" }, { "calendarname.islamic-civil", "B\u00fcrgerlich islaamisch Kal\u00e4nder" }, { "calendarname.islamicc", "B\u00fcrgerlich islaamisch Kal\u00e4nder" }, { "calendarname.japanese", "Japaanisch Kal\u00e4nder" }, { "calendarname.buddhist", "Buddhischtisch Kal\u00e4nder" }, { "calendarname.islamic", "Islaamisch Kal\u00e4nder" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ".", "\u2019", ";", "%", "0", "#", "\u2212", "E", "\u2030", "\u221e", "NaN" } }, { "NumberPatterns", { "#,##0.###", "#,##0.00ад", "#,##0а%" } } };
    }
}
