package sun.util.resources.cldr.es;

import sun.util.resources.TimeZoneNamesBundle;

public class TimeZoneNames_es_419 extends TimeZoneNamesBundle
{
    @Override
    protected final Object[][] getContents() {
        final String[] array = { "Hora est\u00e1ndar de Monta\u00f1a", "MST", "Hora de verano de Monta\u00f1a", "MDT", "Hora de las Monta\u00f1as", "MT" };
        final String[] array2 = { "Hora est\u00e1ndar del Pac\u00edfico", "PST", "Hora de verano del Pac\u00edfico", "PDT", "Hora del Pac\u00edfico", "PT" };
        final String[] array3 = { "Hora est\u00e1ndar oriental", "EST", "Hora de verano oriental", "EDT", "Hora oriental", "ET" };
        final String[] array4 = { "Hora est\u00e1ndar central", "CST", "Hora de verano central", "CDT", "Hora central", "CT" };
        return new Object[][] { { "America/Los_Angeles", array2 }, { "America/Denver", array }, { "America/Phoenix", array }, { "America/Chicago", array4 }, { "America/New_York", array3 }, { "America/Indianapolis", array3 }, { "America/Inuvik", array }, { "America/Iqaluit", array3 }, { "America/Matamoros", array4 }, { "America/Indiana/Winamac", array3 }, { "America/El_Salvador", array4 }, { "America/Kentucky/Monticello", array3 }, { "America/Coral_Harbour", array3 }, { "America/North_Dakota/Center", array4 }, { "America/Guatemala", array4 }, { "PST8PDT", array2 }, { "America/Rankin_Inlet", array4 }, { "America/Cayman", array3 }, { "America/Belize", array4 }, { "America/Panama", array3 }, { "CST6CDT", array4 }, { "America/Indiana/Tell_City", array4 }, { "America/Menominee", array4 }, { "America/Tijuana", array2 }, { "America/Managua", array4 }, { "America/Indiana/Petersburg", array3 }, { "America/Resolute", array4 }, { "America/Chihuahua", array }, { "America/Ojinaga", array }, { "America/Merida", array4 }, { "America/Mazatlan", array }, { "America/Edmonton", array }, { "America/Tegucigalpa", array4 }, { "America/Rainy_River", array4 }, { "America/Yellowknife", array }, { "America/Port-au-Prince", array3 }, { "America/Nipigon", array3 }, { "America/Indiana/Vevay", array3 }, { "America/Regina", array4 }, { "America/Boise", array }, { "EST5EDT", array3 }, { "America/North_Dakota/New_Salem", array4 }, { "America/Dawson_Creek", array }, { "America/Costa_Rica", array4 }, { "America/Dawson", array2 }, { "America/Shiprock", array }, { "America/Winnipeg", array4 }, { "America/Hermosillo", array }, { "America/Indiana/Knox", array4 }, { "America/Cancun", array4 }, { "America/North_Dakota/Beulah", array4 }, { "America/Thunder_Bay", array3 }, { "America/Swift_Current", array4 }, { "America/Grand_Turk", array3 }, { "America/Metlakatla", array2 }, { "America/Bahia_Banderas", array4 }, { "America/Pangnirtung", array3 }, { "America/Santa_Isabel", array2 }, { "America/Cambridge_Bay", array }, { "America/Toronto", array3 }, { "America/Indiana/Marengo", array3 }, { "MST7MDT", array }, { "America/Creston", array }, { "America/Monterrey", array4 }, { "America/Indiana/Vincennes", array3 }, { "America/Whitehorse", array2 }, { "America/Nassau", array3 }, { "America/Mexico_City", array4 }, { "America/Jamaica", array3 }, { "America/Louisville", array3 }, { "America/Vancouver", array2 }, { "America/Montreal", array3 }, { "America/Detroit", array3 } };
    }
}
