package sun.text.resources.cldr.eu;

import java.util.ListResourceBundle;

public class FormatData_eu extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "urtarrila", "otsaila", "martxoa", "apirila", "maiatza", "ekaina", "uztaila", "abuztua", "iraila", "urria", "azaroa", "abendua", "" } }, { "MonthAbbreviations", { "urt", "ots", "mar", "api", "mai", "eka", "uzt", "abu", "ira", "urr", "aza", "abe", "" } }, { "MonthNarrows", { "U", "O", "M", "A", "M", "E", "U", "A", "I", "U", "A", "A", "" } }, { "DayNames", { "igandea", "astelehena", "asteartea", "asteazkena", "osteguna", "ostirala", "larunbata" } }, { "DayAbbreviations", { "ig", "al", "as", "az", "og", "or", "lr" } }, { "DayNarrows", { "I", "M", "A", "A", "A", "O", "I" } }, { "standalone.DayNarrows", { "I", "M", "A", "L", "A", "O", "I" } }, { "QuarterNames", { "1. hiruhilekoa", "2. hiruhilekoa", "3. hiruhilekoa", "4. hiruhilekoa" } }, { "QuarterAbbreviations", { "1Hh", "2Hh", "3Hh", "4Hh" } }, { "QuarterNarrows", { "1", "2", "3", "4" } }, { "narrow.AmPmMarkers", { "a", "p" } }, { "Eras", { "K.a.", "K.o." } }, { "field.era", "Aroa" }, { "field.year", "Urtea" }, { "field.month", "Hilabetea" }, { "field.week", "Astea" }, { "field.weekday", "Asteguna" }, { "field.dayperiod", "AM//PM" }, { "field.hour", "Ordua" }, { "field.minute", "Minutuak" }, { "field.second", "Segundoak" }, { "field.zone", "Ordu-eremua" }, { "TimePatterns", { "HH:mm:ss zzzz", "HH:mm:ss z", "HH:mm:ss", "HH:mm" } }, { "DatePatterns", { "EEEE, y'eko' MMMM'ren' dd'a'", "y'eko' MMM'ren' dd'a'", "y MMM d", "yyyy-MM-dd" } }, { "buddhist.Eras", { "BC", "BG" } }, { "roc.Eras", { "R.O.C. aurretik", "R.O.C." } }, { "calendarname.islamic-civil", "Islamiar egutegi zibila" }, { "calendarname.islamicc", "Islamiar egutegi zibila" }, { "calendarname.gregorian", "Egutegi gregoriarra" }, { "calendarname.gregory", "Egutegi gregoriarra" }, { "calendarname.japanese", "Japoniar egutegia" }, { "calendarname.buddhist", "Egutegi budista" }, { "calendarname.islamic", "Islamiar egutegia" }, { "calendarname.roc", "Txinako Errepublikako egutegia" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ",", ".", ";", "%", "0", "#", "-", "E", "\u2030", "\u221e", "NaN" } }, { "NumberPatterns", { "#,##0.###", "#,##0.00ад", "#,##0%" } } };
    }
}
