package com.me.mdm.onpremise.server.integration.sdp;

import java.io.File;

public class MDMSDPIntegrationConstants
{
    public static final String APPNAME = "APPNAME";
    public static final String SERVER = "SERVER";
    public static final String PORT = "PORT";
    public static final String PROTOCOL = "PROTOCOL";
    public static final String SDP_APP_NAME = "HelpDesk";
    public static final String AUTHENTICATION_KEY = "AUTHENTICATION_KEY";
    public static final String AUTHENDICATION_KEY = "AUTHENDICATION_KEY";
    public static final String OPERATION_NAME = "OPERATION_NAME";
    public static final String INPUT_DATA_SDP = "INPUT_DATA";
    public static final String INPUT_DATA_SDP_MSP = "data";
    public static final String ADD_REQUEST = "ADD_REQUEST";
    public static final String TECHNICIAN_KEY = "TECHNICIAN_KEY";
    public static final String TYPE_OF_OPERATION = "TYPE_OF_OPERATION";
    public static final String IS_NOT_TRAIL = "IS_NOT_TRAIL";
    public static final String SMART_PHONE = "Smart Phone";
    public static final String TABLET = "Tablet";
    public static final String ASSET_STATUS_IN_STORE = "In store";
    public static final String ASSET_STATUS_DISPOSED = "Disposed";
    public static final String ASSET = "asset";
    public static final String USERNAME = "username";
    public static final String MESSAGE = "message";
    public static final String OPERATION = "operation";
    public static final String DETAILS = "Details";
    public static final String DETAILS_MSP = "details";
    public static final String PARAMETER = "parameter";
    public static final String NAME = "name";
    public static final String VALUE = "value";
    public static final String LOGINANME = "loginname";
    public static final String DOMAIN_NAME_LOWER = "domainname";
    public static final String GET_ALL = "GET_ALL";
    public static final String STATUS = "status";
    public static final String SUCCESS = "success";
    public static final String DISPOSE = "dispose";
    public static final String DELETE = "delete";
    public static final String FORMAT = "format";
    public static final String ADD_WORKLOG = "ADD_WORKLOG";
    public static final String EDIT_REQUEST = "EDIT_REQUEST";
    public static final String GET_REQUEST = "GET_REQUEST";
    public static final String CLOSE_REQUEST = "CLOSE_REQUEST";
    public static final String REQUEST_TEMPLATE = "reqTemplate";
    public static final String SDP_NOTREACHABLE_COUNT = "SDPNotReachableCount";
    public static final String TOTAL_COUNT = "TotalCount";
    public static final String SUCCESS_COUNT = "SuccessCount";
    public static final String DIFF_NOFILES_ATTACHED_COUNT = "DiffNoFilesAttachedCount";
    public static final String INVALID_XML_FORMAT_COUNT = "InvalidXMLFormatCount";
    public static final String MAXIMAM_SIZE_REACHED_COUNT = "MaxSizeReachedCount";
    public static final String EMPTY_FILE_COUNT = "EmptyFileCount";
    public static final String FULLSCAN_FAILURE_COUNT = "FullScanFailCount";
    public static final String DIFFSCAN_FAILURE_COUNT = "DiffScanFailCount";
    public static final String COMPUTER_NOTAVAILABLE_COUNT = "CompNACount";
    public static final String FAILURE_COUNT = "FailCount";
    public static final String IS_WORKLOG_ENABLED = "IS_WORKLOG_ENABLED";
    public static final String CUSTOMER_NAME_IN_LOG = "customerName";
    public static final String OPERATION_NAME_IN_LOG = "operationName";
    public static final String DEVICE_NAME_IN_LOG = "deviceName";
    public static final String UDID_IN_LOG = "udid";
    public static final String ADD_UPDATE_ASSET_DATA_OP_IN_LOG = "Add/Update Asset Data";
    public static final String UPDATE_ASSET_OWNER_OP_IN_LOG = "Update Asset Owner";
    public static final String UPDATE_ASSET_OP_IN_LOG = "Update Asset Status";
    public static final String DELETE_ASSET_OP_IN_LOG = "Delete Asset";
    public static final String ASSET_QUEUE_DATA = "ASSET_QUEUE_DATA";
    public static final String SDP_AND_AE = "SDP_AND_AE";
    public static final String SDP_APPNAME = "HelpDesk";
    public static final String AE_APPNAME = "AssetExplorer";
    public static final String IS_FEATURE_UPDATE_ONLY = "IS_FEATURE_UPDATE_ONLY";
    public static final String SDP_INTEGRATION_ENABLED = "SDP_INTEGRATION_ENABLED";
    public static final String AE_INTEGRATION_ENABLED = "AE_INTEGRATION_ENABLED";
    public static final String SDP_MDM_POST_OWNER = "SDP_MDM_POST_OWNER";
    public static final String SDP_MDM_ASSET_DEL_VALUE = "SDP_MDM_ASSET_DEL_VALUE";
    public static final String IS_ENABLED = "IS_ENABLED";
    public static final String SDP_BUILD_NUMBER = "SDP_BUILD_NUMBER";
    public static final String SDP_MDM_INV_INTEGRATION = "SDP_MDM_INV_INTEGRATION";
    public static final String AE_MDM_INV_INTEGRATION = "AE_MDM_INV_INTEGRATION";
    public static final String INV_SCAN_SCHEDULED_TIME = "INV_SCAN_SCHEDULED_TIME";
    public static final String SDP_MDM_UI_INTEGRATION = "SDP_MDM_UI_INTEGRATION";
    public static final String SDP_MDM_UI_INTEGRATION_PARAMS = "SDP_MDM_UI_INTEGRATION_PARAMS";
    public static final String SDP_MDM_ACTION_INTEGRATION_PARAMS = "SDP_MDM_ACTION_INTEGRATION_PARAMS";
    public static final String SDP_MDM_HELPDESK_ALERT = "SDP_MDM_HELPDESK_ALERT";
    public static final String SDP_MDM_HELPDESK_NEW_APP_ALERT = "SDP_MDM_HELPDESK_NEW_APP_ALERT";
    public static final String SDP_MDM_HELPDESK_BLACKLIST_APP_ALERT = "SDP_MDM_HELPDESK_BLACKLIST_APP_ALERT";
    public static final String SDP_MDM_HELPDESK_UNMANAGED_CERTIFICATE_ALERT = "SDP_MDM_HELPDESK_UNMANAGED_CERTIFICATE_ALERT";
    public static final String MDM_SERVER_HOME;
    public static final String SDP_KEYSTORE_DIR;
    public static final String SDP_KEYSTORE_PATH;
    public static final char[] SDP_KEYSTORE_PASSPHRASE;
    public static final String SDP_CERTIFICATE_ALIAS = "sdpCertificate";
    public static final String AE_KEYSTORE_DIR;
    public static final String AE_KEYSTORE_PATH;
    public static final char[] AE_KEYSTORE_PASSPHRASE;
    public static final String AE_CERTIFICATE_ALIAS = "aeCertificate";
    public static final String BASE_URL = "BASE_URL";
    public static final String URL = "URL";
    public static final String CONTENT_TYPE = "CONTENT_TYPE";
    public static final String IS_DO_INPUT = "IS_DO_INPUT";
    public static final String IS_DO_OUTPUT = "IS_DO_OUTPUT";
    public static final String IS_FOR_DATA_POST = "IS_FOR_DATA_POST";
    public static final String KEYSTORE_PATH = "KEYSTORE_PATH";
    public static final String KEYSTORE_PASSPHRASE = "KEYSTORE_PASSPHRASE";
    public static final String NO_CONTENT_TYPE = "NO_CONTENT_TYPE";
    public static final String SDP_SETTINGS_PAGE_VISIT_COUNT = "SDP_SETTINGS_PAGE_VISIT_COUNT";
    public static final String ASSET_EXPLORER_SETTINGS_PAGE_VISIT_COUNT = "ASSET_EXPLORER_SETTINGS_PAGE_VISIT_COUNT";
    public static final String MDMP_SDP_ASSIGN_GROUP_COUNT = "MDMP_SDP_ASSIGN_GROUP_COUNT";
    public static final String MDMP_SDP_ASSIGN_PROFILE_GROUP_COUNT = "MDMP_SDP_ASSIGN_PROFILE_GROUP_COUNT";
    public static final String MDMP_SDP_ASSIGN_PROFILE_DEVICE_COUNT = "MDMP_SDP_ASSIGN_PROFILE_DEVICE_COUNT";
    public static final String MDMP_SDP_ASSIGN_APP_GROUP_COUNT = "MDMP_SDP_ASSIGN_APP_GROUP_COUNT";
    public static final String MDMP_SDP_ASSIGN_APP_DEVICE_COUNT = "MDMP_SDP_ASSIGN_APP_DEVICE_COUNT";
    public static final String MDMP_SDP_ASSIGN_STAGED_DEVICE_COUNT = "MDMP_SDP_ASSIGN_STAGED_DEVICE_COUNT";
    public static final String MDMP_SDP_DEPROVISION_DEVICE_COUNT = "MDMP_SDP_DEPROVISION_DEVICE_COUNT";
    public static final String MDMP_SDP_LOCATE_DEVICE_COUNT = "MDMP_SDP_LOCATE_DEVICE_COUNT";
    public static final String MDMP_SDP_LOCK_DEVICE_COUNT = "MDMP_SDP_LOCK_DEVICE_COUNT";
    public static final String MDMP_SDP_ALARM_DEVICE_COUNT = "MDMP_SDP_ALARM_DEVICE_COUNT";
    public static final String MDMP_SDP_CORPORATE_WIPE_DEVICE_COUNT = "MDMP_SDP_CORPORATE_WIPE_DEVICE_COUNT";
    public static final String MDMP_SDP_COMPLETE_WIPE_DEVICE_COUNT = "MDMP_SDP_COMPLETE_WIPE_DEVICE_COUNT";
    public static final String MDMP_SDP_CLEAR_PASSCODE_DEVICE_COUNT = "MDMP_SDP_CLEAR_PASSCODE_DEVICE_COUNT";
    public static final String MDMP_SDP_LOST_MODE_DEVICE_COUNT = "MDMP_SDP_LOST_MODE_DEVICE_COUNT";
    public static final String DOC_ROOT = "DocRoot";
    public static final String NODE = "Node";
    public static final String COMPUTER_NAME = "ComputerName";
    public static final String MAC_ADDRESS = "MacAddress";
    public static final String COMPUTER_INFO = "Computer_Info";
    public static final String HARDWARE_INFO = "Hardware_Info";
    public static final String SOFTWARE_INFO = "Software_Info";
    public static final String COMPUTER = "Computer";
    public static final String OS = "OperatingSystem";
    public static final String NAME_COMMON = "Name";
    public static final String MODEL = "Model";
    public static final String IS_LAPTOP = "isLaptop";
    public static final String BUILD_NUMBER = "BuildNumber";
    public static final String VERSION = "Version";
    public static final String SERIAL_NUMBER = "SerialNumber";
    public static final Long SDP_MSP_V3_COMPATIBLE_BUILD;
    
    static {
        MDM_SERVER_HOME = System.getProperty("server.home");
        SDP_KEYSTORE_DIR = MDMSDPIntegrationConstants.MDM_SERVER_HOME + File.separator + "conf" + File.separator + "sslcerts";
        SDP_KEYSTORE_PATH = MDMSDPIntegrationConstants.SDP_KEYSTORE_DIR + File.separator + "servicedeskplus.keystore";
        SDP_KEYSTORE_PASSPHRASE = "sdppassphrase".toCharArray();
        AE_KEYSTORE_DIR = MDMSDPIntegrationConstants.MDM_SERVER_HOME + File.separator + "conf" + File.separator + "sslcerts";
        AE_KEYSTORE_PATH = MDMSDPIntegrationConstants.SDP_KEYSTORE_DIR + File.separator + "assetexplorer.keystore";
        AE_KEYSTORE_PASSPHRASE = "aepassphrase".toCharArray();
        SDP_MSP_V3_COMPATIBLE_BUILD = 10600L;
    }
}
