package sun.text.resources.cldr.sl;

import java.util.ListResourceBundle;

public class FormatData_sl extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "januar", "februar", "marec", "april", "maj", "junij", "julij", "avgust", "september", "oktober", "november", "december", "" } }, { "MonthAbbreviations", { "jan.", "feb.", "mar.", "apr.", "maj", "jun.", "jul.", "avg.", "sep.", "okt.", "nov.", "dec.", "" } }, { "standalone.MonthAbbreviations", { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "avg", "sep", "okt", "nov", "dec", "" } }, { "MonthNarrows", { "j", "f", "m", "a", "m", "j", "j", "a", "s", "o", "n", "d", "" } }, { "DayNames", { "nedelja", "ponedeljek", "torek", "sreda", "\u010detrtek", "petek", "sobota" } }, { "DayAbbreviations", { "ned.", "pon.", "tor.", "sre.", "\u010det.", "pet.", "sob." } }, { "standalone.DayAbbreviations", { "ned", "pon", "tor", "sre", "\u010det", "pet", "sob" } }, { "DayNarrows", { "n", "p", "t", "s", "\u010d", "p", "s" } }, { "QuarterNames", { "1. \u010detrtletje", "2. \u010detrtletje", "3. \u010detrtletje", "4. \u010detrtletje" } }, { "QuarterAbbreviations", { "Q1", "Q2", "Q3", "Q4" } }, { "QuarterNarrows", { "1", "2", "3", "4" } }, { "AmPmMarkers", { "dop.", "pop." } }, { "long.Eras", { "pred na\u0161im \u0161tetjem", "na\u0161e \u0161tetje" } }, { "Eras", { "pr. n. \u0161t.", "po Kr." } }, { "field.era", "Doba" }, { "field.year", "Leto" }, { "field.month", "Mesec" }, { "field.week", "Teden" }, { "field.weekday", "Dan v tednu" }, { "field.dayperiod", "\u010cas dneva" }, { "field.hour", "Ura" }, { "field.minute", "Minuta" }, { "field.second", "Sekunda" }, { "field.zone", "Obmo\u010dje" }, { "TimePatterns", { "HH:mm:ss zzzz", "HH:mm:ss z", "HH:mm:ss", "HH:mm" } }, { "DatePatterns", { "EEEE, dd. MMMM y", "dd. MMMM y", "d. MMM yyyy", "d. MM. yy" } }, { "calendarname.gregorian", "gregorijanski koledar" }, { "calendarname.gregory", "gregorijanski koledar" }, { "calendarname.roc", "kitajski dr\u017eavni koledar" }, { "calendarname.islamic-civil", "islamski civilni koledar" }, { "calendarname.islamicc", "islamski civilni koledar" }, { "calendarname.japanese", "japonski koledar" }, { "calendarname.buddhist", "budisti\u010dni koledar" }, { "calendarname.islamic", "islamski koledar" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ",", ".", ";", "%", "0", "#", "-", "e", "\u2030", "\u221e", "NaN" } }, { "NumberPatterns", { "#,##0.###", "#,##0.00ад", "#,##0%" } } };
    }
}
