package sun.text.resources.es;

import sun.util.resources.OpenListResourceBundle;

public class JavaTimeSupplementary_es extends OpenListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "QuarterAbbreviations", { "T1", "T2", "T3", "T4" } }, { "QuarterNames", { "1er trimestre", "2º trimestre", "3er trimestre", "4º trimestre" } }, { "QuarterNarrows", { "1T", "2T", "3T", "4T" } }, { "calendarname.buddhist", "calendario budista" }, { "calendarname.gregorian", "calendario gregoriano" }, { "calendarname.gregory", "calendario gregoriano" }, { "calendarname.islamic", "calendario isl\u00e1mico" }, { "calendarname.islamic-civil", "calendario civil isl\u00e1mico" }, { "calendarname.islamicc", "calendario civil isl\u00e1mico" }, { "calendarname.japanese", "calendario japon\u00e9s" }, { "calendarname.roc", "calendario de la Rep\u00fablica de China" }, { "field.dayperiod", "periodo del d\u00eda" }, { "field.era", "era" }, { "field.hour", "hora" }, { "field.minute", "minuto" }, { "field.month", "mes" }, { "field.second", "segundo" }, { "field.week", "semana" }, { "field.weekday", "d\u00eda de la semana" }, { "field.year", "a\u00f1o" }, { "field.zone", "zona" }, { "islamic.DatePatterns", { "EEEE, d 'de' MMMM 'de' y GGGG", "d 'de' MMMM 'de' y GGGG", "dd/MM/y GGGG", "dd/MM/y GGGG" } }, { "java.time.buddhist.DatePatterns", { "EEEE, d 'de' MMMM 'de' y G", "d 'de' MMMM 'de' y G", "dd/MM/y G", "dd/MM/y G" } }, { "java.time.islamic.DatePatterns", { "EEEE, d 'de' MMMM 'de' y G", "d 'de' MMMM 'de' y G", "dd/MM/y G", "dd/MM/y G" } }, { "java.time.japanese.DatePatterns", { "EEEE, d 'de' MMMM 'de' y G", "d 'de' MMMM 'de' y G", "dd/MM/y G", "dd/MM/y GGGGG" } }, { "java.time.long.Eras", { "antes de Cristo", "anno D\u00f3mini" } }, { "java.time.roc.DatePatterns", { "EEEE, d 'de' MMMM 'de' y G", "d 'de' MMMM 'de' y G", "dd/MM/y G", "dd/MM/y GGGGG" } }, { "java.time.short.Eras", { "antes de Cristo", "anno D\u00f3mini" } }, { "roc.DatePatterns", { "EEEE, d 'de' MMMM 'de' y GGGG", "d 'de' MMMM 'de' y GGGG", "dd/MM/y GGGG", "dd/MM/y G" } }, { "roc.Eras", { "antes de R.O.C.", "" } }, { "roc.short.Eras", { "antes de R.O.C.", "" } } };
    }
}
