package sun.text.resources.cldr.is;

import java.util.ListResourceBundle;

public class FormatData_is extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "jan\u00faar", "febr\u00faar", "mars", "apr\u00edl", "ma\u00ed", "j\u00fan\u00ed", "j\u00fal\u00ed", "\u00e1g\u00fast", "september", "okt\u00f3ber", "n\u00f3vember", "desember", "" } }, { "MonthAbbreviations", { "jan", "feb", "mar", "apr", "ma\u00ed", "j\u00fan", "j\u00fal", "\u00e1g\u00fa", "sep", "okt", "n\u00f3v", "des", "" } }, { "MonthNarrows", { "J", "F", "M", "A", "M", "J", "J", "\u00c1", "L", "O", "N", "D", "" } }, { "standalone.MonthNarrows", { "j", "f", "m", "a", "m", "j", "j", "\u00e1", "s", "o", "n", "d", "" } }, { "DayNames", { "sunnudagur", "m\u00e1nudagur", "\u00feri\u00f0judagur", "mi\u00f0vikudagur", "fimmtudagur", "f\u00f6studagur", "laugardagur" } }, { "DayAbbreviations", { "sun", "m\u00e1n", "\u00feri", "mi\u00f0", "fim", "f\u00f6s", "lau" } }, { "DayNarrows", { "S", "M", "\u00de", "M", "F", "F", "L" } }, { "standalone.DayNarrows", { "s", "m", "\u00fe", "m", "f", "f", "l" } }, { "QuarterNames", { "1st fj\u00f3r\u00f0ungur", "2nd fj\u00f3r\u00f0ungur", "3rd fj\u00f3r\u00f0ungur", "4th fj\u00f3r\u00f0ungur" } }, { "standalone.QuarterNames", { "1. fj\u00f3r\u00f0ungur", "2. fj\u00f3r\u00f0ungur", "3. fj\u00f3r\u00f0ungur", "4. fj\u00f3r\u00f0ungur" } }, { "QuarterAbbreviations", { "F1", "F2", "F3", "F4" } }, { "standalone.QuarterAbbreviations", { "1F", "2F", "3F", "4F" } }, { "QuarterNarrows", { "1", "2", "3", "4" } }, { "AmPmMarkers", { "f.h.", "e.h." } }, { "Eras", { "fyrir Krist", "eftir Krist" } }, { "narrow.Eras", { "f.k.", "e.k." } }, { "field.era", "t\u00edmabil" }, { "field.year", "\u00e1r" }, { "field.month", "m\u00e1nu\u00f0ur" }, { "field.week", "vika" }, { "field.weekday", "vikudagur" }, { "field.dayperiod", "f.h./e.h." }, { "field.hour", "klukkustund" }, { "field.minute", "m\u00edn\u00fata" }, { "field.second", "sek\u00fanda" }, { "field.zone", "sv\u00e6\u00f0i" }, { "TimePatterns", { "HH:mm:ss zzzz", "HH:mm:ss z", "HH:mm:ss", "HH:mm" } }, { "DatePatterns", { "EEEE, d. MMMM y", "d. MMMM y", "d.M.yyyy", "d.M.yyyy" } }, { "calendarname.gregorian", "Gregor\u00edskt dagatal" }, { "calendarname.gregory", "Gregor\u00edskt dagatal" }, { "calendarname.roc", "k\u00ednverskt dagatal" }, { "calendarname.islamic-civil", "\u00cdslamskt borgaradagatal" }, { "calendarname.islamicc", "\u00cdslamskt borgaradagatal" }, { "calendarname.japanese", "Japanskt dagatal" }, { "calendarname.buddhist", "B\u00fadd\u00edskt dagatal" }, { "calendarname.islamic", "\u00cdslamskt dagatal" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ",", ".", ";", "%", "0", "#", "\u2212", "\u00d710^", "\u2030", "\u221e", "EiTa" } }, { "NumberPatterns", { "#,##0.###", "#,##0.00ад", "#,##0%" } } };
    }
}
