package sun.text.resources.cldr.sk;

import java.util.ListResourceBundle;

public class FormatData_sk extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "janu\u00e1ra", "febru\u00e1ra", "marca", "apr\u00edla", "m\u00e1ja", "j\u00fana", "j\u00fala", "augusta", "septembra", "okt\u00f3bra", "novembra", "decembra", "" } }, { "standalone.MonthNames", { "janu\u00e1r", "febru\u00e1r", "marec", "apr\u00edl", "m\u00e1j", "j\u00fan", "j\u00fal", "august", "september", "okt\u00f3ber", "november", "december", "" } }, { "MonthAbbreviations", { "jan", "feb", "mar", "apr", "m\u00e1j", "j\u00fan", "j\u00fal", "aug", "sep", "okt", "nov", "dec", "" } }, { "MonthNarrows", { "j", "f", "m", "a", "m", "j", "j", "a", "s", "o", "n", "d", "" } }, { "DayNames", { "nede\u013ea", "pondelok", "utorok", "streda", "\u0161tvrtok", "piatok", "sobota" } }, { "standalone.DayNames", { "nede\u013ea", "pondelok", "utorok", "streda", "\u0161tvrtok", "piatok", "sobota" } }, { "DayAbbreviations", { "ne", "po", "ut", "st", "\u0161t", "pi", "so" } }, { "standalone.DayAbbreviations", { "ne", "po", "ut", "st", "\u0161t", "pi", "so" } }, { "DayNarrows", { "N", "P", "U", "S", "\u0160", "P", "S" } }, { "standalone.DayNarrows", { "N", "P", "U", "S", "\u0160", "P", "S" } }, { "QuarterNames", { "1. \u0161tvr\u0165rok", "2. \u0161tvr\u0165rok", "3. \u0161tvr\u0165rok", "4. \u0161tvr\u0165rok" } }, { "standalone.QuarterNames", { "1. \u0161tvr\u0165rok", "2. \u0161tvr\u0165rok", "3. \u0161tvr\u0165rok", "4. \u0161tvr\u0165rok" } }, { "QuarterAbbreviations", { "Q1", "Q2", "Q3", "Q4" } }, { "standalone.QuarterAbbreviations", { "1Q", "2Q", "3Q", "4Q" } }, { "QuarterNarrows", { "1", "2", "3", "4" } }, { "AmPmMarkers", { "dopoludnia", "popoludn\u00ed" } }, { "Eras", { "pred n.l.", "n.l." } }, { "field.era", "\u00c9ra" }, { "field.year", "Rok" }, { "field.month", "Mesiac" }, { "field.week", "T\u00fd\u017ede\u0148" }, { "field.weekday", "De\u0148 v t\u00fd\u017edni" }, { "field.dayperiod", "\u010cas\u0165 d\u0148a" }, { "field.hour", "Hodina" }, { "field.minute", "Min\u00fata" }, { "field.second", "Sekunda" }, { "field.zone", "P\u00e1smo" }, { "TimePatterns", { "H:mm:ss zzzz", "H:mm:ss z", "H:mm:ss", "H:mm" } }, { "DatePatterns", { "EEEE, d. MMMM y", "d. MMMM y", "d.M.yyyy", "d.M.yyyy" } }, { "calendarname.gregorian", "Gregori\u00e1nsky kalend\u00e1r" }, { "calendarname.gregory", "Gregori\u00e1nsky kalend\u00e1r" }, { "calendarname.roc", "Kalend\u00e1r \u010c\u00ednskej republiky" }, { "calendarname.islamic-civil", "Islamsk\u00fd ob\u010diansky kalend\u00e1r" }, { "calendarname.islamicc", "Islamsk\u00fd ob\u010diansky kalend\u00e1r" }, { "calendarname.japanese", "Japonsk\u00fd kalend\u00e1r" }, { "calendarname.buddhist", "Buddhistick\u00fd kalend\u00e1r" }, { "calendarname.islamic", "Islamsk\u00fd kalend\u00e1r" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ",", "а", ",", "%", "0", "#", "-", "E", "\u2030", "\u221e", "NaN" } }, { "NumberPatterns", { "#,##0.###", "#,##0.00ад", "#,##0а%" } } };
    }
}
