package com.me.devicemanagement.onpremise.tools.backuprestore.util;

import java.io.File;

public class BackupRestoreContants
{
    public static final int SUCCESS = 1;
    public static final int ERROR = -1;
    public static final int INVALID_ZIP = -2;
    public static final int INCOMPATIBLE_BUILD = -3;
    public static final int SERVER_RUNNING = -4;
    public static final int OUT_OF_MEMORY = -5;
    public static final int RUNTIME_ERROR = -6;
    public static final int CANCELLED = -7;
    public static final int REMOTE_DB_NOT_RUNNING = -8;
    public static final int INCOMPATIBLE_PRODUCT = -9;
    public static final int INCOMPATIBLE_DB = -10;
    public static final int CURRENT_BACKUP_FAILED = -11;
    public static final int REVERT_FAILED = -12;
    public static final int FILES_MISSING = -13;
    public static final int INCOMPATIBLE_ARCHITECTURE = -14;
    public static final int PEER_NOT_REACHABLE = -15;
    public static final int FOS_SERVER_RUNNING = -16;
    public static final int SQL_DB_FILE_SYSTEM_MISMATCH = -17;
    public static final int SERVER_MAINTENANCE_RUNNING = -18;
    public static final int EXE_RUNNING = -19;
    public static final int MSSQL_DB_VERSION_CHECK_FAILED = -20;
    public static final int MSSQL_DB_MAJOR_VERSION_MISMATCH = -21;
    public static final int COPYING = 2;
    public static final int DUMPING = 3;
    public static final int COMPRESSING = 4;
    public static final int CLEANING_UP = 5;
    public static final int COPYING_CURRENT_CONFIG = 6;
    public static final int EXTRACTING = 7;
    public static final int RESTORING = 8;
    public static final int RESTORED_PREV_CONFIG = 9;
    public static final int REVERTING = 10;
    public static final int CANCELLING = 11;
    public static final int ESTIMATING = 12;
    public static final int BACKUP_IN_PROGRESS = 13;
    public static final int FILE_BACKUP_IN_PROGRESS = 14;
    public static final int DB_BACKUP_IN_PROGRESS = 15;
    public static final int RUNNING_PRECHECK = 16;
    public static final int FILE_RESTORE_IN_PROGRESS = 17;
    public static final int DB_RESTORE_IN_PROGRESS = 18;
    public static final int REDIS_BACKUP_IN_PROGRESS = 19;
    public static final int REDIS_RESTORE_IN_PROGRESS = 20;
    public static final int BINARY = 1;
    public static final int DUMP = 2;
    public static final int COPY = 3;
    public static final int MYSQLDB = 1;
    public static final int PGSQLDB = 2;
    public static final int MSSQLDB = 3;
    public static final String REDIS_DATA_FOLDER_LOC;
    public static final String REDIS_CONF_FOLDER_LOC;
    public static final String REDIS_DUMP_FILE_LOC;
    public static final String REDIS_AOF_FILE_LOC;
    public static final String PRODUCT_SETTINGS_LOC;
    public static final String REDIS_SETTINGS_LOC;
    public static final String REPLICATION_USE_CREDENTIAL = "repl.usecredentials";
    public static final String REPLICATION_SHARENAME = "repl.sharename";
    public static final String REPLICATION_USERNAME = "repl.username";
    public static final String REPLICATION_PASSWORD = "repl.password";
    public static final String REMOTE_INSTALLATION_DIRECTORY = "repl.remoteinstallationDir";
    public static final String DEFAULT_OUTFILE_FORMAT = "$BUILDNUMBER-$TIMESTAMP";
    public static final String TIME_STAMP_FORMAT = "MMM-dd-yyyy-HH-mm";
    public static final String MEDC = "medc";
    public static final String XML_NAME = "backup-files.xml";
    public static final String BACKUP_FILES_XML_LOCATION = "/conf/backup-files.xml";
    public static final String BACKUP_TRACKER_JSON_FILENAME = "BackupTracking.json";
    public static final String BACKUP_TRACKER_INTERNAL_JSON_FILENAME = "BackupTrackingInternal.json";
    public static final String BACKUP_LOC_TYPE_KEY = "loc-type";
    public static final String IS_MAIL_CONFIGURED_KEY = "is-mail-configured";
    public static final String BACKUP_FILES_MAINTAIN_COUNT_KEY = "backup-count";
    public static final String BACKUP_STATUS_KEY = "backup-status";
    public static final String RESTORE_STATUS_KEY = "restore-status";
    public static final String SUCCESS_STATUS_VALUE = "success";
    public static final String FAILURE_STATUS_VALUE = "failure";
    public static final String BACKUP_HISTORY_KEY = "backup-history";
    public static final String RESTORE_HISTORY_KEY = "restore-history";
    public static final String LAST_SUCCESSFUL_TIME_KEY = "last-success-time";
    public static final String TOP_ERROR_KEY = "top-errors";
    public static final String USE_NATIVE_FOR_EXECUTION_KEY = "use-nat";
    public static final String USE_NATIVE_FOR_EXECUTION_HISTORY_KEY = "use-nat-his";
    public static final String BACKUP_ERROR_CODE_KEY = "errcode";
    public static final String BAK_FORMAT_ENABLED_STATUS = "bak-enabled";
    public static final String BAK_FORMAT_ENABLED_DURING_PPM = "bak-enabled-inppm";
    public static final String PASSWORD_PROTECTED_KEY = "isPasswordProtected";
    public static final String BACKUP_TYPE_KEY = "backup-type";
    public static final String RESTORE_TYPE_KEY = "restore-type";
    public static final String BACKUP_FOLDER_PERMISSION_KEY = "backup-folder-permission";
    public static final String BAK_BACKUP_PERMISSION_KEY = "bak-backup-permission";
    public static final int BACKUP_RESTORE_HISTORY_COUNT = 30;
    public static final int BACKUP_RESTORE_ERROR_HISTORY_COUNT = 3;
    public static final int BACKUP_LOC_TYPE = 1;
    public static final int MAIL_CONFIGURED = 2;
    public static final int BACKUP_STATUS = 3;
    public static final int RESTORE_STATUS = 4;
    public static final int BACKUP_FILES_MAINTAIN_COUNT = 5;
    public static final int BACKUP_ERROR_CODE = 6;
    public static final int DLL_BACKUP = 7;
    public static final int PASSWORD_PROTECTED = 8;
    public static final int BACKUP_TYPE = 9;
    public static final int RESTORE_TYPE = 10;
    public static final int SCHEDULED_DB_BACKUP_FOLDER_PERMISSION = 11;
    public static final int BAK_BACKUP_PERMISSION = 12;
    public static final int DEFAULT_BACKUP_LOC = 1;
    public static final int DIFFERENT_DIRECTORY_BACKUP_LOC = 2;
    public static final int REMOTE_BACKUP_LOC = 3;
    public static final String DEFAULT_DBBACKUP_PASSWORD = "Password123";
    public static final String PASSWORD_HINT_FILENAME = "DB_Password_Hint.txt";
    public static final String DUMP_BACKUP_FOLDER = "DumpBackup";
    public static final String DUMP_TYPE = "dump";
    public static final String BINARY_TYPE = "binary";
    public static final String MSSQL_BAK_BACKUPRESTORE_CONFIGURATIONS = "mssql_bak_backuprestore_configurations";
    public static final String MSSQL_BAK_BACKUP_CONFIGURATIONS = "backup_configurations";
    public static final String MSSQL_BAK_RESTORE_CONFIGURATIONS = "restore_configurations";
    
    static {
        REDIS_DATA_FOLDER_LOC = "redis" + File.separator + "data";
        REDIS_CONF_FOLDER_LOC = "redis" + File.separator + "conf";
        REDIS_DUMP_FILE_LOC = "redis" + File.separator + "data" + File.separator + "dump.rdb";
        REDIS_AOF_FILE_LOC = "redis" + File.separator + "data" + File.separator + "appendonly.aof";
        PRODUCT_SETTINGS_LOC = "conf" + File.separator + "productSettings.conf";
        REDIS_SETTINGS_LOC = "conf" + File.separator + "redis_settings.conf";
    }
}
