package sun.text.resources.cldr.fil;

import java.util.ListResourceBundle;

public class FormatData_fil extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "Enero", "Pebrero", "Marso", "Abril", "Mayo", "Hunyo", "Hulyo", "Agosto", "Setyembre", "Oktubre", "Nobyembre", "Disyembre", "" } }, { "MonthAbbreviations", { "Ene", "Peb", "Mar", "Abr", "May", "Hun", "Hul", "Ago", "Set", "Okt", "Nob", "Dis", "" } }, { "MonthNarrows", { "E", "P", "M", "A", "M", "H", "H", "A", "S", "O", "N", "D", "" } }, { "DayNames", { "Linggo", "Lunes", "Martes", "Miyerkules", "Huwebes", "Biyernes", "Sabado" } }, { "DayAbbreviations", { "Lin", "Lun", "Mar", "Mye", "Huw", "Bye", "Sab" } }, { "standalone.DayAbbreviations", { "", "", "", "Miy", "", "Biy", "" } }, { "DayNarrows", { "L", "L", "M", "M", "H", "B", "S" } }, { "QuarterNames", { "ika-1 sangkapat", "ika-2 sangkapat", "ika-3 quarter", "ika-4 na quarter" } }, { "standalone.QuarterNames", { "ika-1 sangkapat", "ika-2 quarter", "ika-3 sangkapat", "ika-4 na quarter" } }, { "QuarterAbbreviations", { "Q1", "Q2", "Q3", "Q4" } }, { "standalone.QuarterAbbreviations", { "Q1", "Q2", "Q3", "Q4" } }, { "QuarterNarrows", { "1", "2", "3", "4" } }, { "narrow.AmPmMarkers", { "a", "p" } }, { "Eras", { "BC", "AD" } }, { "field.era", "Era" }, { "field.year", "Taon" }, { "field.month", "Buwan" }, { "field.week", "Linggo" }, { "field.weekday", "Araw ng Linggo" }, { "field.dayperiod", "Dayperiod" }, { "field.hour", "Oras" }, { "field.minute", "Minuto" }, { "field.second", "Segundo" }, { "field.zone", "Zone" }, { "TimePatterns", { "HH:mm:ss zzzz", "HH:mm:ss z", "HH:mm:ss", "HH:mm" } }, { "DatePatterns", { "EEEE, MMMM dd y", "MMMM d, y", "MMM d, y", "M/d/yy" } }, { "calendarname.islamic-civil", "Kalendaryong Islamic-Civil" }, { "calendarname.islamicc", "Kalendaryong Islamic-Civil" }, { "calendarname.gregorian", "Kalendaryong Gregorian" }, { "calendarname.gregory", "Kalendaryong Gregorian" }, { "calendarname.japanese", "Kalendaryong Japanese" }, { "calendarname.buddhist", "Kalendaryo ng Buddhist" }, { "calendarname.islamic", "Kalendaryong Islamic" }, { "calendarname.roc", "Kalendaryong Minguo" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ".", ",", ";", "%", "0", "#", "-", "E", "\u2030", "\u221e", "NaN" } }, { "NumberPatterns", { "#,##0.###", "да#,##0.00", "#,##0%" } } };
    }
}
