package com.theorem.radius3;

public final class Cisco
{
    public static final int VENDORID = 9;
    public static final int avpair = 1;
    public static final int cisco_avpair = 1;
    public static final int ciscoav = 1;
    public static final int Cisco_AVPair = 1;
    public static final int Cisco_NAS_Port = 2;
    public static final int Cisco_Fax_Account_Id_Origin = 3;
    public static final int Cisco_Fax_Msg_Id = 4;
    public static final int Cisco_Fax_Pages = 5;
    public static final int Cisco_Fax_Coverpage_Flag = 6;
    public static final int Cisco_Fax_Modem_Time = 7;
    public static final int Cisco_Fax_Connect_Speed = 8;
    public static final int Cisco_Fax_Recipient_Count = 9;
    public static final int Cisco_Fax_Process_Abort_Flag = 10;
    public static final int Cisco_Fax_Dsn_Address = 11;
    public static final int Cisco_Fax_Dsn_Flag = 12;
    public static final int Cisco_Fax_Mdn_Address = 13;
    public static final int Cisco_Fax_Mdn_Flag = 14;
    public static final int Cisco_Fax_Auth_Status = 15;
    public static final int Cisco_Email_Server_Address = 16;
    public static final int Cisco_Email_Server_Ack_Flag = 17;
    public static final int Cisco_Gateway_Id = 18;
    public static final int Cisco_Call_Type = 19;
    public static final int Cisco_Port_Used = 20;
    public static final int Cisco_Abort_Cause = 21;
    public static final int h323_remote_address = 23;
    public static final int h323_conf_id = 24;
    public static final int h323_setup_time = 25;
    public static final int h323_call_origin = 26;
    public static final int h323_call_type = 27;
    public static final int h323_connect_time = 28;
    public static final int h323_disconnect_time = 29;
    public static final int h323_disconnect_cause = 30;
    public static final int h323_voice_quality = 31;
    public static final int h323_gw_id = 33;
    public static final int h323_incoming_conf_id = 35;
    public static final int h323_credit_amount = 101;
    public static final int h323_credit_time = 102;
    public static final int h323_return_code = 103;
    public static final int h323_prompt_id = 104;
    public static final int h323_time_and_day = 105;
    public static final int h323_redirect_number = 106;
    public static final int h323_preferred_lang = 107;
    public static final int h323_redirect_ip_address = 108;
    public static final int h323_billing_model = 109;
    public static final int h323_currency = 110;
    public static final int subscriber = 111;
    public static final int gw_rxd_cdn = 112;
    public static final int gw_final_xlated_cdn = 113;
    public static final int call_id = 141;
    public static final int session_protocol = 142;
    public static final int method = 143;
    public static final int prev_hop_via = 144;
    public static final int prev_hop_ip = 145;
    public static final int incoming_req_uri = 146;
    public static final int outgoing_req_uri = 147;
    public static final int next_hop_ip = 148;
    public static final int next_hop_dn = 149;
    public static final int sip_hdr = 150;
    public static final int Cisco_Multilink_ID = 187;
    public static final int Cisco_Num_In_Multilink = 188;
    public static final int Cisco_Pre_Input_Octets = 190;
    public static final int Cisco_Pre_Output_Octets = 191;
    public static final int Cisco_Pre_Input_Packets = 192;
    public static final int Cisco_Pre_Output_Packets = 193;
    public static final int Cisco_Maximum_Time = 194;
    public static final int Cisco_Disconnect_Cause = 195;
    public static final int Cisco_Data_Rate = 197;
    public static final int Cisco_PreSession_Time = 198;
    public static final int Cisco_PW_Lifetime = 208;
    public static final int Cisco_IP_Direct = 209;
    public static final int Cisco_PPP_VJ_Slot_Comp = 210;
    public static final int Cisco_PPP_Async_Map = 212;
    public static final int Cisco_IP_Pool_Definition = 217;
    public static final int Cisco_Assign_IP_Pool = 218;
    public static final int Cisco_Route_IP = 228;
    public static final int Cisco_Link_Compression = 233;
    public static final int Cisco_Target_Util = 234;
    public static final int Cisco_Maximum_Channels = 235;
    public static final int Cisco_Data_Filter = 242;
    public static final int Cisco_Call_Filter = 243;
    public static final int Cisco_Idle_Limit = 244;
    public static final int Cisco_Account_Info = 250;
    public static final int Cisco_Service_Info = 251;
    public static final int Cisco_Command_Code = 252;
    public static final int Cisco_Control_Info = 253;
    public static final int Cisco_Xmit_Rate = 255;
    
    public Cisco() {
        VendorSpecific.addVendor(this.getClass().getName(), 9);
    }
}
