package sun.text.resources.cldr.en;

import java.util.ListResourceBundle;

public class FormatData_en extends ListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "MonthNames", { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", "" } }, { "MonthAbbreviations", { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "" } }, { "MonthNarrows", { "J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D", "" } }, { "DayNames", { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" } }, { "DayAbbreviations", { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" } }, { "DayNarrows", { "S", "M", "T", "W", "T", "F", "S" } }, { "QuarterNames", { "1st quarter", "2nd quarter", "3rd quarter", "4th quarter" } }, { "QuarterAbbreviations", { "Q1", "Q2", "Q3", "Q4" } }, { "narrow.AmPmMarkers", { "a", "p" } }, { "long.Eras", { "Before Christ", "Anno Domini" } }, { "Eras", { "BC", "AD" } }, { "narrow.Eras", { "B", "A" } }, { "field.era", "Era" }, { "field.year", "Year" }, { "field.month", "Month" }, { "field.week", "Week" }, { "field.weekday", "Day of the Week" }, { "field.dayperiod", "AM/PM" }, { "field.hour", "Hour" }, { "field.minute", "Minute" }, { "field.second", "Second" }, { "field.zone", "Time Zone" }, { "TimePatterns", { "h:mm:ss a zzzz", "h:mm:ss a z", "h:mm:ss a", "h:mm a" } }, { "DatePatterns", { "EEEE, MMMM d, y", "MMMM d, y", "MMM d, y", "M/d/yy" } }, { "DateTimePatterns", { "{1} {0}" } }, { "java.time.buddhist.DatePatterns", { "EEEE, MMMM d, y G", "MMMM d, y G", "MMM d, y G", "M/d/yy GGGGG" } }, { "buddhist.DatePatterns", { "EEEE, MMMM d, y GGGG", "MMMM d, y GGGG", "MMM d, y GGGG", "M/d/yy G" } }, { "java.time.japanese.DatePatterns", { "EEEE, MMMM d, y G", "MMMM d, y G", "MMM d, y G", "M/d/yy GGGGG" } }, { "japanese.DatePatterns", { "EEEE, MMMM d, y GGGG", "MMMM d, y GGGG", "MMM d, y GGGG", "M/d/yy G" } }, { "java.time.roc.DatePatterns", { "EEEE, MMMM d, y G", "MMMM d, y G", "MMM d, y G", "M/d/yy GGGGG" } }, { "roc.DatePatterns", { "EEEE, MMMM d, y GGGG", "MMMM d, y GGGG", "MMM d, y GGGG", "M/d/yy G" } }, { "java.time.islamic.DatePatterns", { "EEEE, MMMM d, y G", "MMMM d, y G", "MMM d, y G", "M/d/yy G" } }, { "islamic.DatePatterns", { "EEEE, MMMM d, y GGGG", "MMMM d, y GGGG", "MMM d, y GGGG", "M/d/yy GGGG" } }, { "calendarname.islamic-umalqura", "Islamic Calendar [Umm al-Qura]" }, { "calendarname.islamic-civil", "Islamic-Civil Calendar" }, { "calendarname.islamicc", "Islamic-Civil Calendar" }, { "calendarname.buddhist", "Buddhist Calendar" }, { "calendarname.islamic", "Islamic Calendar" }, { "calendarname.gregorian", "Gregorian Calendar" }, { "calendarname.gregory", "Gregorian Calendar" }, { "calendarname.roc", "Minguo Calendar" }, { "calendarname.japanese", "Japanese Calendar" }, { "DefaultNumberingSystem", "latn" }, { "latn.NumberElements", { ".", ",", ";", "%", "0", "#", "-", "E", "\u2030", "\u221e", "NaN" } }, { "NumberPatterns", { "#,##0.###", "¤#,##0.00;(¤#,##0.00)", "#,##0%" } } };
    }
}
