package com.me.devicemanagement.framework.webclient.schedulereport;

public class CriteriaBasedReportConstants
{
    public static final String WHERE = "WHERE";
    public static final String AND = "AND";
    public static final String OR = "OR";
    public static final String ON = "ON";
    public static final String NOT = "NOT";
    public static final String DATE = "DATE";
    public static final String DATE_RESTRICTED = "DATE_RESTRICTED";
    public static final String DATE_TIME = "DATETIME";
    public static final String BOOLEAN = "BOOLEAN";
    public static final String BIGINT = "BIGINT";
    public static final String INT = "INT";
    public static final String CHAR = "CHAR";
    public static final String SPACE = " ";
    public static final String COMMA = ",";
    public static final String EMPTY_STRING = "";
    public static final String OPEN_BRACE = "(";
    public static final String CLOSE_BRACE = ")";
    public static final String SINGLE_QUOTE = "'";
    public static final String EQUAL_TOKEN = "=";
    public static final String NOT_EQUAL_TOKEN = "!=";
    public static final String GREATER_THAN_TOKEN = ">";
    public static final String GREATER_EQUAL_TOKEN = ">=";
    public static final String LESS_THAN_TOKEN = "<";
    public static final String LESSER_EQUAL_TOKEN = "<=";
    public static final String INNER_JOIN_TOKEN = "INNER JOIN";
    public static final String LEFT_JOIN_TOKEN = "LEFT JOIN";
    public static final String DATE_RANGE_FROM = "date1";
    public static final String DATE_RANGE_TO = "date2";
    public static final String EQUAL = "equal";
    public static final String NOT_EQUAL = "not equal";
    public static final String EMPTY = "empty";
    public static final String NOT_EMPTY = "not empty";
    public static final String GREATER_THAN = "greater than";
    public static final String GREATER_OR_EQUAL = "greater or equal";
    public static final String LESS_THAN = "less than";
    public static final String LESS_OR_EQUAL = "less or equal";
    public static final String LIKE = "like";
    public static final String CONTAINS = "contains";
    public static final String BEFORE = "Before";
    public static final String AFTER = "After";
    public static final String NOT_LIKE = "not like";
    public static final String STARTS_WITH = "starts with";
    public static final String ENDS_WITH = "ends with";
    public static final String IN = "in";
    public static final String NOT_IN = "not in";
    public static final String IS = "is";
    public static final String IS_NOT = "is not";
    public static final String INNER_JOIN = "INNER_JOIN";
    public static final String LEFT_JOIN = "LEFT_JOIN";
    public static final String DOT = ".";
    public static final int LOGICAL_AND = 1;
    public static final int LOGICAL_OR = 2;
    public static final int MAIN_CRIT = 1;
    public static final int PLACE_HOLDER_CRIT = 2;
    public static final int BOTH_CRIT = 3;
}
