package sun.text.resources.fr;

import sun.util.resources.OpenListResourceBundle;

public class JavaTimeSupplementary_fr extends OpenListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "QuarterAbbreviations", { "T1", "T2", "T3", "T4" } }, { "QuarterNames", { "1er trimestre", "2e trimestre", "3e trimestre", "4e trimestre" } }, { "QuarterNarrows", { "T1", "T2", "T3", "T4" } }, { "calendarname.buddhist", "Calendrier bouddhiste" }, { "calendarname.gregorian", "Calendrier gr\u00e9gorien" }, { "calendarname.gregory", "Calendrier gr\u00e9gorien" }, { "calendarname.islamic", "Calendrier musulman" }, { "calendarname.islamic-civil", "Calendrier civil musulman" }, { "calendarname.islamicc", "Calendrier civil musulman" }, { "calendarname.japanese", "Calendrier japonais" }, { "calendarname.roc", "Calendrier r\u00e9publicain chinois" }, { "field.dayperiod", "cadran" }, { "field.era", "\u00e8re" }, { "field.hour", "heure" }, { "field.minute", "minute" }, { "field.month", "mois" }, { "field.second", "seconde" }, { "field.week", "semaine" }, { "field.weekday", "jour de la semaine" }, { "field.year", "ann\u00e9e" }, { "field.zone", "fuseau horaire" }, { "islamic.DatePatterns", { "EEEE d MMMM y GGGG", "d MMMM y GGGG", "d MMM, y GGGG", "d/M/y GGGG" } }, { "islamic.Eras", { "", "AH" } }, { "islamic.MonthAbbreviations", { "Mouh.", "Saf.", "Rabi\u02bb-oul-A.", "Rabi\u02bb-out-T.", "Djoum.-l-O.", "Djoum.-t-T.", "Radj.", "Cha.", "Ram.", "Chaou.", "Dou-l-Q.", "Dou-l-H.", "" } }, { "islamic.MonthNames", { "Mouharram", "Safar", "Rabi\u02bb-oul-Aououal", "Rabi\u02bb-out-Tani", "Djoumada-l-Oula", "Djoumada-t-Tania", "Radjab", "Cha\u02bbban", "Ramadan", "Chaououal", "Dou-l-Qa\u02bbda", "Dou-l-Hidjja", "" } }, { "islamic.short.Eras", { "", "AH" } }, { "java.time.buddhist.DatePatterns", { "EEEE d MMMM y G", "d MMMM y G", "d MMM, y G", "d/M/yyyy" } }, { "java.time.buddhist.long.Eras", { "BC", "\u00e8re bouddhiste" } }, { "java.time.buddhist.short.Eras", { "BC", "\u00e8re bouddhiste" } }, { "java.time.islamic.DatePatterns", { "EEEE d MMMM y G", "d MMMM y G", "d MMM, y G", "d/M/y G" } }, { "java.time.japanese.DatePatterns", { "EEEE d MMMM y G", "d MMMM y G", "d MMM, y G", "d/M/y GGGGG" } }, { "java.time.long.Eras", { "avant J\u00e9sus-Christ", "apr\u00e8s J\u00e9sus-Christ" } }, { "java.time.roc.DatePatterns", { "EEEE d MMMM y G", "d MMMM y G", "d MMM, y G", "d/M/y GGGGG" } }, { "java.time.short.Eras", { "BC", "ap. J.-C." } }, { "roc.DatePatterns", { "EEEE d MMMM y GGGG", "d MMMM y GGGG", "d MMM, y GGGG", "d/M/y G" } }, { "roc.Eras", { "avant RdC", "RdC" } }, { "roc.short.Eras", { "avant RdC", "RdC" } } };
    }
}
