package sun.util.resources.cldr.rn;

import sun.util.resources.OpenListResourceBundle;

public class CurrencyNames_rn extends OpenListResourceBundle
{
    @Override
    protected final Object[][] getContents() {
        return new Object[][] { { "BIF", "FBu" }, { "aed", "Idiramu ryo muri Leta Zunze Ubumwe z'Abarabu" }, { "aoa", "Ikwanza ryo muri Angola" }, { "aud", "Idolari ryo muri Ositaraliya" }, { "bhd", "Idinari ry'iribahireyini" }, { "bif", "Ifaranga ry'Uburundi" }, { "bwp", "Ipula ryo muri Botswana" }, { "cad", "Idolari rya Kanada" }, { "cdf", "Ifaranga rya Kongo" }, { "chf", "Ifaranga ry'Ubusuwisi" }, { "cny", "Iyuwani ryo mu Bushinwa" }, { "cve", "Irikaboveridiyano ryo muri Esikudo" }, { "djf", "Ifaranga ryo muri Jibuti" }, { "dzd", "Idinari ryo muri Alijeriya" }, { "egp", "Ipawundi rya Misiri" }, { "ern", "Irinakufa ryo muri Eritereya" }, { "etb", "Ibiri ryo muri Etiyopiya" }, { "eur", "Iyero" }, { "gbp", "Ipawundi ryo mu Bwongereza" }, { "ghc", "Icedi ryo muri Gana" }, { "gmd", "Idalasi ryo muri Gambiya" }, { "gns", "Ifaranga ryo muri Gineya" }, { "inr", "Irupiya ryo mu Buhindi" }, { "jpy", "Iyeni ry'Ubuyapani" }, { "kes", "Ishilingi rya Kenya" }, { "kmf", "Ifaranga rya Komore" }, { "lrd", "Idolari rya Liberiya" }, { "lsl", "Iloti ryo muro Lesoto" }, { "lyd", "Idinari rya Libiya" }, { "mad", "Idiramu ryo muri Maroke" }, { "mga", "Iriyari ryo muri Madagasikari" }, { "mro", "Ugwiya ryo muri Moritaniya" }, { "mur", "Irupiya ryo mu birwa bya Morise" }, { "mwk", "Ikwaca ryo muri Malawi" }, { "mzm", "Irimetikali ryo muri Mozambike" }, { "nad", "Idolari rya Namibiya" }, { "ngn", "Inayira ryo muri Nijeriya" }, { "rwf", "Ifaranga ry'u Rwanda" }, { "sar", "Iriyari ryo muri Arabiya Sawudite" }, { "scr", "Irupiya ryo mu birwa bya Sayisheli" }, { "sdg", "Ipawundi rya Sudani" }, { "shp", "Ipawundi rya Sente Helena" }, { "sll", "Ilewone" }, { "sos", "Ishilingi ryo muri Somaliya" }, { "std", "Idobura ryo muri Sawotome na Perensipe" }, { "szl", "Ililangeni" }, { "tnd", "Idinari ryo muri Tuniziya" }, { "tzs", "Ishilingi rya Tanzaniya" }, { "ugx", "Ishilingi ry'Ubugande" }, { "usd", "Idolari ry'abanyamerika" }, { "zar", "Irandi ryo muri Afurika y'Epfo" }, { "zmk", "Ikwaca ryo muri Zambiya" }, { "zwd", "Idolari ryo muri Zimbabwe" } };
    }
}
